### ISSUE TITLE
Cannot call `map` from Ramda with same arity but different signatures

### ISSUE THREAD

**Issue by rjmk** [flowtype/flow-typed#101]
The way the typings for `map` in Ramda currently work, if you try and call `map` in two places with the same arity (arguments passed one-by-one, or both at once), but different type arguments (array, object, functor), Flow will blow up.

For example, try adding

```js
const zs: {[key: string]: string} = _.map((x) => x.toString(), { a: 1, b: 2, c: 3 })
```

below [here](https://github.com/flowtype/flow-typed/blob/956d9f3a2748aa4b095debc53772782b00a9c7f5/definitions/npm/ramda_v0.21.x/test_ramda_v0.21.x.js#L145)

and running the tests

cc/ @alexeygolev

**Comment by alexeygolev** [comment]
@rjmk will check tonight. Let me know if you have ideas about the possible reason

**Comment by rjmk** [comment]
@alexeygolev I will do some research on Flow / the links on the inference algorithm you left on the PR. At the moment I'm pretty in the dark about all of this!

**Comment by alexeygolev** [comment]
@rjmk by the way what do you mean by "flow will blow up"?

**Comment by alexeygolev** [comment]
@rjmk can't reproduce or I'm not understanding the problem correctly. If I change the type of object values to `number` in your signature flow will complain which means it works the way it should. Your expression typechecks

**Comment by rjmk** [comment]
@alexeygolev Sorry, horrendous of me not to paste the error output. My issue was that in the type checking error message, it would only consider the members of `map` with array types.

Now, however, I also cannot reproduce. But not could I reproduce when changing the type of object values to `number`. `git diff` shows only the insertion of that line. Upon deleting files ignored by the `.gitignore` the error disappears.

Appears to be anomalous. Sorry for dragging you into that, @a
