### ISSUE TITLE
[jest_v20.x.x] Globals missing: require.requireActual require.requireMock

### ISSUE THREAD

**Issue by Palisand** [flowtype/flow-typed#1027]
```
require.requireActual("...")
        ^^^^^^^^^^^^^ property `requireActual`. Property not found in
require.requireActual("...")
^^^^^^^ object type
```

https://facebook.github.io/jest/docs/api.html#requirerequireactualmodulename

**Comment by carlos-peru** [comment]
I'm experiencing the same problem as @Palisand

**Comment by GAntoine** [comment]
Added in `jest_v21.x.x`

**Comment by danrot** [comment]
I have just updated to the latest version using `flow-typed update jest@21.x.x`, but I am still getting the same message... It is also not clear to me where `require.requireActual` is defined, I can just find `requireActual` alone 🤔

**Comment by micahthomas** [comment]
@danrot and anyone else looking at this, use jest.requireActual
