### ISSUE TITLE
Not building some libraries?

### ISSUE THREAD

**Issue by bradennapier** [flowtype/flow-typed#1070]
So flow-typed is ignoring some packages from my package.json

for example - graphql - nothing gets imported at all for that so I get errors in every single file saying i do not have that module.

Any solution?  I have to ignore node_modules for other reasons.

My guess is no stub is created because the node_modules has the definitions in them but since I can't use these that means it doesn't work now :(

Perhaps some way of forcing stub creation?

**Comment by GAntoine** [comment]
Sure, run `flow-typed create-stub graphql` and you'll get a stub. If you run into issues creating it, try passing the `-o` flag, to overwrite possible existing stubs.
