### ISSUE TITLE
[styled-components_v2.x.x] Getting error on extend

### ISSUE THREAD

**Issue by akronb** [flowtype/flow-typed#1085]
Hi! 
After latest [commit ](https://github.com/flowtype/flow-typed/commit/0d75e491b3f8b95bcc9397e0c08e9f582a9b5312) to styled-components libdef i'm getting this error

```
68: const MenuLinkArrow = MenuLink.extend`
                                   ^^^^^^ property `extend`. Property not found in
68: const MenuLinkArrow = MenuLink.extend`
                          ^^^^^^^^ statics of Link
```

Link is imported from React Router v4

**Comment by GAntoine** [comment]
While someone looks at this, you can modify your local version of `flow-typed/npm/styled-components_v2.x.x.js` to match what it was before the change. If you think you can fix it, a PR would be appreciated!

**Comment by akronb** [comment]
Problem is solved for me with [last commit](https://github.com/flowtype/flow-typed/commit/44a50364fce6475f5f032145966a3251525244fe).

**Comment by akronb** [comment]
I'm getting this error again. 
@mwalkerwells Can you check this?

**Comment by mwalkerwells** [comment]
Cannot tell exactly what ``MenuLink`` is, but is this your use case?

```js
// The Button from the last section without the interpolations
const Button = styled.button`
	color: palevioletred;
	font-size: 1em;
	margin: 1em;
	padding: 0.25em 1em;
	border: 2px solid palevioletred;
	border-radius: 3px;
`;

// We're extending Button with some extra styles
const TomatoButton = Button.extend`
	color: tomato;
	border-color: tomato;
`;
```

**Comment by mwalkerwells** [comment]
That currently doesn't error for me, but if Button is defined as ``const Button = styled.button``, it does.

**Comment by akronb** [comment]
Sorry for lack of information. Here is an example of code that causes this error.
```JSX
// @flow
import React from 'react';
import { Link } from 'react-router-dom';
import styled from 'styled-components';
import arrowImg from '../img/arrow.svg';

const MenuLink = styled(Link)`
  display: inline-block;
  font-weight: 300;
  color: #fff;
  text-decoration: none;
  margin-top: .5rem;
`;

const MenuLinkArrow = MenuLink.extend`
  margin-top: 1rem;

  &:after {
    content: url(${arrowImg});
    margin-left: .5rem;
  }
`;

export default () =>
  (<nav>
    <MenuLink to="#">Item 1</MenuLink>
    <MenuLink to="#">Item 2</MenuLink>
    <MenuLinkArrow to="#">All items</MenuLinkArrow>
  </nav>);
```

**Comment by mwalkerwells** [comment]
Took a refactor, but this should resolve this issue. I'd encourage you to contribute too! I'd be happy to give diff feedback.

**Comment by akronb** [comment]
@mwalkerwells Thanks! It works fine for me
