### ISSUE TITLE
relay problems

### ISSUE THREAD

**Issue by sibelius** [flowtype/flow-typed#1097]
I've received a lot of this when trying to use flow with react-relay

```jsx
node_modules/relay-runtime/lib/isScalarAndEqual.js:0
isScalarAndEqual. Duplicate module provider
current provider. See: node_modules/relay-compiler/lib/isScalarAndEqual.js:0
```

is there any good tips of how to use react-relay with react-native in flow?

**Comment by GAntoine** [comment]
You might have more luck [opening an issue](https://github.com/facebook/flow/issues) at the official flow repo. There are not definitions here for `react-relay`, so I assume it's related to flow core.
