### ISSUE TITLE
Missunderstaning of Lodash documentation.

### ISSUE THREAD

**Issue by Mtnt** [flowtype/flow-typed#1109]
In the lodash documentation some arguments is specified as `object`. It can be read as "just object like `{}`", but all complex entities are inherited from the `object`.
So, looks like in the lodash methods with `object` params can also take arrays and other object-based types. I wrote to the lodash repo an issue https://github.com/lodash/lodash/issues/3296 - you can see an answer of an owner.

**Comment by GAntoine** [comment]
Closing this, as most of the methods which take `object` param use the `Object/?Object` type, as expected, or `T` when the type isn't inferred.
