### ISSUE TITLE
[CLI] Need a `flow-typed update-cache` command

### ISSUE THREAD

**Issue by jeffmo** [flowtype/flow-typed#111]
Currently the cache updates itself if it's been more than 5 days since it was last used.
We should also include an `update-cache` command so users can quickly update the cache themselves.

(Also, while we're at it, might as well add a `--update-cache` flag to the `install` command too)

**Comment by ryyppy** [comment]
Maybe I will give it  a shot if nobody is working on that!

**Comment by jeffmo** [comment]
Go for it!

**Comment by ryyppy** [comment]
This issue should be closed ... I cannot do it sadly :-(
