### ISSUE TITLE
Add a custom source for library imports

### ISSUE THREAD

**Issue by krainboltgreene** [flowtype/flow-typed#1132]
So I have a collection of 78 packages in the @unctionjs organization. They all have distinct types. I would love to submit all 78 packages to flow-typed, but I update regularly and it would become an enormous pain.

It would be awesome if I could supply flow-typed with a custom source for libraries and maintain my own repository of types.

**Comment by GAntoine** [comment]
Out of curiosity, would you consider submitting to `flow-typed` if the `cli` offered a simple way to open a PR with the changes you want to contribute? In that, when you make changes to definitions, you type something like `flow-typed contribute` or `flow-typed contribute thrush`, which automatically opens a PR with your changes.

**Comment by krainboltgreene** [comment]
Yes, I would use that.

**Comment by krainboltgreene** [comment]
I have to say though, at that point aren't we just reinventing npm but for types? Wouldn't it be easier to put a layer on top of npm for this structure?

  - npm has versions
  - npm has safety checks
  - npm has metadata
  - npm has publish, unpublish, and deprecation mechanics
  - npm has locks
  - npm handles random people wanting to add things
  - npm handles organizations AND private packages

All things that flow-typed will eventually (or currently) needs

**Comment by GAntoine** [comment]
Funny, something similar was brought up a while ago: #990

**Comment by GAntoine** [comment]
Closing in favour of #1494
