### ISSUE TITLE
Help with Mongoose typings

### ISSUE THREAD

**Issue by albertorestifo** [flowtype/flow-typed#1140]
I'm trying to create typings for Mongoose, but I don't know if what I want to do is possible.

I want to start simple, so let's ignore for now all the possible ways to define a model in Mongoose. My goal is to make something like this possible, where looking up a property that wasn't defined in the schema will error in Flow.

```js
import mongoose from 'mongoose';

const UserSchema = new mongoose.Schema({
  email: {
    type: String, 
    required: true 
  },
  createdAt: { 
    type: Date, 
    default: Date.now 
  },
});

const User = mongoose.model('User', UserSchema);

// And let's run a query

User.findOne({ email: 'example@example.com' }).exec()
  .then((user) => {
    // $ExpectError
    user.lol
  })
```

This is what I came up with, which doesn't achieve my goal:

```typescript
declare class Mongoose$Schema<Schema> {}

type Mongoose$Query<Schema> = {| [$Keys<Schema>]: any |}
type Mongoose$Projection<Schema> = { [$Keys<Schema>]: any }
                                    
declare type Mongoose$Result<Schema> = {| [$Keys<Schema>]: any |}                                   
                                    
declare interface Mongoose$QueryInterface<Schema> {
  exec(): Promise<Mongoose$Result<Schema> | void>
}

declare class Mongoose$Model<Schema> {
  findOne(query: Mongoose$Query<Schema>, projection?: Mongoose$Projection<Schema>): Mongoose$QueryInterface<Schema>
}
```

Is what I wish to do even possible?

**Comment by mwalkerwells** [comment]
This works correctly, with one downside: I cannot transform the Type using an intersection (commented out type definition). ☹️

In this example, ``user.email`` is an instance of ``String``, not a ``string`` literal.

```js
// @flow

// type TypeTransform =
//   & (({ type: typeof String }) => string)
//   & (({ type: typeof Date }) => Date)

type TypeTransform = <T>({ type: T }) => T

type MongooseSchemaConfigTransform<Config>
  = $ObjMap<Config, TypeTransform>

declare module 'mongoose' {
  declare class Schema<Config> {
    constructor(config: Config): void
  }
  declare type Model<Config> = {
    findOne: ($Shape<MongooseSchemaConfigTransform<Config>>) =>
      { exec: void => Promise<MongooseSchemaConfigTransform<Config>> },
  }

  declare export default {
    model: <Config>(string, Schema<Config>) => Model<Config>,
    Schema: typeof Schema,
  }
}

```

**Comment by mwalkerwells** [comment]
@avikchaudhuri Given the context of (https://twitter.com/mwalkerwells/status/880131654337024001), here's an interesting HKT limitation with ``$ObjMap``: no intersection transform functions.

**Comment by albertorestifo** [comment]
Yes, that seems to work, thanks for the tip!

I'll try to gradually implement everything but the library has so many different use-cases that it's not an easy task to create complete typings.

**Comment by sibelius** [comment]
check this out https://github.com/entria/flow-typed-wip/issues/1

**Comment by nodkz** [comment]
Who interested in mongoose type defs, please follow [PR 1196](https://github.com/flowtype/flow-typed/pull/1196)

**Comment by sibelius** [comment]
@albertorestifo @nodkz works is enough for your use case?

**Comment by albertorestifo** [comment]
Yeah I think this issue can be closed. 

Thank you all for the work!
