### ISSUE TITLE
Redux nested combineReducer

### ISSUE THREAD

**Issue by Baptiste-Garcin** [flowtype/flow-typed#1148]
Hi,

In my project, I use nested reducers. As example :
```
const reducer = combineReducers({
  posts,
  user: combineReducers({
    localisation,
    watch,
  }),
});
```
The problem is that the redux libDef is not accepting this usage.
Does it mean that it is a wrong way to do that ?
For now, i use a workaround :
`declare function combineReducers<O: Object, A>(reducers: O): any;`
instead of
`declare function combineReducers<O: Object, A>(reducers: O): CombinedReducer<$ObjMap<O, <S>(r: Reducer<S, any>) => S>, A>;`
Is anyone know a better way ?

Thanks

**Comment by cef62** [comment]
I've the same issue. @Baptiste-Garcin have you found a better solution?

**Comment by Baptiste-Garcin** [comment]
Nop sorry... But still interested
