### ISSUE TITLE
[marked_v0.3.x] flow 53.1 Classes may not have properties named `constructor`

### ISSUE THREAD

**Issue by rosskevin** [flowtype/flow-typed#1165]
```
flow-typed/npm/marked_v0.3.x.js:9
  9:   constructor: (o?: marked$MarkedOptions) => marked$Renderer
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Classes may not have properties named `constructor`
```
Using flow-typed (latest commit): 3b064385b759e1e75ff181e7fcc3572875e142ee

/related #7788

There are several constructor signatures that need addressed in this file.

**Comment by FezVrasta** [comment]
Hey @rosskevin did you find a solution for this?

**Comment by rosskevin** [comment]
I manually commented out the constructor.

**Comment by JohnPucciarelli** [comment]
@FezVrasta here's a pull request for a fix: https://github.com/flowtype/flow-typed/pull/1197/commits
