### ISSUE TITLE
lodash: improper typing of "Object"

### ISSUE THREAD

**Issue by bradennapier** [flowtype/flow-typed#1168]
When lodash accepts an "object" it actually also accepts an Array but Object is used.  From what I can tell this should be changed to using generics instead of ?Object

For example in _.get()

```js
_.get(['one', 'two'], '2')
```

the above should work but flowtyped will complain here.

**Comment by GAntoine** [comment]
Closing as the current implementation of the typedef does support using arrays. `Object` is a parent of `Array`. From the test files:

```javascript
// Array — not documented, but _.get does support arrays
get([1, 2, 3], "0");
get(["foo", "bar", "baz"], "[1]");
get([{ a: "foo" }, { b: "bar" }, { c: "baz" }], "2");
get([[1, 2], [3, 4], [5, 6], [7, 8]], "3");
```
