### ISSUE TITLE
Tape definition file

### ISSUE THREAD

**Issue by ryyppy** [flowtype/flow-typed#118]
Hey,
I am almost done with the `tape` libdef, but I am stuck with a specific kind of definition, so I hope I get some direction how I solve this...

**Considering following usage:**

```javascript
import test from 'tape';

// 1
test.skip('mytest', (t) => { t.end(); });

// 2
test('myothertest', (t) => {
  t.end();
});
```

I could only get `//2` running with this declaration:

```javascript
declare module 'tape' {
  type TestBody = Function;
  type TestOptions = Object;

  type TestFn = (description: string, fnOrOpts: TestBody | TestOptions, fn?: TestBody) => void;
  declare module.exports: TestFn;
}
```

But I have no idea how I can export a class Function `Test`, which can be called as `test()`, but also supports the static function `skip`...

I tried something like this (actually a desperate attempt):
```javascript
...
declare class Test {
  constructor(desc: string, fnOrOpts: TestBody | TestOptions, fn?: TestBody): void
  static skip(): void
}

...
declare module.exports: Test
```

But of course, this does not work as expected...

Any ideas?

**Comment by mk0x9** [comment]
```javascript
// 1
test.skip('mytest', (t) => { t.end(); });

// 2
test('myothertest', (t) => {
  t.end();
});
```

Only first arguments differ (with same type), second arguments are the same.

>  But I have no idea how I can export a class Function `Test`, which can be called as `test()`

[Class functions could be called only with keyword `new`](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-ecmascript-function-objects-call-thisargument-argumentslist).

`Test` is probably ordinary function with attached method `skip`.

According to [Flow documentation](http://flowtype.org/docs/functions.html) it is not possible to annotate overloaded functions yet (check last paragraph, _Overloading Caution_).

You can try something like this though:

```javascript
interface tape$testObject {
     plan: (n: number) => void,
     end: (err?: any) => void
};

type tape$testOpts = {
    skip?: boolean,
    timeout: number
} | {
    skip: boolean,
    timeout?: number
};

interface tape$testFunctions {
    skip: (name: string, cb: tape$testObject) => void,
    onFinish: (cb: Function) => void
}

type tape$testCb = (t: tape$testObject) => void;

declare module 'tape' {
    declare module.exports: (a: string|tape$testOpts|tape$testCb, b?: tape$testOpts|tape$testCb, c?: tape$testCb, ...rest: Array<void>) => void;
}
```

Also not sure if it's possible to annotate methods on function object.

**Comment by ryyppy** [comment]
Actually, I just realized that our current `mocha` libdef does exactly what I am looking for:

```
declare var describe : {
    (name:string, spec:() => void): void;
    only(description:string, spec:() => void): void;
    skip(description:string, spec:() => void): void;
    timeout(ms:number): void;
};
```

but to be honest, I don't understand how this makes sense in a semantical way ;-)
I will try this out, thank you very much for the input @mk0x9 !

**Comment by alexeygolev** [comment]
@ryyppy was about to mention this approach. What do you find confusing though?

**Comment by ryyppy** [comment]
When I read the `declare` I read following:

"Declare me an entity `describe`, which is an `Object` containing the attributes `only`, `skip`, `timeout` and... not `(name: string): void`?"

Is the last part the constructor method? but it is not declared as a `class`, so what is this witchcraft?

**Comment by alexeygolev** [comment]
@ryyppy maybe I'm too naive with the way I'm reading it but I read the `(name:string, spec:() => void): void` as "you can also call this thing as a function":)
the thing is — you're not going to be using your "test" to typecheck if it indeed has all the methods. So what you actually need it to be is just a bag of function definitions one of which happen to define a function call () => void

**Comment by mk0x9** [comment]
> Is the last part the constructor method? but it is not declared as a class, so what is this witchcraft?

Nope, functions are objects too.

```javascript
const fn = () => {};
console.log(fn instanceof Object); // true
```

**Comment by ryyppy** [comment]
Exactly! And that's why by my intuition, I would not assume that defining a `(something: any): void` inside a `Object` would implicitly define it's `call` behavior... It made more sense for me to define this stuff as a Union / Intersection type instead ... `declare module.exports: (arg) => void | { only: () => void }` ... because for me, it would either be an object with said `only` method, or a `Function` which can be called with `arg`... (which is apparently wrong)

Anyways, this tips helped me A LOT understanding the parsing mechanisms! So thank you very much for clarifying 👍  🎉 

Hopefully I will get my PR ready by tomorrow, maybe you will have a look over it then ;-)

**Comment by ryyppy** [comment]
PR: #127
