### ISSUE TITLE
`flow-typed install` hangs

### ISSUE THREAD

**Issue by aaronshaf** [flowtype/flow-typed#1184]
```
• Found 117 dependencies in package.json to install libdefs for. Searching...
• rebasing flow-typed cache...
```

It'd be useful to show progress with more verbosity so we could know where it is failing.

**Comment by johnryan** [comment]
fwiw i notices a pretty huge improvement by running `rm -rf ~/.flow-typed/`

**Comment by danielbartsch** [comment]
you can do
`flow-typed install --verbose`

Then it'll show exactly what dependencies where found. But it still hangs at `rebasing flow-typed cache` with no further information...

I cannot install flow types anymore because of this.

**Comment by BarsaTM** [comment]
Hello,
You can check out this issue: #909
Looks like that this issue appears on specific node version.

In my case Node 8.4.0 fixes the problem.

**Comment by GAntoine** [comment]
Closing as per the comment above (also not an issue on latest/8.6.0).
