### ISSUE TITLE
redux - Middleware

### ISSUE THREAD

**Issue by alexreardon** [flowtype/flow-typed#1193]
The first argument of the middleware needs to be a `MiddlewareAPI`

```js
declare type Middleware<S, A, D = Dispatch<A>> =
    (api: MiddlewareAPI<S, A, D>) =>
      (next: D) => D;
```

Could this be changed so that you could also pass in a `Store` rather than a `MiddlewareAPI`?. I am finding that I cannot use my `Store` type for the first argument - I need to create another type: MiddlewareApi

**What I want to do**
```js
type Store = ReactStore<State, Action, Dispatch>

(store: Store) => (next: Dispatch) => ...
```

**What I need to do currently**
```js
(store: MiddlewareAPI<State, Action, Dispatch>) => (next: Dispatch) => ...
```

**Comment by stryju** [comment]
To be clear, you're not getting your store inside of middleware, but a subset of it - the methods are called the same, which might cause confusion.
