### ISSUE TITLE
flow-typed install not fetching dependencies of dependencies

### ISSUE THREAD

**Issue by kevinjalbert** [flowtype/flow-typed#1204]
The following shows me adding `react-router-dom` to a vanilla `create-react-app` project that has a single flow annotation to allow flow-typed to work.

```
❯ yarn add react-router-dom
yarn add v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 7 new dependencies.
├─ history@4.7.2
├─ hoist-non-react-statics@2.3.1
├─ react-router-dom@4.2.2
├─ react-router@4.2.0
├─ resolve-pathname@2.2.0
├─ value-equal@0.4.0
└─ warning@3.0.0
Done in 6.56s.
```

I then install `flow-typed` and installed the types.

```
❯ flow-typed install --overwrite
• Found 6 dependencies in package.json to install libdefs for. Searching...
• rebasing flow-typed cache...
• Installing 2 libDefs...
  • flow-bin_v0.x.x.js
    └> ./flow-typed/npm/flow-bin_v0.x.x.js
flow-bin
/Users/jalbert/Projects/theScore/temp/flow-typed/npm
  • react-router-dom_v4.x.x.js
    └> ./flow-typed/npm/react-router-dom_v4.x.x.js
react-router-dom
/Users/jalbert/Projects/theScore/temp/flow-typed/npm
• Generating stubs for untyped dependencies...
  • flow@^0.2.3
    └> flow-typed/npm/flow_vx.x.x.js
  • react-scripts@1.0.12
    └> flow-typed/npm/react-scripts_vx.x.x.js

!! No flow@v0.54.0-compatible libdefs found in flow-typed for the above untyped dependencies !!

I've generated `any`-typed stubs for these packages, but consider submitting
libdefs for them to https://github.com/flowtype/flow-typed/
```

I was expecting to have the type definitions for `react-router` as it was a dependancies of `react-router-dom`. When I look in the `flow-typed` director it isn't present.

```
❯ tree flow-typed
flow-typed
└── npm
    ├── flow-bin_v0.x.x.js
    ├── flow_vx.x.x.js
    ├── react-router-dom_v4.x.x.js
    └── react-scripts_vx.x.x.js

1 directory, 4 files
```

This leaves me having to explicitly declare dependencies of dependencies if I'm going to use them. I guess this isn't a bad thing, in reality as this makes the `package.json` more _true_ in what is declared as dependencies of my project.

I'm just wondering if this is the expected behaviour, or if I'm doing something wrong?

**Comment by spencerhakim** [comment]
>This leaves me having to explicitly declare dependencies of dependencies if I'm going to use them. I guess this isn't a bad thing, in reality as this makes the `package.json` more *true* in what is declared as dependencies of my project.

You need to include ALL your direct dependencies in your `package.json`, regardless of whether or not they happen to also be dependencies of your other dependencies. This applies to the `package.json` ecosystem as a whole, not just for `flow-typed`.

**Comment by kevinjalbert** [comment]
@spencerhakim I figured as much. 👍 

Thanks for the insight on that, it was pretty much my hunch when reflecting on it.

**Comment by romanlv** [comment]
Isn't explicitly defining ALL dependencies can create a situation when multiple versions of the same library are included in the bundle?

 E.g. 

`packageX` -> package.json `{"redux": "^3.7.2"}`

but in the project, package.json install added latest verison `{"redux": "^4.0"}`
If later in the code I'm using `import .. from "redux"` it will result in both versions of the `redux` included, which I'm trying to avoid. 

Ideally, there should be a way to specify package.json file to be used to install dependencies from. `-p` can be used right now, but it requires `flow-bin` package to be mentioned there....
