### ISSUE TITLE
non-deterministic travis-ci builds

### ISSUE THREAD

**Issue by followbl** [flowtype/flow-typed#1229]
of course this is often common in ci builds...is this known? or something that needs to be looked at? 

https://travis-ci.org/flowtype/flow-typed/builds/272655614 - ❌ 
https://travis-ci.org/flowtype/flow-typed/builds/272690444 - ❌ [user-error]
https://travis-ci.org/flowtype/flow-typed/builds/272693101 - ❌ 
https://travis-ci.org/flowtype/flow-typed/builds/272694371 - ✅ 

the 2nd was my fault after I ran the tests locally and installed the latest-prettier and committed some wrong linting rule...but of the 3 that had the same code, only 1 out of 3 passed.

**Comment by GAntoine** [comment]
You're right in that the output of one of the tests is non-deterministic. Another test also assumes a connection to npm is available, which isn't always the case (though I'd wager the second one won't happen very often). I've tried taking a crack at it some time ago, but didn't get very far.

Basically, in the test that's failing, the array that's returned contains 2 objects `[{A}, {B}]`, and although they may appear in either order, the spec itself only expects one. It would be awesome if someone with testing experience could try rewriting the `expect` in a way that accepts either order.

**Comment by followbl** [comment]
@GAntoine thank you for confirming this wasn't a one-off occurrence and your detailed message. I'll take a look and report back
