### ISSUE TITLE
Crash with backslash path separator in cli/run-tests

### ISSUE THREAD

**Issue by HyperBrain** [flowtype/flow-typed#1234]
After checkout, when executing `./cli/dist/cli.js run-tests` the CLI crashes in case `path.sep` is a backslash (`\`). For me that's the case in my Git bash.

```
 cli/dist/cli.js run-tests
C:\Projects\flow\flow-typed\cli\dist\commands\runTests.js:70
var basePathRegex = new RegExp('definitions' + _node.path.sep + 'npm' + _node.path.sep + '(@[^' + _node.path.sep + ']*' + _node.path.sep + ')?[^' + _node.path.sep + ']*' + _node.path.sep + '?');
```

The reason is, that the use of path.sep in the RegExp is not correct in the backslash case. In that case the separator has to be doubled, as backslash as a regexp character has to be escaped properly.

Instead of using `path.sep` directly, the possibly escaped path.sep should be build before and then inserted into the cli.

**Comment by yizhoucao** [comment]
Same issue here on my windows laptop

**Comment by pablowatson** [comment]
Same issue on windows. Cannot run flow-type at all.
