### ISSUE TITLE
How to allow a specific element, but also allows elements that return that specific element when rendered

### ISSUE THREAD

**Issue by JCMais** [flowtype/flow-typed#1237]
On https://flow.org/en/docs/react/children/#toc-only-allowing-a-specific-element-type-as-children it's shown how to allow only one children of specific type, but what about if my component returns that exact type?

Let's say I want to only allow `Text` elements and scalar values for the react-native Text element, so we have:
```
type ReactOnlyElementTypeAsChildren<T> = void | null | boolean | number | string | React$Element<typeof Text>;
```

This works great, if I do:
```
function DumbComp() { return <View></View>; }
function MyComp() {
  return <Text><DumbComp>{/* ... /*}</DumbComp></Text>
}
```

it throws an error as expected

```
 Error: test.js:8
 22:       <Text><DumbComp>{/* ... /*}</DumbComp></Text>
                  ^^^^^^^^^ exact type: object type. This type is incompatible with ....
```                     

But what if my component returns a `<Text>` element itself? like

```
function DumbComp() { return <Text></Text>; }
```

The error is still there, as expected. But is there any way to make flow understand  that?

**Comment by GAntoine** [comment]
As this isn't related to a typedef, you might have more luck asking on the [flow github page](https://github.com/facebook/flow).
