### ISSUE TITLE
Tuple unions are not working correctly

### ISSUE THREAD

**Issue by ryanscottaudio** [flowtype/flow-typed#1246]
This throws both when I use the tuple length and when I use the elements within the tuple to figure out which kind of tuple it is:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAqArjjHgDJ4B2A5hgBYCMYAvGANpMC6A3JrgIkylGvQYAmNpwAMAGjA9+2fEVLkAsgEMsAIwLth5KnUYsAPmpEnxE-qgDGcagGcMYDOrwAuK5p360hzyinyOzm5gAG5aMMR4LOyeIgB05KYMbKzsLAD8Hl7B3GC+yeRcYU6u7jFxeFJJhTLF2Tlg+WV4RSUFIhW8QA

I would think this should work both ways I'm trying it.

**Comment by GAntoine** [comment]
Closing, as this is a flow issue unrelated to `flow-typed`. You're more then welcome to open an issue at the [facebook/flow](https://github.com/facebook/flow) repository.

**Comment by ryanscottaudio** [comment]
thanks, sorry about that, must've had both tabs open
