### ISSUE TITLE
[CONTRIB] Prefixing namespaces

### ISSUE THREAD

**Issue by ryyppy** [flowtype/flow-typed#126]
Since a few PRs start adapting namespaces like `$npm$bull` or `$npm$pad$type` ... would it be a good idea to define namespace rules in `CONTRIBUTING.md`?

**Comment by marudor** [comment]
I think it is a good Idea.
I would be in favor to drop the $npm and use a <packageName>$ prefix.
so $npm$bull would be bull$Foobar.
We should probably mention that only globals need prefixing - not types/Classes within a module.
@jeffmo Your thought?

**Comment by jeffmo** [comment]
I had been advocating for `$npm` for the same reasons @LegNeato mentioned over in https://github.com/flowtype/flow-typed/pull/124/files#r64975115

There's a reasonable chance we'll want to add other namespaces than just npm in the future (things like core libraries, application-specific global definitions that don't end up in flow-typed at all, and even libraries that happen to not be on `npm -- as rare is that probably will be).

Longer term we'll move this inside the `declare module {}` body instead and shouldn't need to pollute the global scope with non-global types. FWIW: I'm about halfway through the work to revamp `declare module {}`, so hopefully that should be ready to ship in the next several weeks.

**Comment by ryyppy** [comment]
Okay, sounds reasonable!
Not sure how we should handle this, ... probably just leave everything how it is right now?
Anyways, we should maybe put this somewhere in the Contribution guidelines, so people definitely know.

Any github-issue link for your `declare module {}` revamp? Kinda sounds we finally get support for `export type` syntax? :-)

**Comment by jeffmo** [comment]
> Not sure how we should handle this, ... probably just leave everything how it is right now?
Anyways, we should maybe put this somewhere in the Contribution guidelines, so people definitely know.

Yea that seems like a good idea. I'll update the guide now.

> Any github-issue link for your `declare module {}` revamp?

I don't have anything tracking it right now, but I guess we can use this issue to track it? I'm hoping to have something ready sometime next week here.

**Comment by jeffmo** [comment]
Threw this together: https://github.com/flowtype/flow-typed/pull/137

**Comment by ryyppy** [comment]
I think this issue is done
