### ISSUE TITLE
What version of 'react-i18next' should I use?

### ISSUE THREAD

**Issue by MichaelDeBoey** [flowtype/flow-typed#1279]
I thought that the version in this directory is the same as the version of the package itself, but when I was searching for the [`react-i18next`](https://github.com/i18next/react-i18next) libdef, I only found `v2.x.x ` (`flow` version: `>=v0.30.x <=v0.39.x`) & `v1.10.x` (`flow` version: `>=v0.30.x <=v0.52.x`).
And there aren't any libdef's exposed from de library 😕

I use the latest `flow-bin` (`^0.55.0`)

**Comment by marudor** [comment]
With 0.53 there were some breaking Changes.
So I most likely restricted it to <=v0.52.x to ensure it is working.
As the typedefs for react-i18next v1.1 do not work for flow > 0.52.x

**Comment by MichaelDeBoey** [comment]
OK I understand that, but shouldn't libdef for `v5.x` also be in the repository?
Now there's only `v1.10.x` & `v2.x.x`, but the package already is [`v5.4.1`](https://github.com/i18next/react-i18next/blob/master/CHANGELOG.md)... 😕

I suppose that it's not provided and a PR would be welcome?

If so, I'd like to help with that, but I'm not experienced in making one, so any help would be awesome then 🙂
