### ISSUE TITLE
[COMMUNITY] React-Europe

### ISSUE THREAD

**Issue by ryyppy** [flowtype/flow-typed#128]
I saw that @jeffmo announced a talk for React-Europe 2016 about `flow` and that's why I wanted to ask if anyone here is also going there and keen to meet up? Would be cool to talk about flow, the future and other stuff :-)

**Comment by jeffmo** [comment]
Yes let's meet up! :) I get in on Wednesday afternoon and will be around through Friday night

**Comment by ryyppy** [comment]
sweet! I will be there from Thursday until Sunday...
What about @marudor and @splodingsocks ? 

Are you also there? :-)

**Comment by splodingsocks** [comment]
Oh man, sounds like so much fun! I won't be there, unfortunately, though I'd love to go to React Europe someday.

**Comment by marudor** [comment]
@ryyppy Sadly I've got no ticket. Otherwise I would probably be there.
