### ISSUE TITLE
Flow doesn't understand lodash type checking.

### ISSUE THREAD

**Issue by philipp-sorin** [flowtype/flow-typed#1281]
example 
```
import { isUndefined } from 'lodash';

function bar(value: string) {}
function foo(value?: string) {
  if (!isUndefined(value)) {
     bar(value);// undefined. This type is incompatible with expected param type of string;
  }
}
```

**Comment by marudor** [comment]
Nothing we can do with flow-typed. Thats something flow needs to handle.
Although I doubt that will be possible. Unless you use basic JS checks.

**Comment by philipp-sorin** [comment]
@marudor, as far as I know, flow has %checks syntax
https://github.com/facebook/flow/issues/3048
