### ISSUE TITLE
Required module not found

### ISSUE THREAD

**Issue by kingaiakab** [flowtype/flow-typed#1287]
I use flow-typed for libdef, but it doesn't seem to work.

```
// @flow

import { Foo } from 'some-lib'; // ERROR: required module not found 
```

I have this in my `.flowconfig` file: 
```
[libs]
<PROJECT_ROOT>/flow-typed
```

And I have a file `flow-typed/some-lib.js`:

```
// @flow

declare module 'some-lib' {
  declare export var Foo: any;
}
```

Am I missing something?

**Comment by sunny-mittal** [comment]
I had the same issue and added `node_modules` to the `[lib]` section of my .flowconfig. I just started with flow today so I may be doing it wrong, but it seemed to work for me. Let me know if it does for you!
