### ISSUE TITLE
[Help needed] Maintainer needed

### ISSUE THREAD

**Issue by marudor** [flowtype/flow-typed#1296]
As you may have noticed I'm currently the one mainly maintaining this repo.
It is to much work to do in my free time though. Thats why I rarely address issues and usually just merge PRs after a quick check.

I would like to have more maintainer - Is there anyone who thinks he can help and is up to the responsibility?

**Comment by TrySound** [comment]
I can help with a few projects I am interested in.

**Comment by GAntoine** [comment]
I'd be happy to help with the codebase itself, at this point I'm pretty familiar with it.

**Comment by h-michael** [comment]
I can help maintaining some projects about, react, redux.

**Comment by kogai** [comment]
Would be nice to contribute 🙋

**Comment by MichaelDeBoey** [comment]
I'm happy to help maintaining the project. 🙂

**Comment by AugustinLF** [comment]
Could help too :)

**Comment by marudor** [comment]
I've added (or rather instructed someone to add) @GAntoine as maintainer.
He did quite a lot of PRs and helped a lot.

I will see how we manage with him as support.
Thanks for the offers to the rest.
If needed I will contact you :)

**Comment by GAntoine** [comment]
Thanks marudor, and thanks everyone for answering the call!

For those eager to help, I'll be pinging familiar faces when looking over PRs once in a while, namely people I've seem working on one typedef or another.
