### ISSUE TITLE
Difference between React$ComponentType and React.ComponentType?

### ISSUE THREAD

**Issue by phillipj** [flowtype/flow-typed#1302]
I'm currently experiencing an issue where replacing `React$ComponentType` with `React.ComponentType` in [react-intl's injectIntl()](https://github.com/flowtype/flow-typed/blob/master/definitions/npm/react-intl_v2.x.x/flow_v0.53.x-/react-intl_v2.x.x.js#L125) libdef fixes a type checking error.

```patch
iff --git a/flow-typed/npm/react-intl_v2.x.x.js b/flow-typed/npm/react-intl_v2.x.x.js
index 07744d6..2a78d3e 100644
--- a/flow-typed/npm/react-intl_v2.x.x.js
+++ b/flow-typed/npm/react-intl_v2.x.x.js
@@ -126,14 +126,14 @@ declare module "react-intl" {
     messageDescriptors: T
   ): T;
   declare function injectIntl<Props: {}>(
-    WrappedComponent: React$ComponentType<
+    WrappedComponent: React.ComponentType<
       { intl: $npm$ReactIntl$IntlShape } & Props
     >,
     options?: {
       intlPropName?: string,
       withRef?: boolean
     }
-  ): React$ComponentType<Props>;
+  ): React.ComponentType<Props>;
   declare function formatMessage(
     messageDescriptor: $npm$ReactIntl$MessageDescriptor,
     values?: Object
```

Although the above modification obviously does the job, and something I was about to open a PR for, I'd really appreciate understanding **why** that works rather than something I found out of luck by reading the [React utility types](https://flow.org/en/docs/react/types/) 🤔 

<details>
<summary>flow check error for reference</summary>

```bash
Error: src/components/more/MorePage.js:84
                 v----------------
 84:             <EnterDepositCode
 85:               onSubmit={submitDepositCode}
 86:               loading={submitDepositCodeLoading}
...:
 89:             />
                 -^ React element `EnterDepositCode`
 43: export class EnterDepositCode extends React.Component<Props, State> {
                                                           ^^^^^ property `intl`. Property not found in. See: src/components/more/EnterDepositCode.js:43
                 v----------------
 84:             <EnterDepositCode
 85:               onSubmit={submitDepositCode}
 86:               loading={submitDepositCodeLoading}
...:
 89:             />
                 -^ props of React element `EnterDepositCode`
```
</details><br>

Any hints?

**Comment by phillipj** [comment]
Today I'm suddenly seeing this error with the above patch:

```bash
Library type error:
flow-typed/npm/react-intl_v2.x.x.js:129
129:     WrappedComponent: React.ComponentType<
                           ^^^^^ identifier `React`. Could not resolve name
```

Which never occurred on my machine yesterday for some reason.

Guess there's good reason to stick with `React$ComponentType`, it's just not obvious to me.

**Comment by kalley** [comment]
To use `React.ComponentType` you have to use the star import (`import * as React from 'react'). If you haven't imported react that way, those types are not available off of `React`. With the `$` separator, you have access to the globally defined types.

**Comment by marudor** [comment]
Exactly.
It's best to use React.ComponentType
as React$ComponentType is considered private.
Just import React right after the declare module.

**Comment by phillipj** [comment]
Aha, thanks a lot for explaining the differences!

With your comments, I assume that flow-typed libdefs are required to use `React$ComponentType`, but application code could use `React.ComponentType` as long as the entire React namespace has been required first.

**Comment by marudor** [comment]
Actually it should be able to use React.ComponentType in flow-typed.
```
declare module 'example' {
    import type * as React from 'react';
}
```
SHOULD work.

**Comment by sibelius** [comment]
`import type * as React from 'react';` does not work


> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ import type * as React. This is invalid syntax. Maybe you meant: `import type React from "react"`?

**Comment by sibelius** [comment]
`import type React from 'react'` does not work either

> ^^^^^ Default import from `react`. The default export is a value, but not a type. `import type` only works on type exports like type aliases, interfaces, and classes. If you intended to import the type *of* a value, please use `import typeof` instead.

**Comment by sibelius** [comment]
`import * as React from 'react';` neither
       ^^^^^^ Imports within a `declare module` body must always be `import type` or `import typeof`!

**Comment by snaumov** [comment]
@kalley 

I presume, this is gonna be correct import as well instead of importing everything?

`import type {ComponentType} from 'react' `

**Comment by kalley** [comment]
@snaumov Yes, that is correct. That's how I use it in my applications.
