### ISSUE TITLE
framesync Malformed flow-version directory name

### ISSUE THREAD

**Issue by jbarabander** [flowtype/flow-typed#1303]
When attempting to run ```flow-typed install``` in my project I get the following issue:
```sh
UNCAUGHT ERROR: Error: npm/framesync_v3.x.x/flow_v0.16.0: Malformed flow-version directory name! Expected the name to be formatted as 'flow_all' or 'flow_-?v<VERSION>' or 'flow_v<VERSION>-?' or 'flow_v<VERSION>-v<VERSION>' (for a range).
```
I assume this is similar to #611 and would be happy to make a PR fixing this.

**Comment by GAntoine** [comment]
Seems like it, a PR would be appreciated! Ping me when it's open and I'll take a look.

**Comment by jbarabander** [comment]
@GAntoine Will do!  PR coming shortly.

**Comment by jbarabander** [comment]
@GAntoine: Its open!  Thanks for all the great work you guys do on this library!
