### ISSUE TITLE
`flow-typed install --ignoreDef peer bundle` does not work

### ISSUE THREAD

**Issue by amilajack** [flowtype/flow-typed#1308]
The [wiki](https://github.com/flowtype/flow-typed/wiki/CLI-Commands-&-Flags#examples-1) says that running the command `flow-typed install --ignoreDef peer bundle` will ignore installation of peer and bundle types. Instead, it fails with the following error:

```
ERROR: Please specify npm package names in the format of `foo@1.2.3`
```

**Comment by GAntoine** [comment]
That's a typo, my bad. It should be `--ignoreDeps`. I'll fix it in the wiki in a sec.
