### ISSUE TITLE
Flow types for Flow JSON output

### ISSUE THREAD

**Issue by nmote** [flowtype/flow-typed#131]
Could we have Flow types for the output of the JSON versions of various Flow commands? I'm happy to contribute some but obviously these shouldn't be in the `npm` namespace, so I'm not sure where they should go. If you help me figure that out I'll put up a PR.

**Comment by jeffmo** [comment]
So I think the ideal approach to something like this would be to build a consolidated JS library that abstracts calls to Flow into an actual JS API. I started playing around with this over [here](https://github.com/facebook/flow/pull/1360), but we could pick it back up again.

**Comment by ryyppy** [comment]
I will fork it, ... since the cli is quite deep-water with secret commands (AFAIK I only found out about certain features through either `flow --help`, reading vim-flow or other hidden resources) ... 

What commands are missing here?
