### ISSUE TITLE
create method on axios is missing

### ISSUE THREAD

**Issue by despairblue** [flowtype/flow-typed#133]
Does adding this to the Axios class fix it?

```js
  declare class Axios {
    create: <T>(config?: AxiosXHRConfigBase<T>) => Axios;
  }
```

**Comment by ryyppy** [comment]
Just by reading the docs, there would be `baseURL` missing from the `config` object... not sure if the `create` config and the `constructor` config are the same?

**Comment by jeffmo** [comment]
Feel free to send a PR suggesting an update if there's something missing on this libdef
