### ISSUE TITLE
Regex change in #1315 leads to failure of matches for Windows paths

### ISSUE THREAD

**Issue by HyperBrain** [flowtype/flow-typed#1335]
In #1315 , a path matching regex was changed to prevent crashes on Windows where an invalid regex would be created (due to missing escapes for backslashes).

The changed code was in `runTests.js`:
Original regex:
`definitions${path.sep}npm${path.sep}(\@[^${path.sep}]*${path.sep})?[^${path.sep}]*${path.sep}?`

The change just replaced all `path.sep` with `/`.

The problem now is, that the regex will not match any paths returned by Windows anymore, because they natively contain backslashes.

In my opinion there are 2 feasible approaches to fix the "fix" properly:

(1) Use the original regex, but escape `path.sep` properly in case it is a backslash:
```
const escapedPathSep = path.sep === '\\' ? '\\\\' : path.sep;
... `definitions${escapedPathSep}npm${escapedPathSep}(\@[^${escapedPathSep}]*${escapedPathSep})?[^${escapedPathSep}]*${escapedPathSep}?`
```

(2) Normalize the path so that it only contains slashes:
```
`definitions${path.sep}npm${path.sep}(\@[^${path.sep}]*${path.sep})?[^${path.sep}]*${path.sep}?`.replace('\\', '')
```

(1) would be the most compatible solution as (2) might break if paths explicitly contain backslashes on Unix filesystems.

**Comment by GAntoine** [comment]
@jkomyno @kulmajaba Thoughts? I mean it makes sense to me, but so did the original PR. I can't test this on Windows either, so I'll leave it up to whatever comes out of this discussion, and we'll go with that.

**Comment by jkomyno** [comment]
@GAntoine I've cloned and installed globally my fork of flowtyped (even with master as my PR was merged) and on Windows 10 `flow-typed install something@x.x.x` works as expected

**Comment by HyperBrain** [comment]
The match failure should only appear if onlyChanged is set to `true` in the search: https://github.com/flowtype/flow-typed/blob/master/cli/src/commands/runTests.js#L49-L69

**Comment by GAntoine** [comment]
@HyperBrain I'm going to throw together a fix for this bug. I'll ping you when the PR is up, since I'll need someone on a windows system to test the fix, if that's alright with you.

**Comment by ebrearley** [comment]
@GAntoine I can also test it for you on my Windows machine if you need it.

**Comment by kulmajaba** [comment]
Okay, this makes more sense than the original PR. My bad, didn't realize regex is built in global scope so I thought "it crashed before and now it doesn't, must work then."

**Comment by HyperBrain** [comment]
@GAntoine Yes, that's fine for me, I'll test it then. BTW, only my first (1) suggestion will work, as I recognized that the replace (`\\, ''`) in (2) would also remove control backslashes from the regex, which is not what we want here ;-)
