### ISSUE TITLE
installing jasmine breaks flow-typed

### ISSUE THREAD

**Issue by stevenalanstark** [flowtype/flow-typed#1368]
if I install the jasmine typed definitions it breaks flow-typed, I can not install any new definitions without deleting jasmine definitions and trying again. Clean cache is not required.

Jasmine@2.4

the error:

`UNCAUGHT ERROR: Error: jasmine_v2.4.x/flow_vx.x.x: The major version of a Flow version string cannot be `x`, it must be a number!`

**Comment by GAntoine** [comment]
I've got a fix for it open at #1341. We're just discussing it at the moment.
