### ISSUE TITLE
Ramda declarations, destructuring imports

### ISSUE THREAD

**Issue by bwestergard** [flowtype/flow-typed#139]
To grab the interface file I ran: `flow-typed install ramda -f 0.26`, then added a line to my `.flowconfig` to produce:
```
[libs]
decls
flow-typed/npm
```

I created a trivial test file...

```js
/* @flow weak */
import { identity } from 'ramda'
console.log(identity(3))
```

And on type checking got...

```
handlers/scratch.js:3
  3: import { identity } from 'ramda'
              ^^^^^^^^ Named import from module `ramda`. This module has no named export called `identity`.
```

Looking at the file, [it appears](https://github.com/flowtype/flow-typed/blob/master/definitions/npm/ramda_v0.21.x/flow_%3E%3Dv0.23.x/ramda_v0.21.x.js#L621) that all of the declarations are exported building up one class through mixins, which class is then the sole export. This, it seems, produces the frustrating result above. I can work around this by avoiding destructuring import:

```js
import Ramda from 'ramda'
const { map, add, identity } = Ramda

// map, add, identity now all typed
```

I'm new to flow, so it's unclear to me whether this is an issue with the declarations in this repository, a result of some misunderstanding on my part, or a shortcoming of flow itself.

cc @alexeygolev @jeffmo. Thanks for your contributions so far.

**Comment by ryyppy** [comment]
Actually, should `Ramda` be exported as a class with `mixins`?
I understand that the idea of those classes is to categorize the functions and mixins does a great job "spreading" those functions across one single export class... but to make named imports work, I guess we need to export a Object type?

**Comment by bwestergard** [comment]
@ryyppy Makes sense to me.

**Comment by alexeygolev** [comment]
@ryyppy @bwestergard I will look into it, unless anybody is up for a PR

**Comment by ryyppy** [comment]
I think @jeffmo said something about syntax support for named exports in `declare module` scope... maybe this will ease this issue?

**Comment by jeffmo** [comment]
Support for both named and default exports inside a `declare module` will ship in 0.28 (no later than early next week). In the meantime, `declare module` bodies can only export one or the other:

Named via `declare module.exports: {namedExport1: number, namedExport2: string};`
Default via `declare module.exports: MyDefaultExportTypeHere;`

**Comment by alexeygolev** [comment]
@jeffmo I think we should wait till 0.28 ships then

**Comment by sebinsua** [comment]
Looks like `flow@0.28` was released yesterday. Has anybody taken a look at getting this to work?

Is it possible to use `declare export var [...]` to output each of the functions within `RType` as named exports? (Aware that `class` was being used here to group related types.)

**Comment by mwalkerwells** [comment]
```
import Ramda from 'ramda';
const { curry, compose, reduce, keys, append } = Ramda;
```

@bwestergard / @jeffmo When I add line #2 (even if I remove the // @flow comment), flow instantly consumes 100% cpu after saving the file. Any idea why?

Using flow@0.27.0 & ramda_v0.21.x

**Comment by jeffmo** [comment]
@mwalkerwells: How long does it stay at 100% ? Also, how many flow worker processes do you see loaded in the background?

**Comment by mwalkerwells** [comment]
Really strange, but I can't get it to repro anymore. It was doing it all yesterday @ early today too. Atom command + click for modules wouldn't work in the meantime as well. It had 1/4 processes pegged @ 100% indefinitely iirc.

**Comment by alexeygolev** [comment]
@sebinsua: Working on it now. Hope to create a PR later today/tomorrow
Will also fix some bugs like empty generics introduced by flow@0.28

**Comment by alexeygolev** [comment]
Just a quick update. Still working on it. Should be able to submit a PR before Monday. Found a couple of wrong typings along the way:-P

**Comment by alexeygolev** [comment]
#188 
that took me a while:)

**Comment by alexeygolev** [comment]
This can be closed I guess @mwalkerwells @sebinsua @bwestergard 
I guess the aforementioned performance hiccup could be discussed in a separate issue?
