### ISSUE TITLE
How to define libs dependent on other libs type definition.

### ISSUE THREAD

**Issue by h-michael** [flowtype/flow-typed#1390]
I try to define [react-native-storage](https://github.com/sunnylqm/react-native-storage).
This package depends on 'AsyncStorage' from 'react-native'.
I want to use 'AsyncStorage' type def to define react-native-storage.
Plz tell me how to use other libs type def.

**Comment by sibelius** [comment]
like this https://github.com/flowtype/flow-typed/blob/master/definitions/npm/react-redux_v5.x.x/flow_v0.54.x-/react-redux_v5.x.x.js#L1

**Comment by sibelius** [comment]
```jsx
import type { Dispatch, Store } from "redux";

declare module "react-redux" {
}

```

or inside

```
declare module "react-redux" {
    import type { Dispatch, Store } from "redux";
}
```

**Comment by h-michael** [comment]
@sibelius Thanks!
