### ISSUE TITLE
redux.Reducer missing necessary | void

### ISSUE THREAD

**Issue by CharlesStover** [flowtype/flow-typed#1397]
The type Reducer in redux_v3.x.x.js should be:

```JS
declare type Reducer<S, A> = (state: S | void, action: A) => S;
```

A reducer may accept `undefined` as its first argument in order to return an initial state.

e.g.
```JS
const INIT_STATE: StateType = { a: 'b' };
const reducer: Reducer<StateType, Action> = (state: StateType = INIT_STATE, action: Action): StateType => {
  /* etc */
  return state;
};
```

If the user initiates the state with `reducer(undefined, '@@redux/INIT')` then `INIT_STATE` is returned.

**Comment by ZhangYiJiang** [comment]
What is the difference between this and 

```
declare type Reducer<S, A> = (state?: S, action: A) => S;
```

I've noticed the same issue with the libdef for `createStore` - 

```
declare export function createStore<S, A, D>(reducer: Reducer<S, A>, enhancer?: StoreEnhancer<S, A, D>): Store<S, A, D>;
declare export function createStore<S, A, D>(reducer: Reducer<S, A>, preloadedState: S, enhancer?: StoreEnhancer<S, A, D>): Store<S, A, D>;
```

If you have middlewares, then the libdef will inexplicably demand `preloadedState` to also be provided
