### ISSUE TITLE
definition of ms is incorrect

### ISSUE THREAD

**Issue by rmg** [flowtype/flow-typed#1419]
If anyone wants an easy PR, the `ms` libdef should be changed match the API as described in the docs:
> If a number is supplied to ms, a string with a unit is returned.
> If a string that contains the number is supplied, it returns it as a number (e.g.: it returns 100 for '100').
> If you pass a string with a number and a valid unit, the number of equivalent ms is returned.

Would be something like this:
```
  declare module.exports: {
    (val: string, options?: Options): number;
    (val: number, options?: Options): string;
  };
```

**Comment by doshisid** [comment]
This breaking my code builds. I'd be happy to submit a PR.

**Comment by GAntoine** [comment]
Closed since fixed.
