### ISSUE TITLE
Recompose doesn't actually type check and accepts everything

### ISSUE THREAD

**Issue by MarcCoquand** [flowtype/flow-typed#1421]
Hi, I'm trying to use Flow with recompose and it doesn't seem to type check at all. I installed recompose type checking with `flyd-install recompose@v0.24` and then copy pasted the example code and gave it some arbitrary arguments and it passes the type check anyway:

```
// @flow

import React from "react";
import { withStateHandlers
       , type HOC} from "recompose";

const Counter = ({ count, increment, decrement }) =>
  <div>
    Count: {count}
    <div>
      <button onClick={increment}>+</button>
      <button onClick={decrement}>-</button>
    </div>
  </div>;
// This should throw error?
export const App:HOC<string, string, number, string> = withStateHandlers(
  {
    count: 0
  },
  {
    increment: ({ count }) => () => ({ count: count + 1 }),
    decrement: ({ count }) => () => ({ count: count - 1 })
  }
)(Counter);
```

I am not entirely sure why this is but it seems the program passes regardless what type I make it.

**Comment by TrySound** [comment]
@MarcCoquand Which version of recompose do you have? If flow-typed version is different you will get installed stub definitions.

**Comment by TrySound** [comment]
You may copy that file by hands to fix that. The latest recompose releases did not change api

**Comment by MarcCoquand** [comment]
Thank you, I changed the file name `flow-typed/npm/recompose_v0.24.x.js` to `flow-typed/npm/recompose_v0.26.0.js` and it works now 👍 .
