### ISSUE TITLE
react-redux connect broken on flow > 0.54

### ISSUE THREAD

**Issue by bdrobinson** [flowtype/flow-typed#1432]
I recently upgraded flow to 0.57 and now my connect annotations are no longer working. Previously I was doing something along the lines of
```js
type Props = { name: string, age: number }
type OwnProps = { name: string }
const connector: Connector<OwnProps, Props> = connect(
    (state, ownProps) => ({
        // age: 3,
        name: ownProps.name,
    }),
    {},
)
```
which would correctly raise an error in flow 0.54 since the `age` prop is not set. However, in flow 0.55 and above this no longer raises a flow error, when it should. Has something changed with flow itself? Or does the react-redux libdef need updating? I'm pretty certain I have the latest libdefs installed.

**Comment by villesau** [comment]
There is some talk about react-redux libDefs being broken in the PR: https://github.com/flowtype/flow-typed/pull/1317

**Comment by bdrobinson** [comment]
Interesting. It's confusing because I observed that using the latest libdefs, the type checking definitely **does** work with flow 0.54, but on 0.55-0.58 (I've tested them all) the type checking fails to identify the error. So it feels like some Flow behaviour changed between 0.54 and 0.55 and the libdefs haven't been updated to account for it? Either that, or Flow 0.55 introduced a bug of some kind?

**Comment by villesau** [comment]
@bdrobinson If you suspect it's a bug in Flow, maybe you could report your findings in Flow issues too?

**Comment by bdrobinson** [comment]
Ok I did a `git bisect` and have found out that the commit that broke this is https://github.com/facebook/flow/commit/bd938abfb8970972d512847415d0f68563120480 . I've put some details on https://github.com/facebook/flow/issues/4939

**Comment by julienw** [comment]
See also https://github.com/flowtype/flow-typed/issues/1269

**Comment by AndrewSouthpaw** [comment]
I'm recommending we consolidate discussion to https://github.com/facebook/flow/issues/5343, since it's the most developed.
