### ISSUE TITLE
What is the preferred way for a module to provide its own libdef?

### ISSUE THREAD

**Issue by callumlocke** [flowtype/flow-typed#1451]
I'm writing a Node module. I'm using Flow in development. I'm building my code with Babel to compile and strip the type annotations, and then publishing the Babel output to npm.

I would like to expose my module's types so that dependent projects (if they are also using Flow) may automatically use types.

My question: should I PR a libdef into flow-typed after publishing my module? Or is it better to just include `.js.flow` file(s) with my published code?

(If it's the latter, is there any documentation on the best practices for doing this? Is there a way I can auto-generate the `.js.flow` files? Is there a good example of a small Node module that does this in the ideal way?)

**Comment by GAntoine** [comment]
Good question! I'm not too sure myself, but I've reached out to someone who would have a better idea.

**Comment by mruzekw** [comment]
The typed source code works as a .js.flow file. We just copy and rename them on build.

**Comment by jedwards1211** [comment]
(note that it's impossible to provide different `.js.flow` files for different versions of flow)

**Comment by callumlocke** [comment]
This is now in the FAQ:

https://github.com/flowtype/flow-typed/wiki/FAQs#what-is-the-preferred-way-for-a-module-to-provide-its-own-libdef
