### ISSUE TITLE
[mongoose] missing some types

### ISSUE THREAD

**Issue by sibelius** [flowtype/flow-typed#1469]
- [x] `connections` on Mongoose (https://github.com/Automattic/mongoose/blob/9c487909a21a128dae8ed434cf3bd4630129d64e/lib/index.js#L37)
- [x] `disconnect` on Mongoose (https://github.com/Automattic/mongoose/blob/9c487909a21a128dae8ed434cf3bd4630129d64e/lib/index.js#L280)
- [x] ObjectId.isValid method on ObjectId (https://github.com/Automattic/mongoose/blob/67c465aac5c864c3004d11d49934605037c8f520/test/browser/types.objectid.test_.js#L79)

**Comment by GAntoine** [comment]
Closing this with the merging of #1473
