### ISSUE TITLE
Flow error when using "jest.setTimeout" of "property `setTimeout`: Property not found in object type"

### ISSUE THREAD

**Issue by trevordmiller** [flowtype/flow-typed#1485]
There is a Flow error when using "jest.setTimeout" of "property `setTimeout`: Property not found in object type". For example:

```
jest.setTimeout(10000)
```

I've added a `// $FlowFixMe` comment above this line for now.

- I am using the latest version of jest (`npx jest --version` shows `v21.2.1`)
- I'm on the latest version of `flow-typed` (2.2.3)
- I'm on the latest version of the jest libdef (`flow-typed/npm/jest_v21.x.x.js`)
- I have tried wiping and re-installing `node_modules`

**Comment by trevordmiller** [comment]
Moved from https://github.com/facebook/jest/issues/4856#event-1330306604

**Comment by GAntoine** [comment]
@trevordmiller The issue's been fixed on v21 of jest, since it's the only one where this is available.
