### ISSUE TITLE
Ignore broken definition when running `flow-typed install`

### ISSUE THREAD

**Issue by vjpr** [flowtype/flow-typed#1486]
If there is a broken definition, how can you set it to be ignored when you run this command?

**Comment by GAntoine** [comment]
Broken in what sense? Could you give an example of a definition that is broken?

You can manually remove a definition, and run `flow-typed create-stub definition@1.2.0`. That will generate a stub which has no type-checking/defaults to `all`. Just don't run `update`, or the stub may be removed.

**Comment by vjpr** [comment]
I was having trouble with `next-routes`.

```
Library type error:
flow-typed/npm/next-routes_v1.x.x.js:6
  6:   import type { $Application, Middleware } from 'express';
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ identifier `.$module__express`. Required module not found

Library type error:
flow-typed/npm/next-routes_v1.x.x.js:7
  7:   import type { Link as NextLink, Router as NextRouter } from 'next';
                     ^^^^ Named import from module `next`. This module has no named export called `Link`.

Library type error:
flow-typed/npm/next-routes_v1.x.x.js:7
  7:   import type { Link as NextLink, Router as NextRouter } from 'next';
                                       ^^^^^^ Named import from module `next`. This module has no named export called `Router`.


Found 3 errors
```

**Comment by GAntoine** [comment]
Try adding `express` and `next` as `devDependencies`, and installing their flow-typed definitions. You should then get the correct types within `next`.
