### ISSUE TITLE
feat: install to infer version from package.json

### ISSUE THREAD

**Issue by AndersDJohnson** [flowtype/flow-typed#1505]
`flow-typed install module` should infer version from `package.json` instead of failing with an error saying it expects syntax `flow-typed install module@x.x.x`.

**Comment by GAntoine** [comment]
Agreed, in general `flow-typed` should infer as much as possible from the environment when the user isn't being specific with their commands.

**Comment by AndersDJohnson** [comment]
@GAntoine Thanks for implementing!

**Comment by GAntoine** [comment]
You can thank @villesau! Unlike me he actually took the time to implement it. 😅

**Comment by villesau** [comment]
It bothered me as well but originally I was sure there's a reason why it's _not_ inferred from package.json :D
