### ISSUE TITLE
bug on material-ui create-stub

### ISSUE THREAD

**Issue by sibelius** [flowtype/flow-typed#1511]
it generates only 

```jsx
declare module 'material-ui/RaisedButton/index' {
  declare module.exports: any;
}
```

it should also generates

```jsx
declare module 'material-ui/RaisedButton' {
  declare module.exports: any;
}
```

as we can import RaisedButton like this:

`import RaisedButton from 'material-ui/RaisedButton';`

**Comment by GAntoine** [comment]
Looking at the folder structure, you'll need to import it as `import RaisedButton from 'material-ui/RaisedButton/RaisedButton';`

**Comment by JackClown** [comment]
I am facing a similar problem, but what I use is `ant-design-pro`. I want to use it's component alone like `Exception`.

**Comment by GAntoine** [comment]
@JackClown There's currently no definition for `ant-design-pro`, so unless you're writing one this isn't an issue with flow-typed.

**Comment by JackClown** [comment]
@GAntoine I know it , so I used create-stub to generate, but it didn't generate correctly

**Comment by GAntoine** [comment]
Ah my bad! I see what you're saying, you're experiencing the same issue as above. I think there's a change to the cli pending release that improves stub generation.

**Comment by AndrewSouthpaw** [comment]
@GAntoine is that already in master?

**Comment by GAntoine** [comment]
Yeah, I just need to release a new patch version.

**Comment by JackClown** [comment]
@GAntoine Thanks
