### ISSUE TITLE
Cleanup old/merged branches

### ISSUE THREAD

**Issue by MichaelDeBoey** [flowtype/flow-typed#1530]
The following branches are all merged into `master`, so I guess they can be deleted?

- [`fix_037`](https://github.com/flowtype/flow-typed/tree/fix_037)
- [`prerel_versions`](https://github.com/flowtype/flow-typed/tree/prerel_versions)
- [`travis_node_version`](https://github.com/flowtype/flow-typed/tree/travis_node_version)

The following branches aren't merged into `master`, but are lacking behind for more than 604 commits (up to 1131) so they probably are already into the source in some way I think?
PR's for those branches aren't there anymore also.
- [`flow_version_validation`](https://github.com/flowtype/flow-typed/tree/flow_version_validation)
- [`libdef_prerel`](https://github.com/flowtype/flow-typed/tree/libdef_prerel)
- [`new-install-cmd`](https://github.com/flowtype/flow-typed/tree/new-install-cmd)
- [`testAll`](https://github.com/flowtype/flow-typed/tree/testAll)
- [`thejameskyle-patch-1`](https://github.com/flowtype/flow-typed/tree/thejameskyle-patch-1)

Just keeping the repo a bit cleaner I think 🙂

CC: @GAntoine

**Comment by GAntoine** [comment]
Done and done, thanks for bringing it up. I was meaning to do it sometime but got distracted. IMO there shouldn't be other branches then master, since everything is done via pull-request anyways, even the stuff I commit.

**Comment by MichaelDeBoey** [comment]
I can understand the need of a `develop` branch when completely redesigning the package (for the `3.0` release for instance), or for working on features on the repo itself and then PR them into `master`.
