### ISSUE TITLE
React-Redux connect doesn't work

### ISSUE THREAD

**Issue by maxsalven** [flowtype/flow-typed#1538]
The following works OK and correctly gives me a flow error about `data` being the wrong type:

```

type ComponentProps = {
  data: boolean,
};

const MyComponent = ({ data }: ComponentProps) => <div>{data}</div>;

const mapStateToProps = (state): * => ({
  data: "test",
});

const connector: Connector<{}, ComponentProps> = connect(mapStateToProps);

export default connector(MyComponent);
```

However, if I have a second argument to connect to use an action (or using `mapDispatchToProps`):

```
const connector: Connector<{}, ComponentProps> = connect(mapStateToProps, {
  updateUser,
});
```

then Flow no longer gives me an error, but it should. 

Flow 0.54 correctly gives an error in both situations, so something has broken since then.

**Comment by maxsalven** [comment]
Furthermore, the tests are clearly failing for multiple versions of flow:

`flow-typed run-tests react-redux`

`Found 17 warnings`

**Comment by AndrewSouthpaw** [comment]
I'm recommending we consolidate discussion to https://github.com/facebook/flow/issues/5343, since it's the most developed.

**Comment by AndrewSouthpaw** [comment]
Resolved by recent PR, closing.
