### ISSUE TITLE
Issue with Axios

### ISSUE THREAD

**Issue by maxsalven** [flowtype/flow-typed#1539]
It seems the libdef expects `response.data` to match the shape of submitted `data` in a post request? I think this is incorrect?

```
    axios({
      method: "post",
      url: "/user/12345",
      data: {
        firstName: "Fred",
        lastName: "Flintstone",
      },
    }).then(response => {
      console.log(response.data.wasSuccess);
    });
```

This raises a Flow error saying `wasSuccess` not found in object literal (whereas accessing `response.data.firstName` doesn't raise an error).

The user should be able to define the expected shape of `response.data`.

cc @timothystewart6 @haines

**Comment by haines** [comment]
I think the problem is [here](https://github.com/flowtype/flow-typed/blob/d679eeac2f803286b3dc0cee4afcb01c0f3cc9bd/definitions/npm/axios_v0.17.x/flow_v0.25.x-/axios_v0.17.x.js#L84), where the input config has the same type parameter as the output promise.

**Comment by cyorobert** [comment]
Same issue here. What I'd like to be able to do is something like this:

```javascript

type MyType = {
    foo : string,
    bar : number
}

type Error = {
     error : string
}

type Response = MyType & Error

function post() : Promise<Response> {
    return axios.post('/my-route')
                .then(response => response.data)
                .catch(() => ({error : "an error occurred"}))
}
```
