### ISSUE TITLE
Sequelize `condition` method takes 3 arguments, an alias for `where`

### ISSUE THREAD

**Issue by nss213** [flowtype/flow-typed#1581]
The `Sequelize.condition` method is an alias for `Sequelize.where` and takes 3 arguments, not 2.
In the current definitions, we see that there are 4 defs for where and only 2 for condition:
```
    static where(attr: Object, comparator: string, logic: string | Object): where,
    where(attr: Object, comparator: string, logic: string | Object): where,
    static where(attr: Object, logic: string | Object): where,
    where(attr: Object, logic: string | Object): where,
    static condition(attr: Object, logic: string | Object): where,
    condition(attr: Object, logic: string | Object): where,
```
Since the methods are actually object-equal, we should have 2 more lines for `condition`:
```
    static condition(attr: Object, comparator: string, logic: string | Object): where,
    condition(attr: Object, comparator: string, logic: string | Object): where,
```

**Comment by nss213** [comment]
I'm trying to create a PR for this but I think the pre-commit hooks end up reformatting the entire file.

**Comment by GAntoine** [comment]
> I'm trying to create a PR for this but I think the pre-commit hooks end up reformatting the entire file.

Don't worry about the entire file reformatting, open your PR and we'll take a look at it. 👍

**Comment by nss213** [comment]
Hm, I didn't have a problem this time, so there it is.
