### ISSUE TITLE
[Meetup] Reactive 2016 Conference

### ISSUE THREAD

**Issue by ryyppy** [flowtype/flow-typed#160]
As always, I create this thing as an issue, because really like to hangout with people contributing / using flow-typed & flow.

There will be the Reactive Conference in Bratislava, Slovakia on the 26th - 28th of October (https://reactiveconf.com/) 

Has anybody planned to go there? Or does someone know if there will be any flow guys going?
Actually always wanted to meet @splodingsocks / @marudor ... but I guess you will be busy or too far away? :-/

**Comment by splodingsocks** [comment]
@ryyppy I applied to speak, but didn't get in. So I probably won't be coming this year unless I get admitted to speak at the Elm pre-conference they're working to put together. I might be out there sometime this summer, though, for a related event!

**Comment by ryyppy** [comment]
@splodingsocks Damn, that's unfortunate...

Actually, if you ever happen to come to Europe and you are interested to travel around and to give some talks, make sure to check back with the ReactJS Vienna Meetup Group (@ReactVienna) ... we are always trying to get international speakers to talk here (also by sponsoring travel expenses and such). We even had an Elm introduction recently! :-)

**Comment by splodingsocks** [comment]
That sounds super cool!

**Comment by marudor** [comment]
Well - not to far away, but won't be there.
If you ever visit a chaos related (Chaos Computer Club) event in Germany I will be there though.

**Comment by ryyppy** [comment]
@marudor I realized that you are heavily invested in the chaos club :-) ... maybe I will check that out some time... I will leave this issue open if there is anyone interested in connecting at the conference.
