### ISSUE TITLE
`module.exports` failure.

### ISSUE THREAD

**Issue by mirek** [flowtype/flow-typed#161]
Is this declaration
https://github.com/flowtype/flow-typed/blob/master/definitions/npm/express_v4.x.x/flow_%3E%3Dv0.25.x/express_v4.x.x.js#L227 correct?

Eslint fails with `Parsing error: Unexpected token` on it. Not sure where to report it.

**Comment by jeffmo** [comment]
Support for `declare module.exports` was introduced in Flow `v0.25` (and note that this libdef is versioned at `>=0.25.x`).

Which version of Flow are you using?

**Comment by jeffmo** [comment]
Doh -- I just noticed you said *eslint* fails (not Flow).

This should probably be reported on ESLint I suppose

**Comment by ryyppy** [comment]
I also have this problem,.. usually while I work on my libdef, I just use the old syntax `declare var exports: MyType;` and when I am confident, I just replace with the newer syntax before running the tests...

Would be nice for `eslint` to support this tho...

**Comment by jeffmo** [comment]
Yea agree. Let's use this issue open to track an update to babel-eslint, then. My plate has been piling up lately (between TODOs on flow-typed and other Flow stuff) but I can probably hop on it sometime in the next 2 weeks.

If someone happens to beat me to it I wouldn't be upset, though :)

**Comment by ryyppy** [comment]
Cool, babel merged the new `declare module.exports` syntax 6 days ago! 🎉 
Let's see if we get this working soon :-)

https://github.com/babel/babylon/pull/72
