### ISSUE TITLE
Firebase: add definition of Cloud Firestore functions.

### ISSUE THREAD

**Issue by peat-psuwit** [flowtype/flow-typed#1657]
Firebase libdef in the repository currently doesn't have the definition of Cloud Firestore functions. Please consider adding one.

**Comment by wcandillon** [comment]
@AndrewSouthpaw This is a different library that is requested maybe:

```
import * as functions from "firebase-functions";
```

This one doesn't seem to be cover yet by `flow-typed`.

**Comment by wcandillon** [comment]
I added a simple definition that supports https triggers at https://github.com/flowtype/flow-typed/pull/2311
