### ISSUE TITLE
Can't find flow bin when it is installed as a transitive dependency

### ISSUE THREAD

**Issue by borela** [flowtype/flow-typed#1691]
Flow typed checks for flow bin in the `package.json` instead of the `node_modules` directory. In many projects we have a central package which installs all the tools we need to develop without having to reference each one of them.

**Comment by ADagen** [comment]
We have the same problem.

What about at least option for flow cli to explicitly instruct flow-typed?

E.g.

```bash
flow-typed install foo@1.2.3 --flow-bin 0.66.0
flow-typed install foo@1.2.3 --flow-bin 0.66.0 --ignoreDeps bar bazz
```

Potentialy it will covers some cases for https://github.com/flowtype/flow-typed/issues/1282

And i will be happy to make a PR for --flow-bin argument

**Comment by GAntoine** [comment]
You can use `--packageDir` to specify the relative path to the `package.json` where flow-bin is installed.
