### ISSUE TITLE
axios libdef has static interface property

### ISSUE THREAD

**Issue by TLadd** [flowtype/flow-typed#1694]
The axios libdef has a static interface property on CancelToken. https://github.com/flowtype/flow-typed/blob/master/definitions/npm/axios_v0.17.x/flow_v0.25.x-/axios_v0.17.x.js#L19

[flow v0.62 removed support for static interface properties](https://github.com/facebook/flow/blob/master/Changelog.md#0620). I imagine there are other libdefs that may have broken with this change as well, but this was the only dependency that caused issues in my projects.

**Comment by AndrewHamm** [comment]
@marudor Why was this issue closed? I'm still getting this issue with `flow-bin v0.68.0` and `flow-typed v2.4.0`

The following is the error I am seeing. You can see in the error on line 22 the static property which is still causing the issue is used

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ flow-typed/npm/axios_v0.15.x.js:22:5

Unexpected static modifier

     19│   }
     20│   declare interface CancelToken {
     21│     constructor(executor: (cancel: Canceler) => void): CancelToken;
     22│     static source(): CancelTokenSource;
     23│     promise: Promise<Cancel>;
     24│     reason?: Cancel;
     25│     throwIfRequested(): void;
```
