### ISSUE TITLE
Add react-apollo libdef

### ISSUE THREAD

**Issue by 0xcaff** [flowtype/flow-typed#1704]
It's written in typescript.

* [Github](https://github.com/apollographql/react-apollo)
* [NPM](https://www.npmjs.com/package/react-apollo)

**Comment by 0xcaff** [comment]
It's already done.

https://github.com/apollographql/react-apollo/blob/master/src/index.js.flow

**Comment by holman** [comment]
Might be worthwhile to point out here that Apollo is apparently [removing Flow from the repo](https://github.com/apollographql/react-apollo/pull/1858#issuecomment-376941239), so we should probably have a solution in flow-typed at some point.
