### ISSUE TITLE
[Contributing] Add editorconfig for consistency with text editors

### ISSUE THREAD

**Issue by bassettsj** [flowtype/flow-typed#176]
👋 I was wanting to propose adding a simple `.editorconfig` file so text editors with the plugin installed will automatically configure themselves to be consistent.

http://editorconfig.org/

**Comment by jeffmo** [comment]
Seems reasonable -- wanna send a PR? :)

**Comment by bassettsj** [comment]
# 192

**Comment by marudor** [comment]
Got merged, closing.
