### ISSUE TITLE
Precommit eslint script fails

### ISSUE THREAD

**Issue by saadq** [flowtype/flow-typed#1774]
[This commit](https://github.com/flowtype/flow-typed/commit/5ce3dc7614f4a589f2f070ebef72c4bbf2e23484) seems to have caused an issue with the precommit script. Eslint seems to fail with an output that looks like this:

```
λ flow-typed (master) ⟶ git add .

λ flow-typed (master +) ⟶ git commit -m "add common-tags"
husky > npm run -s precommit (node v8.3.0)

 ↓ Running tasks for package.json [skipped]
   → No staged files match package.json
 ❯ Running tasks for *.js
   ✖ eslint --fix
     git add
✖ eslint --fix found some errors. Please fix them and try committing again.

/Users/squadri/Projects/flow-typed/definitions/npm/common-tags_v1.4.x/flow_v0.25.x-/common-tags_v1.4.x.js
  17:18  error  Parsing error: Unexpected token

  15 | 
  16 |   // Built-in tagged template literals
> 17 |   declare export var html: TaggedTemplate;
     |                  ^
  18 |   declare export var source: TaggedTemplate;
  19 |   declare export var codeBlock: TaggedTemplate;
  20 |   declare export var safeHtml: TaggedTemplate;

✖ 1 problem (1 error, 0 warnings)




husky > pre-commit hook failed (add --no-verify to bypass)

λ flow-typed (master +) ⟶ 
```

I needed to do `git commit -m "add common-tags" --no-verify` in order to get the [pull request](https://github.com/flowtype/flow-typed/pull/1773) through.

**Comment by marudor** [comment]
I've created a issue in babel-eslint as for some reason it doesn't parse it...
https://github.com/babel/babel-eslint/issues/586

**Comment by marudor** [comment]
42ca8a9a4762c3f30678ebcde2d639ad57950ddc should fix this.

**Comment by saadq** [comment]
Can confirm this fixed the precommit issue. This seems to have caused an issue with Travis though, all new pull requests seem to cause tests to fail with a log like [this](https://gist.github.com/anonymous/f14dfa7a5c7d0189beb359fcb38fec44)

**Comment by marudor** [comment]
Yeah... working on it. Thanks for confirming though!
