### ISSUE TITLE
poor performance on lodash flow check

### ISSUE THREAD

**Issue by 1pete** [flowtype/flow-typed#1777]
I found that #1696 (better handling null/undefined) introduced bad performance to flow checking

tested with flow version 0.63, 0.64
tested script
```js
// @flow

import _ from 'lodash';

_.map([], () => 0);
```

comparison | file | time spent
----- | ---- | --------
before | [before pr #1696](https://github.com/flowtype/flow-typed/blob/613e51121adf9a346d64b15418c4ed567a020f34/definitions/npm/lodash_v4.x.x/flow_v0.55.x-/lodash_v4.x.x.js) |  ~2 seconds
after | [current master](https://github.com/flowtype/flow-typed/blob/de4764766be7e1fb8085d7d878b6592edf30f10e/definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js) | ~45 seconds

Could we do anything to improve this?

**Comment by Rauttis** [comment]
I've noticed the same thing, the latest typings for lodash makes flow unusably slow:
Before: `npm run flow  0.35s user 0.10s system 3% cpu 12.356 total`
After: `npm run flow  0.37s user 0.13s system 0% cpu 1:05.77 total`

**Comment by Zmetser** [comment]
Removing all the individual module declarations (introduced [here](https://github.com/flowtype/flow-typed/pull/1790)) solved this for me.

**Comment by maxmalov** [comment]
@Zmetser Individual module declarations were introduced after this issue was actually opened, so I'm not sure they are root cause of the issue

**Comment by Zmetser** [comment]
@maxmalov You're right, I'm sorry. You just added the fp exports and I removed all.

Still, removing all the individual exports speeds up flow. Here's a test repo where flow only reads the lodash libdef and does nothing else when you run `yarn flow` and there's almost a minute difference. https://github.com/Zmetser/lodash_flow_test

**Comment by 1pete** [comment]
I retest this issue with flow version 0.69, it takes ~2sec, seem this issue has been resolved.

Thanks.
