### ISSUE TITLE
Unexpected `any`-typing of imports

### ISSUE THREAD

**Issue by Ashoat** [flowtype/flow-typed#1795]
It seems that many possible `import` and `import type` statements in libdefs can fail silently and end up typing their imports as `any`. Some of these are widely using in existing libdefs.

For instance, `import * as React from 'react';` results in `React` and all of its properties being `any`-typed. Apparently you have to use `React$ComponentType` etc., but I can't find any docs that clarify this. The `import * as React from 'react';` pattern is used extensively in many existing libdefs.

`import type` statements will fail without `declare module` blocks, but outside of those blocks they will also result in `any` types.

`import` statement (not `import type`) are only allowed outside `declare module` blocks, and seem to be guaranteed to result in an `any` type.

**Comment by jedwards1211** [comment]
@GAntoine I think this issue should remain open.  The inability to import types from other libraries is a fundamental bug/shortcoming and merely documenting that fact doesn't really fix it.

**Comment by GAntoine** [comment]
I think we have another issue tracking the importing of libraries in the flow-typed environment. This does seems to be an issue with `flow` itself.

**Comment by AndrewSouthpaw** [comment]
Yep, agreed.
