### ISSUE TITLE
PR  #1796 (React relay variables) introduced a breaking change when validation query variables

### ISSUE THREAD

**Issue by mandx** [flowtype/flow-typed#1802]
I'm kind of new to Flow, and I'm here because the changes introduced in #1796 makes Flow to complain about my code.

I'm using an exact type to validate the `myVars` key inside my component's state, so I'm checking nothing else is passed as variables for that query, something like this:
```javascript
type FragmentQueryVariables = {|
  nodeIds: Array<string>,
|};
```

And here's the full example, using the new `Variable` and `Variables` declarations:
```javascript
type Variable = string | void | number | Variables | void | Array<Variables>;
type Variables = { [string]: Variable } & {$call?: void};

type FragmentQueryVariables = {|
  nodeIds: Array<string>,
|};

const ids: Array<string> = ['some', 'strings'];
const myVars: FragmentQueryVariables = {
  nodeIds: ids,
};
const queryVariables: Variables = myVars;
```
This gives [lots of errors](https://flow.org/try/#0FAFwngDgpgBAagQwE4EsECMA2sC8MDOIqAdgOYwA+MAbgPYoAmlMxArgLbpRLOKobZ8zOo2YBBJEgRgAPHzRYo+AHwBuUJFjyBSmHgDeMANqESpALoAueMgXYYAXxgAyGPoAkAYwSZMAfmsRBgd1DWgYADEpUnYoYhAARVZuMG1FIQMKYBgWWgYoAEkGfGsJKVlTFDJlABpgChDgYE9aYkIYRhKYMukZSuq9YwByfFpYoZqYEaIq0nwh83UWtpAYdlTkLqiEGLjE5KQN-nTB-Wzc-KKuzrrG5faARwOjuyVrNMFB9b58dSA), which I guess boils down to this:
```
    Type argument `T` is incompatible:
        6:   nodeIds: Array<string>,
                            ^ string. This type is incompatible with
        3: type Variables = { [string]: Variable } & {$call?: void};
                            ^ object type
```

I tried to "fix" the declaration by adding `Array<Variable>` but it keeps complaining about the same.

Any pointers? I always though that a stricter type like my exact definition above will fit into something like that `Variables` declaration... I'm typecasting to `any` for the time being, but I really prefer not doing that.

**Comment by steida** [comment]
@mandx Use `// $FlowFixMe` instead of any casting. It's better because Flow will tell you once it will be fixed.

**Comment by mandx** [comment]
@steida Yeah, that makes sense. It does take a bit of refactoring, because `// $FlowFixMe` statement will affect the next line in its entirety, but that's still better than blindsiding Flow entirely by using `any`. Thanks!

**Comment by steida** [comment]
Check https://github.com/este/este for another inspiration.
