### ISSUE TITLE
[Help Wanted] New Maintainer

### ISSUE THREAD

**Issue by GAntoine** [flowtype/flow-typed#1816]
Calling all flowbots! With the growing popularity of flow, `flow-typed` is looking for someone willing to help maintain the project. Preferably someone comfortable with flow who can fill the gaps in my knowledge. 😅

Comment below if you're interested!

**Comment by TrySound** [comment]
I can help a bit. Feel comfortable with lib defs and digging into flow ocaml source.

**Comment by mruzekw** [comment]
Are you looking for a replacement or additional help?

**Comment by marudor** [comment]
Additional Help.
Back when this repo started I mainly maintained it, sadly I do not have that much time anymore (Changed Job and stuff like that)
So more help is perfect.

**Comment by GAntoine** [comment]
Pinging a few people who might be interested:

@aaronjensen @MichaelDeBoey @jedwards1211 @stouf @AndrewSouthpaw @villesau

**Comment by villesau** [comment]
What kind of help is needed? reviewing PR's or helping to maintain the tool it self, something else?

**Comment by MichaelDeBoey** [comment]
I'm happy to help where I can. 🙂

Same questions as @villesau has: What kind of help is needed? Reviewing PR's or helping to maintain the tool itself or something else?

**Comment by GAntoine** [comment]
Mostly reviewing PRs, I'd like someone who's better at flow then myself (which shouldn't be too hard to  find). Also sanity check any changes made to the cli tool, and help out whichever way they want/can.

**Comment by stouf** [comment]
Being usually quite busy with work and other things, I may unfortunately not be the most committed person 😕 That being said, I would be glad to help anytime I can! 👍

**Comment by GAntoine** [comment]
@stouf I'll ping you whenever I need you, but I'll make sure its not too often! 😉

**Comment by stouf** [comment]
@GAntoine Hehe Thanks 🙂 Actually, you can ping me whenever you want/need. I'll do my best to be as responsive as possible; I just can't guarantee to be responsive 100% of the time, that's all 😉

**Comment by villesau** [comment]
After thinking this, I'd be also happy to help! :)

**Comment by marudor** [comment]
For easier communcation I quickly set up a slack:
https://flow-typed.marudor.de (auto invite)

**Comment by AndrewSouthpaw** [comment]
Yeah, I'd love to help out. Thanks for thinking of me, @GAntoine!

**Comment by aaronjensen** [comment]
I'd be happy to do some reviews and merging.

**Comment by jedwards1211** [comment]
Is there any automatic way for us to get notified of PRs for specific package type defs?  I'd like to review any PRs for `redis` and `sequelize` types at the very least

**Comment by GAntoine** [comment]
@jedwards1211 I was planning on (eventually) writing a bot, which could "assign ownership" of libdefs to certain people, and ping them for reviews/questions. It could hook into new PRs via webhooks, or as a github add-on.

**Comment by jedwards1211** [comment]
great idea! all a matter of finding the time right 😅

**Comment by GAntoine** [comment]
Story of all of our lives!

**Comment by sibelius** [comment]
add me as a contributor so I can merge some typedefs

**Comment by AndrewSouthpaw** [comment]
@GAntoine Where were you thinking to host the bot? I wonder if it could be built out as a lambda function...

**Comment by GAntoine** [comment]
Probably? I was planning on hosting on Heroku cause I'm cheap and lazy.

**Comment by GAntoine** [comment]
I'm please to announce we've added @AndrewSouthpaw and @villesau to the maintenance team! They'll be helping out with issues and PRs for new and existing definitions.

A big thanks to everyone for answering the call! 😄
