### ISSUE TITLE
idx typedef problem

### ISSUE THREAD

**Issue by sibelius** [flowtype/flow-typed#1834]
node_modules/idx/lib/idx.js.flow:10
 10: declare module.exports: $Facebookism$Idx;
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ .exports. Could not resolve name

is https://github.com/facebookincubator/idx/blob/master/packages/idx/src/idx.js.flow correct?

I'm using flow 65

**Comment by GAntoine** [comment]
This might help: https://stackoverflow.com/questions/47183924/facebookism-in-flow

**Comment by sibelius** [comment]
tks
