### ISSUE TITLE
The npm Package Hasn't Been Updated in a While

### ISSUE THREAD

**Issue by alexbooker** [flowtype/flow-typed#19]
The current module version is _2.0.0_ yet the latest published version is only _1.0.0_.

I found it a bit confusing when the commands described under the ["`flow-type` CLI" section](https://github.com/flowtype/flow-typed#flow-typed-cli) did not work.

Does it make sense to publish _2.0.0_ or _2.0.0-beta_ today?

If not, how about updating the readme in `master` to reflect _1.0.0_?

Thanks.

**Comment by jeffmo** [comment]
Yea, 2.0.0 is still underway and the CLI doesn't do much other than just validate the names and directory structure of the definitions. The real meat of the CLI will be the ability to find and download libdefs from the GitHub given a flowVersion and a set of packages/packageVersion dependencies.

I'm a little swamped this week, but I do have an initial version of this and should hopefully have a PR ready soon that defines this initial behavior and makes the new CLI actually useful. Once we've had a chance to discuss and land that, I think we'll be ready to publish `2.0.0-beta`.

Good idea about adding a note to the top of the README about the CLI being forthcoming...I can do that tomorrow (unless you want to send a PR? :D )

**Comment by alexbooker** [comment]
Awesome. I'm excited for the future of this project :smile: 

Pull request inbound...
