### ISSUE TITLE
Only run changed Tests on CI

### ISSUE THREAD

**Issue by marudor** [flowtype/flow-typed#190]
Probably related to https://github.com/flowtype/flow-typed/pull/143
https://travis-ci.org/flowtype/flow-typed/builds/144216941

@jeffmo

**Comment by marudor** [comment]
Talked to jeff in IRC, reverted the PR for now.
He will fix it later.

**Comment by ryyppy** [comment]
What's the state of Travis now? Can we close this?

**Comment by marudor** [comment]
Made the name more obvious.

**Comment by GAntoine** [comment]
Closing as this is currently the case.
