### ISSUE TITLE
Input reference of possibly incorrect type

### ISSUE THREAD

**Issue by luka-zitnik** [flowtype/flow-typed#1917]
Hi!

Here it says `inputRef` gives reference to a `FormControl`,
https://github.com/flowtype/flow-typed/blob/master/definitions/npm/react-bootstrap_v0.32.x/flow_v0.53.x-/react-bootstrap_v0.32.x.js#L178

But the react-bootstrap docs say it's a reference to an `<input>` element.
https://github.com/react-bootstrap/react-bootstrap/blob/v0.32.1-docs.0/src/FormControl.js#L29

**Comment by villesau** [comment]
here you go: https://github.com/flowtype/flow-typed/pull/1919

Nice to see traction towards react-bootstrap libdefs :)
