### ISSUE TITLE
Allow CONTRIBUTING.md file in sub folders

### ISSUE THREAD

**Issue by AndrewSouthpaw** [flowtype/flow-typed#1926]
Related to [this discussion](https://github.com/flowtype/flow-typed/commit/6475dcc6d17d87bf2bebb027320cdc404dfb39d3#comments) and [here](https://github.com/flowtype/flow-typed/issues/1915), we're going to add a `CONTRIBUTING.md` file. But right now tests fail when that happens, see #1925 and its [failing build](https://travis-ci.org/flowtype/flow-typed/jobs/350403286):

```
react-navigation_v1.x.x/CONTRIBUTING.md:
  • Unexpected file name. This directory can only contain test files or a libdef file named `react-navigation_v1.x.x.js`.
```

That needs to be fixed before #1925 can be merged.

**Comment by GAntoine** [comment]
There's an explicit check for files in a folder which don't respect test file name regex `/^test_.*\.js$/` at [`npmLibDefs:100`](https://github.com/flowtype/flow-typed/blob/master/cli/src/lib/npm/npmLibDefs.js#L100). I don't want us to go as far as to allow all files, but to whitelist certain files, such as `CONTRIBUTING.md` or `AUTHORS.md`.

**Comment by AndrewSouthpaw** [comment]
That's the plan. I'll probably get to it in a day or two. Thanks for pointing out the source!

**Comment by omeid** [comment]
Could it not be better to just allow `.md` and `.txt` files? Maybe some people don't like SCREAMING CASE FILE NAMES! or perhaps they want to add a license and they have a `license.txt`?

**Comment by AndrewSouthpaw** [comment]
Heh. So, eventually this was released to allow any file type in the subfolders, as long as they're not test files.

**Comment by omeid** [comment]
Yeah, looks like it. #1962
