### ISSUE TITLE
react-redux connect MapStateToProps state parameterization

### ISSUE THREAD

**Issue by Ashoat** [flowtype/flow-typed#1934]
#1731 improved a lot of things! But it's worth noting that the past definition of `MapStateToProps` was parameterized on state, which make it possible to "flow" your Redux state types into your component prop types, without the need to explicitly type the return of `MapStateToProps`.

Wondering if there was an explicit reason that parameterization was dropped. Is there a bug in Flow or some sort of insufficiency that's preventing it from being typed that way in the revamp?

**Comment by villesau** [comment]
@Ashoat  Thanks for reporting the issue! All I know is that it's been working previously, see this: https://github.com/facebook/flow/issues/5792#issuecomment-372346578 and [try flow link](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6hwJ7oCmoA3qAMKwawB2xdOAKkcQDSgCi0xqjOAApZY6AM6gAvqEgjUoAORZiAQwDGOBQG4UtXKABUoFRIBKqjTLmLl6zToAmxNdBXL8bUABFkY9Cpw1AAsAHgBBAD5QAF5jOgJHZ1d3QhJQAHlUZBwfPwDgkOpaBiYo2IASH0hIQppMEpxOMgdff0CggC5vVvzQgwjJCMSXN1JU0gBZFXQAZRwA4mZYYVExENMZwS70gCMAK2ccMtAACjF5nGJt-cOAShiojcFh5NJiAA9MfUgAVzoNZD0UBqegMDS1VBdIr1ASsEghfqcLxbDI3DScJ7XA4aCInRCgUCoaZzBZLFbiLpTWYXRbLETidabCKIW5dE4g4oCKE0e7RKLQ+iwtghSrIaohHh8ATktZFCIYpmgABk3kEQ0QGvGoBlMXIshoJMuZPpYi65ywyDoAHNJDoRmIJEVQB9LnQHGYLDgAHQChohGVRMj40DKN3ELAne5BgkE5Q4H5YOigEItABuETIOCCvi96BNXv1qENtJlkhCwDT6oJkkQNcQWuLurIKi6dB+qB24dtGpBdHOhOJNONq11ZxpXWLvMDwbjCaT0ZjheLw4poHOCy9KmDNe7iF7-eodDBlwcut7x5OROppLpq1uJyKtx0tSPh2Ip+AQyAA)

It's simplified version of the issue, and as you can see, 0.56 fails like it should, but more recent Flow versions does not catch the error.

**Comment by Ashoat** [comment]
Was there a reason you dropped the parameterization of state in `MapStateToProps`? Was that parameterization breaking anything? Naively I’m guessing adding back that type parameterization would enable the typechecker to know the shape of the state type.

**Comment by villesau** [comment]
@Ashoat I'm not sure if i follow. If you mean something like [this](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6hwJ7oCmoA3qAMKwawB2xdOAKkcQDSgCi0xqjOAApZY6AM6gAvqEgjUoAORZiAQwDGOBQG4UtXKABUoFRIBKqjTLmLl6zTsQATYmugrl+NqACyK9AGUcFRxiZlhhUTEAHlN-QQAuUAB5ACMAKxccTn9mAEFmLkTUjI0APlAAXlAACjEgkMSc-K4ASkry2MEdZ1d3UmIAD0x9SABXOg1kelA1egYNKOpURKXMBiZWEiiDUs5OovTM7LyCg5KcUurEUFBUP0Dg0PCRcUTfAPqniPEYuOPm0qIFqJaqzWjrHArGhtCrlVb0ASbYhRAAkABFkJBIFEeHwBN9oktdqBOqVSg5EIQSKACZVyLIaA8QmECYk6lhkHQAOaSHS9MQSJagQYhOiOMwWHAAOnhEKiBPKZGuoGUYuIWGqbSVNxuyhwoywdFAUUcyAAbqUyDgABbIMRS9Ave0M1BMr5OyRRYCmi06G6SRAByleN10sgqRJ0UaoFLq3mIRCzOh1W73T4sp102qfRqfGGK5V6g1G7U6l1ujORNmfKUqZUB+OJ+gp6h0eYhRx0pPt6p3D6PSviFrVJYtHSLOaZYid4DkoA), looks like it does not work.

The reason for dropping all the previous work was to be able to start from scratch. I couldn't grasp my head around the previous version and most of the tests were failing so I couldn't trust on them either.

**Comment by Ashoat** [comment]
@villesau: Sorry for the late reply here. My issue is that I am forced to type the state parameter passed to my `MapStateToProps` as an `Object`. If I try to change the type to the more specific shape of my Redux state, I get Flow errors. However, having the state typed as `Object` means Flow doesn't let me assume anything about its shape. So I'm forced either to make runtime assertions, or to circumvent the type system with an `any`-cast. This is how I am doing it:

```javascript
 mapState = (objectState: Object, ownProps: OP): {
   ...SP,
   cookie: ?string,
   urlPrefix: string,
   deviceToken: ?string,
 } => {
   const state: S = (objectState: any);
   return {
     ...mapStateToProps(state, ownProps),
     cookie: state.cookie,
     urlPrefix: state.urlPrefix,
     deviceToken: state.deviceToken,
   };
 };
```

I think the reason the previous libdef allowed us to use to a more specific shape to type our `MapStateToProps` function was that its definition of `MapStateToProps` was parameterized on the Redux state instead of just typing it as `Object`. I just tried re-adding the parameterization, and it seems to have solved my issue. I'll put up a PR.
