### ISSUE TITLE
Introduce an option to use a custom directory

### ISSUE THREAD

**Issue by nikgraf** [flowtype/flow-typed#194]
Right now I need to have `flow-typed` directory in the root directory of my project. Would you consider to add an option providing a custom directory?

I'm trying to move as many infrastructure/tooling into a directory to keep the root clean.
Totally understandable if you don't want to go down that route, but still curious 😄 

Related twitter conversation with @jeffmo https://twitter.com/nikgraf/status/753548419755540480

**Comment by thejameskyle** [comment]
Would this be an option that lives in `.flowconfig` or that you provide the CLI when installing?

**Comment by jeffmo** [comment]
Thanks for creating an issue. I've been rolling this around in my head the last day or so and here's where I'm at at the moment:

The biggest benefit of requiring exactly `<PROJECT_ROOT>/flow-typed/` is that we get away without needing any kind of additional config for flow-typed (#jsfatigue and all). So In the interest of keeping things simple in the beginning, I'm inclined to just stick to this naming-convention model for now.

Once we roll out the CLI and it gains some more significant adoption, if there becomes an increase in demand or a more general need for configurability like this then I think we should revisit.

**Comment by nikgraf** [comment]
@thejameskyle I don't have hard feelings on if it should be in `.flowconfig` or the `CLI`. As flow-typed seems become an integral part of flow anyway my gut-feeling tells me it should be in `.flowconfig`.

@jeffmo sounds reasonable, better to close the issue or do you want to keep it open?

**Comment by jeffmo** [comment]
Let's close it out for now
