### ISSUE TITLE
Importing React in definitions break React types

### ISSUE THREAD

**Issue by osener** [flowtype/flow-typed#1954]
I noticed some types such as `React.Node` resolving to `any` after starting to use flow-typed, and narrowed it down to this definition: https://github.com/flowtype/flow-typed/blob/b8dd3c3a2040ff2701e1de7b8502f3bcd1459002/definitions/npm/react-helmet_v5.x.x/flow_v0.53.x-/react-helmet_v5.x.x.js#L1

Since almost all definitions use `React$Node`, I wasn't sure if this is the expected behavior, and whether I should report this to Flow or update the type definitions in flow-typed to not import React.

I created a small repo to demonstrate the issue: https://github.com/osener/flow-typed-issue

**Comment by AndrewSouthpaw** [comment]
You're welcome to change it. It's a documented issue, and I've added some further notes in #1956 to clarify further. :)

**Comment by osener** [comment]
@AndrewSouthpaw FYI the FAQ says otherwise https://github.com/flowtype/flow-typed/wiki/FAQs#how-do-i-build-type-definitions-that-depend-on-other-definitions

What surprised me the most here wasn't the lack of safety within libdefs themselves though. The definition I linked above is also overwriting `React.Node` with `type Node = any` in my app code, and it took a while to figure out that an innocuous looking libdef could actually do this.

**Comment by AndrewSouthpaw** [comment]
> What surprised me the most here wasn't the lack of safety within libdefs themselves though.

Word, it's not good. Want to make a PR? 😉

**Comment by zerobias** [comment]
Just not do imports outside of the module declaration itself

This one will works perfectly
```js
declare module 'react-helmet' {
  import type { Node, Element } from 'react'
}```

Also please use global types as little as possible; it leads to incompatibility with actual component types

**Comment by AndrewSouthpaw** [comment]
Yes, it does, *and* we have no smart way to track dependencies between libdefs, which is why we generally discourage it.
