### ISSUE TITLE
UNCAUGHT ERROR, no such file /usr/local/lib/node_modules/definitions/.cli-metadata.json

### ISSUE THREAD

**Issue by mfirry** [flowtype/flow-typed#196]
When I run `flow-typed validate-defs` inside the root of the flow-typed repo I get 

```
UNCAUGHT ERROR: Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/definitions/.cli-metadata.json'
    at Error (native)
```

What am I doing wrong? `run-tests` and `update-cache` work just fine.

I'm using `flow-typed@2.0.0-beta.6`.

Thanks!

**Comment by ryyppy** [comment]
What did you try to do exactly? Did you try to work on a new libdef?
What does `which flow-typed` say? Regarding the path `/usr/local/lib` it looks like it checks your globally installed `flow-typed` instead of the local project repo

**Comment by mfirry** [comment]
Yes, I'm trying to write a new definitions. `flow-typed` is the globally installed one. How do I check my local definitions then?

**Comment by ryyppy** [comment]
You actually have to build your `flow-typed` from the checked out repo.

Check out how the `./run_def_tests.sh` does it's dirty work.
It basically builds the whole `flow-typed` cli and runs the tests.
You can basically go ahead and use `node dist/cli.js validate-defs` after a successful build.

Never use a globally installed `flow-typed` binary for development, it doesn't work that way :-)

**Comment by mfirry** [comment]
Thanks. I'll give a look at the build thing then. 

I imagine I'll end up writing some `./run_validate-defs.sh`  mimicking `./run_def_tests.sh` and see how that goes.
