### ISSUE TITLE
Cant use MapStateToProps definition

### ISSUE THREAD

**Issue by guigonc** [flowtype/flow-typed#1964]
Two months ago I updated the `react-redux` and its types definition, and changed the declarations in my containers as follows. But today after updating it it stopped working. Looking at the file the definition is there (it changed the parameters list but it is still ther) and I am receive `Named import from module react-redux. This module has no named export called MapStateToProps.` as an error, I can't see why it is not working. Am I misusing it or is it a break in the last update? If it is a misuse can anyone post how to do that the right way?

```
// @flow

import { connect, type MapStateToProps } from 'react-redux'
import Component from 'components'
import type { State } from 'types/state'

const mapStateToProps: MapStateToProps<State, {}, Props> = (state) => ({
  ...
})

type Props = {
  ...
}

export default  connect(mapStateToProps)(Component)
```

**Comment by villesau** [comment]
Hi @guigonc,

Some time ago react-redux `connect` libdefs were pretty much built from scratch, see https://github.com/flowtype/flow-typed/pull/1731. MapStateToProps is not exposed anymore as they are type checked when you pass your mapStateToProps function to your connect function. This means that as a consumer of libdefs you shouldn't need MapStateToProps anymore. You can check out the tests for further usage.

There are no migration guide (as I never were able to use previous definitions), but basically you change your code like this:

```
import { connect, type MapStateToProps } from 'react-redux'
import Component from 'components'
import type { State } from 'types/state'

type Props = {
  ...
}
const mapStateToProps = (state: State, props: Props) => ({
  ...
})

export default  connect(mapStateToProps)(Component)
```

**Comment by AndrewSouthpaw** [comment]
Looks like this question is answered, let us know if you have other questions. :)
