### ISSUE TITLE
[redux-actions_v2.x.x] createAction doesn't return Function

### ISSUE THREAD

**Issue by floriangosse** [flowtype/flow-typed#1990]
Since the last change a33adf993162d655d6822b2ec9c37da73edd7e3c flow is complaining about the wrong type because the return type of `createAction` isn't a function anymore. Instead the new type is an object which can't be used as a type. 

The following Flow output shows what the problem is:
```
Cannot use object type as a type because object type is a value. To get the type of a value use typeof.

      7│ import { add } from './actions';
      8│
      9│ type Props = {
     10│   add: add
     11│ }
     12│
     13│ class App extends React.Component<Props> {
```

I found a question on Stackoverflow which is about the same problem: https://stackoverflow.com/questions/39671873/flowtype-annotation-for-callback/39678032

**Comment by floriangosse** [comment]
I spent more time investigation the bug and it seems that there is no other solution. It tried to create an intersection type (`(() => {}) & { toString: () => T }` but this resulted in different errors.

It's a little bit strange that the bug occurred after the change and never before. Also that only a few actions have the wrong type. Here a short example:

```js
type Props = {
	add: add, // => Error
    remove: remove // => Good
}
```

**Comment by villesau** [comment]
@floriangosse I would say that as a rule of thumb always use `typeof`. I did some testing and while Flow accepts you to use function as type in some cases, the type is very loose and you can pass what ever to it. With `typeof` Flow is able to infer more.

**Comment by floriangosse** [comment]
Ok, thanks. I already started using `typeof` - first at the places where flow is complaining about it.

Thanks for your help. :) I will close this issue.
