### ISSUE TITLE
Discuss how to allow dependencies for libdefs

### ISSUE THREAD

**Issue by zaynv** [flowtype/flow-typed#2007]
So following up on #1857, it might be a good idea to talk about how `flow-typed` can allow dependencies between library definitions.

Would it be possible in some way to implement it the same way DefinitelyTyped does? They seem to have a `package.json` file included in the libdef like this: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-redux/package.json that specifies dependencies

Could `flow-typed` do something like this if we moved to installing libdefs via `npm` instead (which I think was discussed previously). Using a `@flow/@flowtype/@flowtyped/etc` namespace and doing something like `npm install -S @flowtyped/react-redux`.

Just wanted to open an issue here to see if anyone had any ideas

**Comment by villesau** [comment]
There actually is already quite extensive discussion about the topic: https://github.com/flowtype/flow-typed/issues/16

I have been planning to give it a stab, but due to lack of time I haven't got that far yet.

**Comment by GAntoine** [comment]
> I have been planning to give it a stab, but due to lack of time I haven't got that far yet.

I've been doing the same. I've gotten something working, but it's far from usable. Hopefully I'll have some time over easter.
