### ISSUE TITLE
CI tests for Node 6 are blowing up.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [flowtype/flow-typed#2025]
Examples:

- https://travis-ci.org/flowtype/flow-typed/jobs/361275747
- https://travis-ci.org/flowtype/flow-typed/jobs/361289455

`yargs` seems to be getting things angry, know what's going on?

**Comment by GAntoine** [comment]
Seems to have fixed itself. 🤷‍♀️

**Comment by AndrewSouthpaw** [comment]
😭
