### ISSUE TITLE
[react-navigation] Unexpected file name

### ISSUE THREAD

**Issue by vomchik** [flowtype/flow-typed#2033]
![vomchik vladimirs-macbook-pro projects lits mush mush-app-react-native-development 2018-04-04 09-43-31](https://user-images.githubusercontent.com/732085/38292685-48fcb438-37ed-11e8-975f-bcc32d4c7244.png)

**Comment by AndrewSouthpaw** [comment]
You'll need to upgrade to the latest version of `flow-typed`, `v2.4.0`.
