### ISSUE TITLE
Error during flow-typed install script running

### ISSUE THREAD

**Issue by sveta-d** [flowtype/flow-typed#2035]
there is such error after react-navigation adding to the dependencies/npm folder
UNCAUGHT ERROR: Error: react-navigation_v1.x.x\CONTRIBUTING.md: Unexpected file name. This directory can only contain test files or a libdef file named `react-navigation_v1.x.x.js`

**Comment by entropitor** [comment]
Updating flow-typed `npm install -g flow-typed` worked for me

**Comment by sveta-d** [comment]
work fine for my, thank you
