### ISSUE TITLE
soundness issue with object lookup

### ISSUE THREAD

**Issue by samuela** [flowtype/flow-typed#2050]
```js
function getString(key: string): string {
  const stuff = {a: 1, b: null, c: undefined};
  return stuff[key];
}
```
type checks just fine on v0.69.0 and master.

https://flow.org/try/#0GYVwdgxgLglg9mABAcwKZQMpQE4zMgCgGtUBPALkQGcc9kBKSm3fRAbwChFEIEbqoIYMEQBedgENKARgA0iAEaUwIADar5ESuAAmqYHlQ6AvgG4uibOhDYkNIcADaJUgF1zxjkA

**Comment by GAntoine** [comment]
Hi @samuela, is your question related to flow, or a definition in flow-typed? If it's to do with flow, you should instead open an issue on the [flow repo](https://github.com/facebook/flow).

**Comment by samuela** [comment]
@GAntoine oh sorry, i had the wrong tab open!

**Comment by samuela** [comment]
ok, opened https://github.com/facebook/flow/issues/6113.
