### ISSUE TITLE
import type is not working

### ISSUE THREAD

**Issue by sibelius** [flowtype/flow-typed#2061]
https://github.com/hally9k/flow-import-bug

It looks like flow `import type` stopped working on flow 66

anybody can take a look on this?

everything imported is marked as `any`

this is happening on flow 69 as well

**Comment by AndrewSouthpaw** [comment]
Discussed in the `CONTRIBUTING` guide and in #1857.

**Comment by sibelius** [comment]
This isn’t working in any user files, not only in flow-typed

**Comment by AndrewSouthpaw** [comment]
Unless I'm misunderstanding (I didn't look at the repo that carefully), the issue you are raising is addressed by something like this:

```js
declare module 'other-module' {
  import type { MyType } from 'some-module';
  declare export function takesMyType(val: MyType): number;
}
```

Can you clarify: if this isn't the case, what exactly is the issue?
