### ISSUE TITLE
React Navigation Directory Broken

### ISSUE THREAD

**Issue by TomPridham** [flowtype/flow-typed#2067]
The react navigation directory has: https://github.com/flowtype/flow-typed/blob/master/definitions/npm/react-navigation_v1.x.x/CONTRIBUTING.md which causes flow-typed to fail when running `flow-typed install` with the following error: `UNCAUGHT ERROR: Error: react-navigation_v1.x.x/CONTRIBUTING.md: Unexpected file name. This directory can only contain test files or a libdef file named 'react-navigation_v1.x.x.js'.
`

**Comment by saadq** [comment]
Duplicate of #2048 and #2033. The TLDR is basically that you need to upgrade `flow-typed` to v2.4 due to some internal changes.

**Comment by TomPridham** [comment]
Woops. should have searched closed ones as well. thanks
