### ISSUE TITLE
Express: middleware interface not allowing for functions that define an extended req or res params

### ISSUE THREAD

**Issue by bassettsj** [flowtype/flow-typed#207]
Having an issue with trying to add extended types of request or response objects to the middleware definitions. I am not sure the best way to fix this, so I thought I would open an issue. Below is an example of code that would fail with the current definition for express: 

```js
declare class PassportRequest extends Request {
   isAuthenticated(): boolean;
}
// Will throw error since it expects it to be of only type Request even though express 
// would  allow you to add a new extended request type that is added by the passport
// middleware.
app.use('/protected',  (req: PassportRequest, res, next) => {
  if (req.isAuthenticated()) {
    next();
  } else {
    res.redirect(401, '/login'); 
  }
});
```

**Comment by ryyppy** [comment]
@bassettsj I wonder if this is still an issue with flow@0.30 ?

**Comment by bassettsj** [comment]
It is no longer an issue, thanks.

**Comment by jtlapp** [comment]
Hey @bassettsj, how do I access the declared `Request` class of the Express type definitions from outside the type definitions file? I want to extend it just as you have above, but I can't figure out how to reference or import it.

**Comment by jtlapp** [comment]
That was freaky. `Request` and `Response` are globals despite being declared nested within a module. So I've successfully declare my subclass, but flow won't match my more specific method signatures to your HTTP method definitions on the router.

**Comment by jtlapp** [comment]
Looks like @mwalkerwells made this possible last night for #464. Thank you! I'm still not sure how to make flow happy with me specifying my new type in middleware signatures.
