### ISSUE TITLE
Error: react-navigation_v1.x.x/CONTRIBUTING.md: Unexpected file name

### ISSUE THREAD

**Issue by bwolfe** [flowtype/flow-typed#2087]
Running flow-typed install causes this error:
Error: react-navigation_v1.x.x/CONTRIBUTING.md: Unexpected file name. This directory can only contain test files or a libdef file named `react-navigation_v1.x.x.js`.

Introduced by PR #1925

**Comment by bwolfe** [comment]
Opened PR #2088

**Comment by AndrewSouthpaw** [comment]
Dupe of #2048 and #2033.
