### ISSUE TITLE
Should we update the testing steps in CONTRIBUTING.md?

### ISSUE THREAD

**Issue by PatriceVignola** [flowtype/flow-typed#2091]
When I was creating my first libdef (I will soon make my first PR to this repo!), I had a hard time testing it according to the [CONTRIBUTING.md guidelines](https://github.com/flowtype/flow-typed/blob/master/CONTRIBUTING.md). When I was running `./run_def_tests.sh <lib_name>`, I had hundreds of linting errors not related to my modules, and many tests were failing. Even if I ran the content of `run_def_tests.sh` line by line, almost every line was throwing an error. But then, I had a look at the readme and simply did `flow-typed validate-defs && flow-typed run-tests` and everything passed.

Am I doing something wrong with `run_def_tests.sh`, or is it outdated? Using the flow-typed CLI was painless as a beginner and since it's not an external dependency, maybe we should change `run_def_tests.sh` to run these commands instead. Cloning a project and seeing hundreds of lint errors and tests failing before even touching anything is a bit of a shock.

**Comment by GAntoine** [comment]
`flow-typed validate-defs && flow-typed run-tests` is how I run my tests as well. I feel using `run_def_tests.sh` is not ideal when testing locally. So yeah, it might make sense to change the docs. Would you be willing to make that change?

**Comment by PatriceVignola** [comment]
I just created a [pull request](https://github.com/flowtype/flow-typed/pull/2094).
