### ISSUE TITLE
jQuery data method does not return a jQuery object.

### ISSUE THREAD

**Issue by AaronAsAChimp** [flowtype/flow-typed#2160]
When using jQuery's `.data(key)` method the return type is incorrect. Flow claims that the type is `JQuery` but it should be `any`.

Judging by the definition it is a precedence issue. The [definition for the setter](https://github.com/flowtype/flow-typed/blob/492c298a82480fa313cc2b5b8a57268012307c0b/definitions/npm/jquery_v3.x.x/flow_v0.28.x-/jquery_v3.x.x.js#L1787) overrides the [definition for the getter](https://github.com/flowtype/flow-typed/blob/492c298a82480fa313cc2b5b8a57268012307c0b/definitions/npm/jquery_v3.x.x/flow_v0.28.x-/jquery_v3.x.x.js#L1801). Switching the order in my local copy fixes the issue.

I'm guessing it was overlooked because the return value is [never assigned in the test](https://github.com/flowtype/flow-typed/blob/492c298a82480fa313cc2b5b8a57268012307c0b/definitions/npm/jquery_v3.x.x/flow_v0.28.x-/test_jquery.js#L540).

**Comment by GAntoine** [comment]
Would switching the order cause the setter to incorrectly return type `any`, where it should be `jQuery`?

**Comment by AaronAsAChimp** [comment]
It does not because the void parameter is more specific.

```js
declare class JQuery {
  // *** Modified to change precidence and for brevity ***
  data(key: string, _: void): any;
  
  data(key: string, value: any): JQuery;

  data(obj: {
    [key: string]: any
  }): JQuery;

  data(_: void): any;
}

// For testing purposes
let $obj = new JQuery();

// Assign some things to test that the types are what they should be.
let $sameObj = $obj.data('stuff', {});
let data: string = $obj.data('stuff');

$sameObj.notAJQueryProp = 'cheese';
```

Produces:

```
25: $sameObj.notAJQueryProp = 'cheese';
             ^ Cannot assign `'cheese'` to `$sameObj.notAJQueryProp` because property `notAJQueryProp` is missing in `JQuery` [1].
References:
8:   data(key: string, value: any): JQuery;
                                    ^ [1]
```

**Comment by PikachuEXE** [comment]
#2286 opened
Tested locally
