### ISSUE TITLE
How to exclude a broken type definition?

### ISSUE THREAD

**Issue by vjpr** [flowtype/flow-typed#2177]
`pg_v7` if broken for me. How can I ignore it?

My current workaround is to run `rm flow-typed/npm/pg_v7.x.x.js || flow-typed create-stub pg` (https://github.com/flowtype/flow-typed/wiki/CLI-Commands-and-Flags#create-stub) after running `flow-typed install`.

Regardless of what version is specified, it creates a stub called `pg_vx.x.x.js`, when what I want it to do is overwrite `pg_v7.x.x.js`.

I opened an issue at flow too (https://github.com/facebook/flow/issues/6256) in case it can be done there in the `.flowconfig`.

**Comment by laugri** [comment]
Not exactly what you are looking for, but you can replace the conflicting types with `any` while waiting for an update (that's what I've done on my side).

**Comment by AndrewSouthpaw** [comment]
I think you'd want `flow-typed create-stub pg@^7` or whatever.

And yes, you can just `any` conflicting types until the libdef gets fixed.

**Comment by AndrewSouthpaw** [comment]
Closing for now, LMK if that doesn't address your question.
