### ISSUE TITLE
[ramda] Flatten messes up the checking

### ISSUE THREAD

**Issue by SamWyld** [flowtype/flow-typed#219]
Flatten messes up when used in composition, @alexeygolev promised to look into it soon (before the end of this week)

``` js
          compose(
            length,
            filter((todo: TodoItem) => todo.done),
            flatten,
            map((list: TodoList) => list.toDoItems)
          )(toDoListsList)
```

**Comment by alexeygolev** [comment]
@SamWyld yep, thanks

**Comment by thejameskyle** [comment]
What is broken about it?

**Comment by alexeygolev** [comment]
@thejameskyle flow reports an error. I think it's to do with the NestedArray

**Comment by thejameskyle** [comment]
```js
// @flow

import {compose, length, filter, flatten, map} from 'ramda';

type TodoItem = { done: boolean };
type TodoList = { toDoItems: Array<TodoItem> };

const toDoListsList: Array<TodoList> = [{
  toDoItems: [{
    done: false
  }, {
    done: true
  }]
}];

compose(
  length,
  filter((todo: TodoItem) => todo.done),
  flatten,
  map((list: TodoList) => list.toDoItems)
)(toDoListsList)
```

Is this what the full code would actually look like?

**Comment by SamWyld** [comment]
@thejameskyle Yeah

**Comment by alexeygolev** [comment]
@thejameskyle @jeffmo  I can't seem to figure it out...
```
declare type NestedArray<T> = Array<T | NestedArray<T>>
```
The problem with this is that `T` can be `Array<T>` so this
```
declare function flatten<T>(xs: NestedArray<T>): Array<T>;
```
results in `Array<Array<T>>` for things like

```
flatten([ [ 1, 2, 3, 4 ], [8]])
```

I really need help with the nested array thing. In haskell we would have to explicitly do flatten xs :: [Int]. I could obviously declare `flatten` like this:
```
declare function flatten(xs: NestedArray<*>): Array<*>;
```
But we effectively lose the safety:-/

**Comment by leonardfactory** [comment]
Changing the `NestedArray` declaration to this (swapping `T` with `NestedArray<T>`):

```js
declare type NestedArray<T> = Array<NestedArray<T> | T>;
```

Causes flow to throw this error:

```
array literal
Could not decide which case to select
union type
```

I though that switching union order would cause flow to try the first one, but it doesn't since there is ambiguity.

**Comment by alexeygolev** [comment]
See https://github.com/facebook/flow/issues/2562
