### ISSUE TITLE
Vague error description

### ISSUE THREAD

**Issue by avalanche1** [flowtype/flow-typed#2197]
```
const foo: Array<number> = [1,2].map((n) => {
	let  bar = n * 2
	bar**n
});
```
Obviously, this function returns `undefined`. But the flow error is really vague: `cannot assign 'map' to 'foo' because undefined[1] is incompatible with number[2] in array element`
It would be much more helpful if flow reported instead that `map` function needs to have an explicit return.

**Comment by AndrewSouthpaw** [comment]
This is for flow, not flow-typed. Wrong repo. 😄 

To help you parse this error, consider this: in the eyes of flow, `Array<number>` and `Array<undefined>` are very different things. You're typing `foo` as the former, but you're returning the latter. Hence, an error. Hope that helps!

**Comment by avalanche1** [comment]
whoops! thank you kindly :)
