### ISSUE TITLE
CLI can't find material-ui anymore

### ISSUE THREAD

**Issue by mastertinner** [flowtype/flow-typed#2215]
Since https://github.com/mui-org/material-ui moved to their own namespace on npm, this should be reflected here as well for the `flow-typed` CLI to pick it up automatically. 

I propose to move `definitions/npm/material-ui_v1.x.x` to `definitions/npm/@material-ui/core_v1.x.x`.

**Comment by GAntoine** [comment]
Yeah that makes sense, care to open a PR with the change?

**Comment by mastertinner** [comment]
Done: https://github.com/flowtype/flow-typed/pull/2218
