### ISSUE TITLE
Moment definition for moment().set({...})

### ISSUE THREAD

**Issue by ggravarr** [flowtype/flow-typed#222]
I think the definition for set on the moment object should be something more like `set(options: { [key:string]:void|number }): this;` it's currently `set(options: { unit: string, value: number }): this;`. [This](http://momentjs.com/docs/#/get-set/set/) is the relevant moment documentation section.  The void union is there in my example because of some code formatting in my project I didn't want to change that uses object shorthand;  I suppose it doesn't really match the documented function.

**Comment by ryyppy** [comment]
Would you mind sending a PR with the proposed changes?

**Comment by thejameskyle** [comment]
Fixed by #234
