### ISSUE TITLE
react-apollo causes flow-typed install to error

### ISSUE THREAD

**Issue by jackmellis** [flowtype/flow-typed#2226]
When I run `flow-typed install` it fails because the react-apollo definition contains a `CONTRIBUTING.md` file:

https://github.com/flowtype/flow-typed/blob/master/definitions/npm/react-apollo_v2.x.x/CONTRIBUTING.md

This is a pretty big blocker for me :disappointed:

**Comment by eryon** [comment]
@GAntoine @TLadd @budde377 
:+1: as of #2172

**Comment by eryon** [comment]
This is an issue with `react-navigation_v1.x.x` and `react-navigation_v2.x.x` as well.

@jackmellis there is a work-around to just remove the offending `CONTRIBUTING.md` files from your local clone of the repository. Check `~/.flow-typed/repo/definitions/npm/<libdef>`.

**Comment by TLadd** [comment]
Are y'all on the latest version of flow-typed? It appears some work was put in to allow this: 
https://github.com/flowtype/flow-typed/issues/1926
https://github.com/flowtype/flow-typed/pull/1962

**Comment by eryon** [comment]
@TLadd correct, thanks. I was on `flow-typed@^2.3.0` and updating the dependency has resolved the issue.

**Comment by GAntoine** [comment]
Thanks for taking this one @TLadd ! I'll be deprecating lower versions on npm once we're done breaking stuff.

**Comment by jackmellis** [comment]
I use flow-typed via npx i.e. `npx flow-typed install` which is still throwing even after clearing my npm cache. Any ideas?

**Comment by AndrewSouthpaw** [comment]
I think our tally of issues regarding this is in the double digits now. 😆
