### ISSUE TITLE
Windows issues

### ISSUE THREAD

**Issue by Phoenixmatrix** [flowtype/flow-typed#225]
Now that Flow[ supports Windows](https://flowtype.org/blog/2016/08/01/Windows-Support.html) (yay!), this probably should too.

2 issues I'm seeing so far: 

First, the obvious one [here](https://github.com/flowtype/flow-typed/blob/master/cli/src/commands/runTests.js#L20), probably just needs the binary path added.

I tried to fix that locally, but I encountered another bigger issues: the file names. Git for Windows really didn't seem to enjoy paths like `flow_>=v0.28.x`.

Don't know what a good solution would be.

**Comment by thejameskyle** [comment]
Looked at this with @gabelevi and it appears that `>` and `<` are reserved characters on windows paths.

@jeffmo We should find another way to communicate the version ranges

**Comment by jeffmo** [comment]
It's not possible to escape `<` and `>`?

**Comment by jeffmo** [comment]
What happens when you check out this repo on a windows machine? Does it just mangle the directory names?

**Comment by Phoenixmatrix** [comment]
It just ignores them and give an error that checkout failed (but everything else gets checked out fine), so `git status` then shows those directories as deleted.

**Comment by gabelevi** [comment]
Nope, no way to escape as far as I can tell. And yeah, I think git has the blob with the info for the file, it just cannot create the file on the filesystem.

**Comment by jeffmo** [comment]
whoa, that's pretty disappointing :(

So having a clear and structured naming format is pretty important for automated tooling here. Any objects to just switching `>=` and `<=` to `gte` and `lte`?

`flow_>=v0.30` -> `flow_gte0.30`
`flow_<=v0.30` -> `flow_lte0.30`
`flow_v0.30` -> `flow_0.30`
`flow_>=0.30_<=0.35` -> "flow_gte0.30_lte0.35"

**Comment by gabelevi** [comment]
What about

`flow_>=v0.30` -> `flow_v0.30-`
`flow_<=v0.30` -> `flow_-v0.30`
`flow_v0.30` -> `flow_v0.30`
`flow_>=v0.30_<=v0.35` -> `flow_v0.30-v0.35.0`

or

`flow_>=v0.30` -> `flow_v0.30...`
`flow_<=v0.30` -> `flow_...v0.30`
`flow_v0.30` -> `flow_v0.30`
`flow_>=v0.30_<=v0.35` -> `flow_v0.30...v0.35.0`

If all we need is to specify a potentially open ended range, then we can get away from the `>=` `<=` mindset

**Comment by jeffmo** [comment]
That is way better than my suggestion

**Comment by jeffmo** [comment]
(I like your first suggestion best)

**Comment by jeffmo** [comment]
I need to finish up the libdef generator I've been sitting on for the past week tomorrow, then I'll try to hop on this this week.

**Comment by Kovensky** [comment]
> `flow_v0.30...`

Ending a filename with a dot may summon zalgo on windows machines.

https://blogs.msdn.microsoft.com/oldnewthing/20071217-00/?p=24143

**Comment by ryyppy** [comment]
I could not find anything on the official Windows Developer page, so I am not sure, would it makes sense to use `flow_v0.30+` instead of `flow_v0.30...`? Would also fit better to the `flow_-v0.30` as well?

https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx

**Comment by Kovensky** [comment]
@ryyppy from that page: "Do not end a file or directory name with a space or a period. Although the underlying file system may support such names, the Windows shell and user interface does not."

**Comment by ryyppy** [comment]
Hmm, not sure what you are trying to say... I wanted to introduce a `+` instead of a `.`?
Ah and for the case `flow_>=v0.30_<=v0.35 -> flow_v0.30+-v0.35.0` ... heh

**Comment by Kovensky** [comment]
Oh, I misunderstood you saying you could not find anything about the dots.

`+` should work, but it might be nicer to use `_` or some other character that is URL-safe. Doesn't matter too much as long as it is doesn't match `/[\/<>:"\\|?*]|[. ]$`, I think.

**Comment by rickmed** [comment]
I have chosen flow over ts now that it supports windows. I would love to have flow-types as well!

**Comment by jeffmo** [comment]
Ok, so to add some closure here I think we should go with:

`flow_>=v0.30` -> `flow_v0.30-`
`flow_<=v0.30` -> `flow_-v0.30`
`flow_v0.30` -> `flow_v0.30`
`flow_>=v0.30_<=v0.35` -> `flow_v0.30-v0.35.0`

Since we already use `_` to separate "name" from "version", I think it's best to have something clearly different. `-` also makes sense for indicating a range.

So I think the work that's needed here goes as follows:

1. Codemod all the existing names in the repo to this new format
1. Update validation code (`validate-defs`/`run-tests` and friends)
1. Bump the beta-version in package.json
1. Bump the [compatibleCLIRange](https://github.com/flowtype/flow-typed/blob/master/definitions/.cli-metadata.json#L2) in the cli-metadata config (to force everyone to upgrade their CLI to understand the new format)

@samwgoldman would you mind taking a crack at this?

**Comment by samwgoldman** [comment]
Yup! Thanks for the details :)

**Comment by lagun4ik** [comment]
This problem can be circumvented by using Docker.

1. Install docker on windows
2. Copy this [this gist](https://gist.github.com/lagun4ik/615d919ec259d1b481f14d605ed14630) and add it to your PATH
3. Use flow-typed

**Comment by jeffmo** [comment]
@samwgoldman any updates here?

**Comment by samwgoldman** [comment]
Wrapping this up now.
