### ISSUE TITLE
Flow type ioredis error:  Cannot call redis.rpoplpush(...).then because property then is missing in undefined

### ISSUE THREAD

**Issue by tchiss** [flowtype/flow-typed#2253]
Hi,
I'm having a flow check error when I call `rpoplpush`method.
Here is the line:
`return redis.rpoplpush(config.mq.topics.queue, config.mq.topics.processing).then((data) => (typeof data === 'string' ? Promise.resolve(data) : Promise.resolve('')));`

Here is the error:
`Cannot call redis.rpoplpush(...).then because property then is missing in undefined [1].`

I checked the `flow-type` definition file of ioredis and I saw this:

`rpoplpush(args: any[], callback: ResCallbackT<any>): void;`
`rpoplpush(...args: any[]): Promise<any>;`

How can I specify to flow that I want to use the second method (`rpoplpush(...args: any[]): Promise<any>`) ?

Thanks

**Comment by AndrewSouthpaw** [comment]
I don't think it's possible really, since the first line is too broadly defined that it always matches for the type definition. You'd need to make them finer to disambiguate.

Just to check I'm thinking of it correctly, would something like `rpoplpush(foo, bar, baz).then` type correctly for you?

**Comment by tchiss** [comment]
I tried the `rpoplpush(foo, bar, baz).then` first and that doesn't work, that's why I proposed an update of the definitions by replacing the `...args: any[]` parameter to the real real parameters in some methods. [https://github.com/flowtype/flow-typed/pull/2265](url) . It seems that some tests failed so I'm going to fix it.
