### ISSUE TITLE
Eslint rule import/no-unresolved does not work with custom definitions

### ISSUE THREAD

**Issue by ezmiller** [flowtype/flow-typed#2254]
I've added a custom definitions directory to my project using the .flowconfig like so:

```
[libs]
./client/flow-typed-custom
```

After adding a file with a module and type declaration `custom-flow-types.js`, I was able to import and use the type that I'd defined with `import type { SomeType } from 'custom-flow-types'`.

However, the import statement caused the `import/no-unresolved` rule from [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import) to complain that it could not resolve the module.

Is there some way to get flow-typed to play well with this rule?

**Comment by AndrewSouthpaw** [comment]
Hmm, sorry to play this game, but this is not our problem. Talk to ESLint or Flow. Or, make your life easier and just create an alias that can be interpreted by ESLint (webpack, in the eslint config, etc.).

**Comment by adtm** [comment]
@ezmiller How did you solved this issue? With configuring ESLint or Webpack?

**Comment by ezmiller** [comment]
@adtm yes in the end I set up some aliases that point to the directory where we keep the flow type files. Then for eslint you can setup the import/resolver plugin to pick up those aliases, something like:

```
    'import/resolver': {
      webpack: {
        config: `/path/to/webpack/config`,
      }
    },
```
