### ISSUE TITLE
Forced local flow-bin requirement

### ISSUE THREAD

**Issue by neutraali** [flowtype/flow-typed#2302]
```
UNCAUGHT ERROR: Error: Failed to find a flow-bin dependency in package.json.
Please install flow-bin: `npm install --save-dev flow-bin`
```
Is there a reason `flow-bin` is required locally, e.g. in this case must be found @ `package.json`, even though it's recommended to install `flow-typed` globally? Neither the **Readme** or the **Changelog** nor trying to sift through the issue log mentions why this is so. I tried using `--packageDir` to point to the global modules directory but there's no `package.json` present for those.

It would be more convenient to allow `flow-typed` to use the globally installed `flow-bin` if found. The justification here is that I'm hesitant to start bloating every project with `flow-bin` just because `flow-typed` seems to force this. I found [an example](https://github.com/jamiebuilds/flow-typed-example) that used `--flowVersion 0.30` and that seemed to work beautifully so I'm wondering what happened between then and now (again, the **Changelog** is a bit brief).

I mean I could create a dummy project just for `flow-bin` and use `--packageDir` but ehhh... :smile_cat:

**Comment by LoganBarnett** [comment]
I'm kind of surprised `flow-typed` wants to be installed globally at all. Some of the benefits here are that your various repos can be upgraded independently, and one thing we can rule out with any problems you have is what version you might be running.

Granted, it's less convenient but it's also more "correct", which is the general tradeoff when working with Flow.

`flow-bin` should be a dev dependency and thus not have any impact on your runtime. While it might be harder to do in `flow-typed`, there are certainly changes between versions of `flow-bin` that can break backwards compatibility. Having a global upgrade occur is undesirable in that case, but then that locks out unrelated repos from also enjoying the upgrade.

Could we instead shift our stance to encourage local installs? In the case of `yarn` you're looking at one extra word to type: `yarn flow`. `npm` is less straightforward - instead it requires `"flow": "flow",` in your `scripts` of `package.json`. In both situations it runs from the executables in `./node_modules/.bin`.

**Comment by AndrewSouthpaw** [comment]
I may be misunderstanding the question here, but...

`flow-bin` is expected to be installed locally, since that's the standard practice anyway per the directions of Flow (I think). I use `yarn flow` as well, and I'm pretty sure that's the recommended way.

**Comment by steida** [comment]
I am using flow-typed locally for months, otherwise, it's super slow.

**Comment by AndrewSouthpaw** [comment]
Seems like this is settled, closing for now. Feel free to disagree. 😉
