### ISSUE TITLE
Where to put flow related libdefs?

### ISSUE THREAD

**Issue by ryyppy** [flowtype/flow-typed#232]
Okay, so I was working on a formatter for `flow --json` output and was writing types for the resulting JSON object, which I have the feeling would be useful for other stuff as well.

Now I am not sure where I should put em'. Would it make sense to create a `definitions/flow` directive, which could also later be used for internal flow libs for older `node` versions etc?

Or should I write the definitions as a `npm/something` which basically is not imported, but only pollutes the global scope? (which also doesn't make any sense)

**Comment by thejameskyle** [comment]
The reason for having all the modules under `definitions/npm` was so that we could have other directories like `core` or whatever.

This one is a bit different than "core" I think. It could almost belong under `npm/flow-bin`, but I don't know. @jeffmo what are your thoughts on this?

**Comment by jeffmo** [comment]
For this specific thing: We should have a library (like, an npm library) that returns well-typed output from Flow (via shelling-out or whatever). Perhaps `flow-bin` is a reasonable place to have such a library (in addition to the binary).

Obviously this doesn't solve the general problem, which may pop up again, but I do think having a lib that retrieves and returns Flow's output is the right way to go here.

**Comment by jeffmo** [comment]
See also: https://github.com/flowtype/flow-typed/issues/131

**Comment by ryyppy** [comment]
> We should have a library (like, an npm library) that returns well-typed output from Flow (via shelling-out or whatever)

I don't really see the challenge in this... it's basically either taking a string and transform it, or create a child_process and use it's stdout? That's what I do right now with my `flow-format` module...

Also I am not sure if we talk about the same types... this is approx. what I have:

```
type FlowMessageBase = {
  context: ?string,
  descr: string,
  end: number,
  endline: number,
  line: number,
  path: string,
  start: number,
}

type FlowMessageBlame = FlowMessageBase & {
  type: 'Blame',
  loc: {
    source: string,
    type: 'SourceFile' | 'LibFile',
    start: {
      column: number,
      line: number,
      offset: number,
    },
    end: {
      column: number,
      line: number,
      offset: number,
    },
  },
};

type FlowMessageComment = FlowMessageBase & { type: 'Comment' };

type FlowMessage = FlowMessageBlame | FlowMessageComment;

type FlowError = {
  kind: 'infer',
  level: 'error',
  message: Array<FlowMessage>, 
};

type FlowJsonOutput = {
  errors?: Array<FlowError>,
  flowVersion: string,
  passed: boolean,
};
```

I guess this would be just a subset of the things you already created in your RFC PR.

**Comment by jeffmo** [comment]
It's not so much of a challenge as annoying to do a lot. Reading from stdout is easy with child_process, but there's all sorts of retry/recover logic that would have to be repeated a lot. Moreover abstracting with a library gives us a nice way to version the output formats with the Flow version.

**Comment by jeffmo** [comment]
But yea, I generally think the RFC PR can include all of these types in its interface

**Comment by jeffmo** [comment]
BTW: I am not attached to being the one to finish that PR. If someone wants to take it over the finish line before I can get back to it, feel free to just ping the PR so I/others know.

Most of the AST types in there are done -- and that should be the most tedious bit of work -- so from there on out most of the rest should be just wrapping the various commands.

**Comment by ryyppy** [comment]
I put these definitions into the recently merged flow/npm-flow-lib package... issue closed.
