### ISSUE TITLE
[CLI] Support for downloading definitions for dependencies of a project

### ISSUE THREAD

**Issue by relekang** [flowtype/flow-typed#233]
It would be awesome if it were possible to run the following or something similar and get definitions for all dependencies that have theme available.

```bash
flow-typed install -f0.30 --dependencies
```

What do you think? I am more than happy to implement it if you think it is a good idea.

**Comment by migueloller** [comment]
Part of the reason why this would be great is that it would allow for keeping the `flow-typed` directory out of version control and then one could add a postinstall npm script to install libdefs.

**Comment by thejameskyle** [comment]
In the future `flow-typed install` will install all the libdefs you need for your dependencies. @jeffmo is already planning work on this
