### ISSUE TITLE
[Feature Request] Allow to install type defs from arbitarly commit of flow-typed

### ISSUE THREAD

**Issue by kogai** [flowtype/flow-typed#2341]
Hi there ✋ 

I have a question or some feature request which for resolving a problem of my team but might be useful for others too.

Currently, our team is using `flow-typed install` subcommand for to fetch type definitions from this repository, but we are gitignoring `flow-typed` directory. 
Because we prefer to install type definitions every time freshly and to ensure that do not modify type definitions manually on our own hands.
On the other words, we prefer to treat type definitions as well as node_modules.

By the way, if we are according to follow the policy above, sometimes our build will be broken unpredictable because of updating type definitions in the repository rapidly(Of course, it is a very sound character of the project).

Thus, I would love to say it will be great when flow-typed install subcommand has an option which can indicate arbitrary commit hash of this repository.
Or is there a way to achieve the request above ❓  

I am glad to hear the opinion or suggestion of the contributors, thanks.
And additional, if I can implement the feature like above, it would be the great honor for me.

**Comment by GAntoine** [comment]
Hi @kogai, and thanks for the feedback. We've actually started work on flow-typed version 3, which will publish type definitions to `npm/yarn`. You'll be able to lock packages to specific versions in your `package.json`.

For that reason, there's an informal moratorium on changes to flow-typed in the meantime.

**Comment by kogai** [comment]
Sounds great 👍 
I'm very looking forward to wait v3, thanks 🙏
