### ISSUE TITLE
Need a better react-dnd definition

### ISSUE THREAD

**Issue by cdchambers** [flowtype/flow-typed#235]
The [current react-dnd definition](https://github.com/flowtype/flow-typed/blob/master/definitions/npm/react-dnd_v2.x.x/flow_%3E%3Dv0.23.x/react-dnd_v2.x.x.js) is incomplete.

I'd like to take a crack at it by starting with [its TypeScript definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/react-dnd/react-dnd.d.ts).

Is there a good rule of thumb for doing this kind of mapping, i.e. X in TypeScript becomes Y in Flowtype?

I've also found 
http://sitr.us/2015/05/31/advanced-features-in-flow.html
and lots of these features used in the flowtype definition for React and Immutable.js. Is it Kosher to use these in flowtype definitions?

**Comment by thejameskyle** [comment]
There is currently no such guide for mapping, although the typescript and flow libdef syntaxes are very similar.

If you need any help you can ping me on [twitter](https://twitter.com/thejameskyle).
