### ISSUE TITLE
CLI favors more generic version ranges when installing libdefs

### ISSUE THREAD

**Issue by strax** [flowtype/flow-typed#236]
When running `flow-typed install enzyme@2.3.2 -f 0.30`, flow-typed installs libdefs for enzyme `2.x.x` as there are two different libdef versions, `2.x.x` and `2.3.x`. The generic `2.x.x` version is more outdated and is probably intended as a fallback unless there are more specific versions available.

Since there seems to be no way for defining upper bounds for version ranges currently, would it make most sense to just track major versions separately instead of making new libdefs for minor versions as well?

**Comment by jeffmo** [comment]
This was fixed over in https://github.com/flowtype/flow-typed/pull/326
