### ISSUE TITLE
Add additional deps in .flowconfig

### ISSUE THREAD

**Issue by pronebird** [flowtype/flow-typed#2362]
Hi,

I use `electron-mocha` to run `mocha` tests in Electron environment. I do not have a direct dependency on `mocha` since `electron-mocha` handles this.

Currently I have lots of errors in my tests because of this since `it` and `describe` are not available. 💩

Maybe having a way to specify additional deps via `.flowconfig` is a way to go. Not sure.

**Comment by AndrewSouthpaw** [comment]
Yeah, you could download the libdef manually, stick it in flow-typed, and then you're good to go.
