### ISSUE TITLE
Material-UI: some literal strings limit the use of setting the options using variables

### ISSUE THREAD

**Issue by PolGuixe** [flowtype/flow-typed#2395]
Some types are declared as literal strings: 
```js
 declare type Color = "inherit" | "primary" | "secondary" | "default";
```

When setting one of those options with a variable -see below-, flow will throw an error:

```jsx
type Props = {
//...
  buttonColor: string,
//...
}

class NewButton extends React.Component<Props>{

  render(){
     return (
       <div>
          //....
            <Button color={this.props.buttonColor}>Click!</Button>  // flow will throw and error here.
          //.....
        </div>
      )
  }

}
```

Any ideas to fix it?
Relaxing the types to accept any string is not the best solution.

**Comment by AndrewSouthpaw** [comment]
You could probably export that type and import it here.

**Comment by PolGuixe** [comment]
Right now I am trying to define types on my side that resemble the ones on `flow-typed/@material-ui/core`

How can I import types from `flow-typed/@material-ui/core`?

**Comment by AndrewSouthpaw** [comment]
If the type is exported from the libdef (and if it's not you can change it), then do

```js
import type { foo } from '@material-ui/core'
```

...probably.

**Comment by PolGuixe** [comment]
Ok. Cool I'll probably do another PR as some types are not exported. ;)

**Comment by AndrewSouthpaw** [comment]
Closing for now, feel free to reopen.
