### ISSUE TITLE
Need a `flow-typed install` CLI command

### ISSUE THREAD

**Issue by jeffmo** [flowtype/flow-typed#24]
We need some kind of baseline command that can be used to just explicitly find + install a library definition for a given "package@version" and flow version. Something like `flow-typed --flowVersion=0.22 underscore@1.0.0`.

It's pretty easy to add new commands to the CLI -- check out the other PRs (https://github.com/flowtype/flow-typed/pull/15, https://github.com/flowtype/flow-typed/pull/23) that do this as an example.

For matching a package@version to a libdef in the repository: I've actually already written `getMatchingLibdefs()` inside `npm/src/commands/libdefsForPkg.js` over in https://github.com/flowtype/flow-typed/pull/23 . Given that that PR might warrant more discussion before it's ready to land, it seems fine to just steal that code and put it somewhere general for re-use (which I would then be happy to rebase #23 on top of if this lands first).

Other than that, this command would just create a directory called `flow-typed` and download/install the appropriate library definitions into it.

**Comment by splodingsocks** [comment]
Awesome! 

Were we also talking about adding built-in support for the flow-typed lib folder to flow? Or should the flow-typed CLI just make sure that flow-typed is in the [lib] section of the .flowconfig?

**Comment by jeffmo** [comment]
Ah yea -- I'll take point on adding it to the default [libs] list in Flow.

It might be too late to get it in the v0.23 cut off, but 0.24 shouldn't come too long after.

**Comment by splodingsocks** [comment]
Think I could take a stab at that one, too? I'd love to get some OCaml under my belt.

**Comment by jeffmo** [comment]
Definitely have at it!

**Comment by ryyppy** [comment]
Interesting... are you planning to integrate some `flow-typed` options into `flow` itself?

**Comment by splodingsocks** [comment]
@ryyppy Just that by default it'll load libs from the flow-typed folder if it exists.

**Comment by jeffmo** [comment]
Checkpoint! @splodingsocks's Flow PR for the aforementioned integration landed: https://github.com/facebook/flow/pull/1640

**Comment by ryyppy** [comment]
I give it a shot, if you don't mind?

**Comment by jeffmo** [comment]
Landed in: https://github.com/flowtype/flow-typed/pull/78
