### ISSUE TITLE
Deprecated $call syntax in express_v4.16.x.js using flow 0.75.0

### ISSUE THREAD

**Issue by doberkofler** [flowtype/flow-typed#2407]
After upgrading to flow 0.75.0 the express definition file reports the following error but I cannot find any documentation on what changed:
```
Warning ----------------------------------------------------------------------- interfaces.flow/express_v4.16.x.js:200:3

Deprecated $call syntax. Use callable property syntax instead. (`deprecated-call-syntax`)

   200|   $call: (
          ^^^^^
```

**Comment by sgrowe** [comment]
FYI for anyone who has this issue, whilst waiting for these definitions to update you can set this option in your `.flowconfig` to disable the error:

```
[lints]
deprecated-call-syntax=off
```

**Comment by luislhl** [comment]
I'm on Flow 0.52.0, and getting many errors like this after the fix in https://github.com/flowtype/flow-typed/pull/2408:

```
Library type error:
flow-typed/npm/express_v4.16.x.js:215
     v------------------------------------------------------------------------------------
215: declare class express$Application extends express$Router mixins events$EventEmitter {
216:   constructor(): void;
217:   locals: { [name: string]: mixed };
...:
253: }
     ^ property `disable`. Property not found in
Object
```

Any ideas?

Upgrading to flow 0.75.0 is not a good option at the moment, because it causes me many more errors with GraphQL types, and I would have to also upgrade GraphQL to a newer version.

**Comment by OM2** [comment]
@luislhl You probably did this and I am not sure this is helpful, I had to just `//$FlowIgnore` above the that class declaration for the time being. I am on the same versions as you.
