### ISSUE TITLE
Ramda: prop doesn't work on undefined

### ISSUE THREAD

**Issue by karlhorky** [flowtype/flow-typed#2437]
Hi there, thanks for this awesome project! Helps so much to have working type definitions for libraries when working with Flow.

In the Ramda documentation, they mention that the `prop` method should return undefined if the parameter passed in is undefined:

```js
R.prop('x', {}); //=> undefined
```

The signature that they mention with Ramda 0.25.0 is:

```
s → {s: a} → a | Undefined
```

I tried using the `?` maybe operator with the `$ElementType<O, T>` return value, but Flow complains about "an indexer property is missing in undefined" ([Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAJgUwMYwIYBOmYUArgHbYAuAlnOWAA4FyMA8AKgFxgDOVBGuQDmAGjAB5HgH4JAIwBWOKgD4AFAGtMATx4dxcHhICUMgCQBRGJgC2mclQ7bGmNhPEcVAblTZ6-MBs8bTlMeQUwAF4wCiwoIUx0H2ZWNQByPDTxIJCwxWMvIA))

```js
declare function prop<T: string, O: ?Object>(key: T, o: O): ?$ElementType<O, T>;
declare function prop<T: string, O: ?Object>(
  key: T,
  ...rest: Array<void>
): (o: O) => ?$ElementType<O, T>;
declare function prop<T: string, O: ?Object>(
  __: $npm$ramda$Placeholder,
  o: O
): (key: T) => ?$ElementType<O, T>;
```

I also tried adding further overloads to the `prop` function with use of `void` and `null`, but this ran into the wrong signature being selected and a function being returned instead of `?T` (as in #1965). ([Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAJgUwMYwIYBOmYUArgHbYAuAlnOWAA4FyMA8AKgFxgDOVBGuQDmAGjAB5HhIBGAKxxUAfAAoA1pgCePDuLjSAlDwAkAURiYAtpnJUOmxpjYTxHJQG4MOfERIVqdAzMrJw8-IIi4hKqqGBgGtpgurFgAHTpRPw8AIIEBHiabABucDToSqhGYCr6kgZgALxKYGYW1rb2js6uHl64hMRklLT0TCzs3HwCQsKqCTp6POSkMDBgAD5gJWVV2+ieWP2+QwGjwRNh0yIxcfNJoinpqZlUOXkFxaXllTw1SytrTZ7epNLZfTzYej8MCWAoyTCyOSNMAAETwVEwqXIiBU9WaAEYAKwAZgADPjyQA2AAsAE4AOwAJgAHGAAPxgChYKBCTDoMA8ADeeB4AHIZKKAL6eFTnFSivCi8SwzTwxFVNnhGYGdxAA))

```js
declare function prop<T: string>(key: T, o: null | void): void;
declare function prop<T: string>(
  key: T,
  ...rest: Array<void>
): (o: null | void) => void;
declare function prop<T: string>(
  __: $npm$ramda$Placeholder,
  o: null | void
): (key: T) => void;
```

What would be the correct approach here? How can `undefined` values also be supported with `prop`?

**Comment by AndrewSouthpaw** [comment]
Ah the joys of trying to do static typing with dynamic functional programming. 😬

I haven't found an obvious way to support this request given the utility types that Flow provides. It sure would be grand, and also I haven't seen a way.

I would just ignore the error with a `// $FlowFixMe` or similar, whatever you use to track errors that are known unresolvable issues.

ccing @LoganBarnett, but closing for now. Feel free to reopen if you object.

**Comment by karlhorky** [comment]
Ok, thanks for the feedback. Would be interested to hear if the situation changes.
