### ISSUE TITLE
Definitions top level versions

### ISSUE THREAD

**Issue by ryyppy** [flowtype/flow-typed#262]
Heya!

I just realized, that `jest` now has a `definitions/npm/jest_v12.0.x` and a `definitions/npm/jest_v14.0.x`  ... So we will eventually have an explosion of major version directories for each library we maintain.

Do we actually want that?

**Comment by jeffmo** [comment]
I don't currently see any issues with it, do you?

**Comment by ryyppy** [comment]
I don't know... I see github capping the directory listing at 1000 elements and with that system we will reach that limit quite fast I guess? I like looking up definitions on github ¯\_(ツ)_/¯

**Comment by jeffmo** [comment]
I suspect we'll hit >1000 packages relatively quickly either way, so not sure this will help too much.

I wonder if it would be possible to build a gh-pages web utility for browsing/searching through them? I know gh-pages is limited to client-side stuff only, so not sure how easy it would be to get access to the repo -- but I bet we could get creative... Maybe update the static list in Travis on each commit to master or something...

**Comment by ryyppy** [comment]
Yeah well, we will need some automatic list generation on the long run anyway... this can wait though...
