### ISSUE TITLE
Update deps / scan for outdated & more

### ISSUE THREAD

**Issue by emirotin** [flowtype/flow-typed#285]
It would be nice to add a couple of improvements:
1. check if any of the defs installed in the project got an update in the registry (and fetch that update)
2. check if there are defs in the registry for any of the modules in my package.json

Also there's a bit of confusion because the CLI combines commands for 2 different categories of users: consumers and the registry maintainers / defs authors.
IMO the 2nd set of commands can be separated into a different executable in the repo.

**Comment by thejameskyle** [comment]
cc @palange

**Comment by GAntoine** [comment]
Closing since we now have `install` and `update` commands.
