### ISSUE TITLE
typing jest mocks in tests

### ISSUE THREAD

**Issue by JosePedroDiasSky** [flowtype/flow-typed#291]
Extract of a jest test:

``` js
jest.mock('../../js/comm/ajax');
import ajax from '../../js/comm/ajax';
describe('ConfigurationProvider', () => {
  it('calling the fetchConfig() should return a promise', () => {
    const expectedCfg = {x:'y'};
    ajax.mockReturnValueOnce(
      Promise.resolve({body:expectedCfg})
    );
    ...
  });
});
```

The original ajax module exported a function so jest will intercept and return a JestMockFn instead. Flow says `property mockReturnValueOnce not found in statics of function`.
How do I let flow know of this? Should I cast the ajax symbol to the JestMockFn type? And how?

Thanks :)

**Comment by ryyppy** [comment]
Not sure if this will help you for your concrete use-case right here, but here is an idea how I did something:

```js
const ajax = jest.fn();

jest.setMock('../../js/comm/ajax', ajax);

describe('ConfigurationProvider', () => {
  it('calling the fetchConfig() should return a promise', () => {
    const expectedCfg = {x:'y'};
    ajax.mockReturnValueOnce(
      Promise.resolve({body:expectedCfg})
    );
    ...
  });
});
```

If you need to use the interface of the mocked function as well, you need to create a new type for `ajax` which will mix the jest mock fn with your actual implementation fn type

**Comment by ryyppy** [comment]
The easy (and probably a less safe) way out would be:

```
jest.mock('../../js/comm/ajax');

// ajax is now unsafe ... deal with it 😎
const ajax: any = require('../../js/comm/ajax');
```

**Comment by aaronjensen** [comment]
Perhaps adding a utility function would be handy:

```js
const mock = (mockObject: any): MockObject => mockObject

mock(ajax).mockReturnValueOnce(...)
```

You could even potentially make that function polymorphic and strongly type things like `mockReturnValueOnce`.

**Comment by jeffmo** [comment]
Yea, the wrapper-function is what i did in the flow-typed CLI:

https://github.com/flowtype/flow-typed/blob/master/cli/src/lib/__tests__/libDefs-test.js#L30-L32

I used `any` there, but it would probably be better to have the `jest` libdef export the interface of a mock and just have it cast to that:

```js
import type {JestMockT} from "jest";
function _mock(mockFn) {
  return ((mockFn: any): JestMockT);
}
```

**Comment by JosePedroDiasSky** [comment]
Thank your for the responses. I would prefer to overload the Function prototype with the jest fn. How evil would that be?

The main reason I dislike @jeffmo 's solution is that is unpractical to have to call _mock() over all auto-stubbed jest functions.

**Comment by sgrishchenko** [comment]
I think I found the most suitable solution (or rather, my colleague suggested it to me):
```js
let mockAjax: JestMockFn<[string], Promise<{body: {}}>>;
jest.mock('../../js/comm/ajax', () => {
  mockAjax = jest.fn()
  return {
    default: mockAjax,
  }
});
describe('ConfigurationProvider', () => {
  it('calling the fetchConfig() should return a promise', () => {
    const expectedCfg = {x:'y'};
    ajax.mockReturnValueOnce(
      Promise.resolve({body:expectedCfg})
    );
    ...
  });
});
```

**Comment by meandmax** [comment]
Hello everyone,

@sgrishchenko how are you able to have **mockAjax** defined when using jest.mock. The block will be hoisted and mockAjax will be undefined, right? We tried with `doMock` as well but that did not work either. Me and my team still looking for a solution to have correctly typed mocks and not need to use `(x: any).mockImplementation()`? Anyone? :)

Cheers Max

**Comment by meandmax** [comment]
It works with different order:

```
import ajax from '../../js/comm/ajax';
jest.mock('../../js/comm/ajax', () => {
  return {
    default: jest.fn(),
  }
});
const mockAjax: JestMockFn<[string], Promise<{body: {}}>> = ajax;
describe('ConfigurationProvider', () => {
  it('calling the fetchConfig() should return a promise', () => {
    const expectedCfg = {x:'y'};
    mockAjax.mockReturnValueOnce(
      Promise.resolve({body:expectedCfg})
    );
    ...
  });
});
```
