### ISSUE TITLE
Strongly-Typed Definitions

### ISSUE THREAD

**Issue by ccorcos** [flowtype/flow-typed#301]
It would be great if these type definitions were strongly typed -- that is, no `any` or `Object` types. 

I'm checking out the typedef for redux here: https://github.com/flowtype/flow-typed/blob/master/definitions/npm/redux_v3.x.x/flow_%3E%3Dv0.23.x/redux_v3.x.x.js#L2

I think that type definition does way more harm than good. Flow is going to miss countless bugs ruining peoples confidence in the tool itself. I think we should delete this definition.

This typedef is shaping up well: https://github.com/reactjs/redux/pull/1887

**Comment by thejameskyle** [comment]
Yup we should be avoiding those. See other issues about linting PRs: https://github.com/flowtype/flow-typed/issues/49

Why don't you submit a PR that improves the definition rather than deleting it outright?

**Comment by ccorcos** [comment]
I figured it was preferred for the libraries themselves to maintain their own type definitions -- hence the reference to the PR
