### ISSUE TITLE
Flow is slow, and then produces unexpected results

### ISSUE THREAD

**Issue by joewalker** [flowtype/flow-typed#310]
Running flow recently started taking 10 / 20 minutes to produce results (with one CPU core maxed out all the way), and then the results it produces seem incorrect.

Some Flow errors that I would have been expected to have been caught are not. As an example below, I have been expecting an error in a IndexedDB call (this is commented out for the time being) but the expected error doesn't happen, so an error is reported.

```
time npm run flow

> project@1.0.0 flow /path/to/project
> flow; test $? -eq 0 -o $? -eq 2

Launching Flow server for /path/to/project
Spawned flow server (pid=35424)
Logs will go to /private/tmp/flow/zSpathzStozSproject.log

...

storage.js:99
 99:         // $FlowIssue: The flow definition of db.transaction seems wrong
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Error suppressing comment. Unused suppression

Found 8 errors
npm run flow  0.48s user 0.31s system 0% cpu 9:50.41 total
```

Also during this run:

flow_typed/test.js:

    declare type Test = string;

someCode.js:

    import type { Test } from 'test';
    const t: Test = 6;

**Comment by joewalker** [comment]
When run with --debug, I get this:
```
Worker interrupted with signal: sigill
Failure("Subprocess(55914): fail 2")
```

**Comment by joewalker** [comment]
So I've narrowed down something that causes this. The problem goes away if I remove the call to `data.update()` (see the removeInfo function), or if I add a type declaration to the `let data =...` line.

```
// @flow
import * as Immutable from 'immutable';
import fs from 'fs-extra-promise';

let data = Immutable.Map();
// The problem with the data.update call below is fixed by adding this
/* Immutable.Map<string, Object> */

export function removeInfo(id: string): Promise<void> {
  data = data.removeIn([ 'thing', id ]);
  // Something about this causes the problem
  data = data.update('email', email => {
    return email.map(ids => ids.filter(thisId => thisId !== id));
  });
  return save();
}

async function save(): Promise<void> {
  const dataFile = ...;
  const output = JSON.stringify(data, null, '  ') + '\n';
  await fs.writeFileAsync(dataFile, output, { encoding: 'utf8' });
}
```

**Comment by JimmyLv** [comment]
real slow too...

**Comment by jeffmo** [comment]
This certainly seems like something the Flow core team should look into, but can you move this over to the [flow](https://github.com/facebook/flow) repo?

This repo is only about library definitions, not the typechecker itself.

**Comment by jeffmo** [comment]
(I've copied your report over to https://github.com/facebook/flow/issues/2586)
