### ISSUE TITLE
[cli] `flow-typed update`

### ISSUE THREAD

**Issue by jeffmo** [flowtype/flow-typed#317]
This is a pretty natural command to expect, and it can probably just be an alias for `flow-typed install -o`: "Install everything, and overwrite the libdefs if they already exist"

**Comment by mwalkerwells** [comment]
@jeffmo ``flow-typed install`` is currently overwriting any libdefs (flow-typed stubs) that have not been merged with this repo. So it seems ``flow-typed update`` and ``flow-typed install`` behave the same.

I just lost a lot of uncommited stubs 😭 .

**Comment by GAntoine** [comment]
@mwalkerwells Sorry to hear you lost all that work. 😕  Is this a new thing `flow-typed` is doing, or do you think it's an old bug you just encountered?

**Comment by mwalkerwells** [comment]
Not sure, I hadn't tried in the past. Right now, I've just added the following to my ``package.json`` file: ``"flow-typed:update": "flow-typed update --skip",``. I then individually call ``flow-typed create-stub PACKAGE_NAME`` before stubbing out (commit beforehand just incase something goes wrong).

macOS 10.13 Beta (17A315i)
flow-typed@2.1.5

**Comment by GAntoine** [comment]
Looks like it's indeed a bug, or at least a function of the original implementation. I'll open a PR and we can discuss it there.
