### ISSUE TITLE
[cli] support scoped npm packages in `flow-typed install`

### ISSUE THREAD

**Issue by jeffmo** [flowtype/flow-typed#320]
https://github.com/flowtype/flow-typed/pull/303 added support for scoped npm packages, but https://github.com/flowtype/flow-typed/pull/289 went in simultaneously.

Need to circle back and makes sure that `flow-typed install` (with a scoped package in package.json) and `flow-typed install @foo/bar@1.2.3` both work.

**Comment by stowball** [comment]
Are sure this is fixed? I have @exponent/ex-navigation as a dependency in my project (which actually uses flow), but no definition was generated so I get `Required module not found`
