### ISSUE TITLE
[cli] Dedupe existing libdefs on `flow-typed install -o`

### ISSUE THREAD

**Issue by jeffmo** [flowtype/flow-typed#334]
Currently if you generate a stub for `foo`, it will create a stub libdef called `foo_vx.x.x`.
Then, maybe later on, someone else contributes a libdef for `foo`.

If you now run `flow-typed install -o`, the CLI will simply install a new libdef _adjacent_ to the previous one (which is wrong!).

Instead, `install` should scan the list of installed libdefs and consider an existing libdef for a less-appropriate version to be an "overwrite". The CLI should delete it if the `--overwrite` flag is passed, but do nothing if not.

**Comment by bsr203** [comment]
could be related. How to not create stub for already existing lib def. If, for example, I modify a stub, ` flow-typed update` overwrites it every time .

**Comment by GAntoine** [comment]
Wow, didn't realize this was an old issue. It's been fixed with #1016!
