### ISSUE TITLE
Support for react-router 4

### ISSUE THREAD

**Issue by aaronjensen** [flowtype/flow-typed#341]
It's alpha right now so we may not want it here, but I'm opening this issue to at least share the definitions I have so far for 4.0.0-alpha.3

https://gist.github.com/aaronjensen/48fcfaa0d540805d30fa18114c224f3f

**Comment by jeffmo** [comment]
Nice. `flow-typed` is pretty strict about the versioning patterns that are allowed, and I think `maj.min.ptc-alpha` versions aren't currently supported yet -- but we probably could/should support that!

**Comment by jeffmo** [comment]
Linking this in to https://github.com/flowtype/flow-typed/issues/392 to track support for prerelease identifiers

**Comment by aaronjensen** [comment]
Works for me, if #714 is the only API change so far then awesome. @jeffmo if you could merge #714 in asap that'd be great, it's a breaking change for the release version.
