### ISSUE TITLE
Parse flow version from .flowconfig?

### ISSUE THREAD

**Issue by kasperpeulen** [flowtype/flow-typed#343]
I get this error:

```
⇒  flow-typed install jest
Failed to find a flow-bin dependency in package.json.
Please install flow bin: `npm install --save-dev flow-bin` or provide a version on the command line: `flow-typed install --flowVersion=0.24.0`
```

My .flowconfig looks like this:

```
[ignore]
<PROJECT_ROOT>/node_modules/fbjs/.*

[include]

[libs]

[options]

[version]
0.32.0
```

Maybe use that version information?

**Comment by jeffmo** [comment]
What should we do if there's both a flow-bin and a `[version]` and they don't align?
Probably error, I guess... (That's a dangerous state to be in anyway)

Ideally `flow-bin` would be the way you dictate the version of Flow you're using though. For my own understanding, can you describe your workflow for running Flow?

**Comment by kasperpeulen** [comment]
@jeffmo I use create-react-app, and Webstorm, with these settings:

<img width="774" alt="screen shot 2016-09-29 at 10 51 25" src="https://cloud.githubusercontent.com/assets/1035299/18947281/b032e4a6-8632-11e6-9da2-f541115a3c9f.png">

Do you think it is better to not install flow globally, but only locally instead? (And point Webstorm to this local flow executable)

**Comment by jeffmo** [comment]
Indeed, I would recommend switching off of a global install in favor of a local `flow-bin` dependency. Installing locally ensures that anyone who checks out the project will use the correct version of Flow with the project.

In any case, it would be good for `flow-typed` to give this advice directly if it notices a .flowconfig but no `flow-bin` package.json dependency.

I'll leave this issue open to track that work item
