### ISSUE TITLE
npm install problem: command not found: flow-typed

### ISSUE THREAD

**Issue by andyfenelon** [flowtype/flow-typed#348]
following the install guide
> $ npm install -g flow-typed
> /Users/user/.nvm/versions/node/v5.2.0/lib
> └── flow-typed@1.0.0 
> 

error

> $ flow-typed
> zsh: command not found: flow-typed
> 

$ npm -v

> 3.3.12

**Comment by csvan** [comment]
Can you use other globally installed npm libs? What happens if you restart the terminal (looks like you are on OSX) and try running flow-typed again?

**Comment by jeffmo** [comment]
Do you have the directory that `npm install -g` installs to in your `$PATH`? You may need to add that...

On my machine it's `/usr/local/bin/`, but it may be different for you

**Comment by shahmeernavid** [comment]
@andyfenelon Ran into this as well. It looks by default, npm installs version 1.0.0 of flow-typed. Running npm install -g flow-typed@2.0.0-beta.11` worked for me.

**Comment by andyfenelon** [comment]
@shahmeernavid  that's fixed it.. thank you.

**Comment by jeffmo** [comment]
v2.0.0 is out now, so hopefully this should be resolved

**Comment by rubengt01** [comment]
I am seeing this issue.

npm install -g flow-typed  (flow-typed@2.1.2)
npm -v (4.2.0)
