### ISSUE TITLE
Syntax error in src/lib/libDefs.js

### ISSUE THREAD

**Issue by Kriegslustig** [flowtype/flow-typed#350]
The changes in `src/lib/libDefs.js` in commit #d9339f8 breaks the build of `cli` for me.

**Error output:**

```
SyntaxError: src/lib/libDefs.js: Unexpected token (19:22)   
  17 | const P = Promise;
  18 |
> 19 | export type LibDef = {|
     |                       ^
  20 |   pkgName: string,
  21 |   pkgVersionStr: string,
  22 |   flowVersion: Version,
```

**Diff:**

```
diff --git a/cli/src/lib/libDefs.js b/cli/src/lib/libDefs.js
index 4941642..29cff96 100644
--- a/cli/src/lib/libDefs.js
+++ b/cli/src/lib/libDefs.js
@@ -16,14 +16,14 @@ import type {Version} from "./semver.js";
 
 const P = Promise;
 
-export type LibDef = {
+export type LibDef = {|
   pkgName: string,
   pkgVersionStr: string,
   flowVersion: Version,
   flowVersionStr: string,
   path: string,
   testFilePaths: Array<string>,
-};
+|};
```

Tested on Mac OS 10.11.6. Using Node 4.6.0 and Node 6.7.0.

What does this `{|` syntax mean? I couln'd find any information about it.

**Comment by jeffmo** [comment]
It's new Flow "exact type" syntax (we haven't announced it yet but it's ready for use).

Try deleting your node_modules directory and re-`npm install`-ing. It requires the latest version of Babel.

Exact types are just object types that have *exactly* the properties specified (no less **and** no more). Normal objects support subtyping, so they only guaratee that they have *at least* the properties specified (but they may also have more). There are some benefits of using exact types when they're appropriate like guaranteeing that property typos get caught.

Please re-open if you still have issues after npm installing

**Comment by Kriegslustig** [comment]
Aah, thank you very much! That worked!
