### ISSUE TITLE
RxJS lib def doesn't install from cli

### ISSUE THREAD

**Issue by goldhand** [flowtype/flow-typed#362]
I have rxjs `5.0.0-beta.12` in my package.json and when I follow the cli install instructions a new file `rxjs_vx.x.x.js` is automatically created instead of installing the desired [rxjs_v5 libdef](https://github.com/flowtype/flow-typed/tree/master/definitions/npm/rxjs_v5.0.x).

Im using node v6.5.0 on OSX 10.11.6

Maybe this is an issue with the `-beta` tag?

**Comment by obimod** [comment]
@goldhand Yes, looks like [semver.js](https://github.com/vuejs/flow-typed/blob/master/cli/src/lib/semver.js) could support [prerelease identifiers](https://docs.npmjs.com/misc/semver#prerelease-identifiers).

**Comment by jeffmo** [comment]
Currently flow-typed libdef versions don't support prerelease identifiers, but this is mostly just oversight and we should fix that.

Thanks for the report!

**Comment by jeffmo** [comment]
Going to consolidate this into [a toplevel issue](https://github.com/flowtype/flow-typed/issues/392) tracking prerelease identifier support since there has been at least 1 other report as well.

**Comment by rgbkrk** [comment]
Is the best way to handle this to merely copy the version that's on master for RxJS 5?
