### ISSUE TITLE
<T> in comment syntax?

### ISSUE THREAD

**Issue by unhammer** [flowtype/flow-typed#382]
I'd like a function like `var safeGet = function<T>(key:string, fallback:T):T` declared using comment syntax – is that possible? Doing `/*:<T>*/ `at that spot gives an "Unexpected token" error from flow (although I am able to define that in e.g. firefox dev console, so I'm guessing it's ok js syntax to have a comment there?)

If not, is it possible to declare types of functions in interfaces even though they're implemented in my file? (Without a type declaration on safeGet, I end up with lots of errors on the call-sites.)

**Comment by jeffmo** [comment]
You can use `/*::<T>*/` to write arbitrary code that Flow sees, but a JS engine would not.
Check out the blog post which details the various options: https://flowtype.org/blog/2015/02/20/Flow-Comments.html#section-1

(PS: In the future it's better to ask general Flow questions over in [the Flow repo](https://github.com/facebook/flow) :) )

**Comment by unhammer** [comment]
doh, somehow thought I was in flow's repo … but thanks a bunch, works great =D
