### ISSUE TITLE
Does anyone already have flow-typed definitions for jQuery and jQueryUI ?

### ISSUE THREAD

**Issue by doberkofler** [flowtype/flow-typed#384]

**Comment by marudor** [comment]
You can find jquery here:
https://github.com/marudor/flowInterfaces

**Comment by doberkofler** [comment]
@marudor Thank you. Excellent work. Two questions:
- will you move the definitions to flow-typed?
- do you also have definitions for jQurey plugins especially for jQuery UI?

**Comment by marudor** [comment]
@doberkofler Yes, the plan is to move it to flow-typed.
No, I do not have any plugins typed.

The one in my repository was a PR. Didn't type it myself.

**Comment by doberkofler** [comment]
@marudor Would you know how to actually extend the existing jQuery definitions (https://github.com/marudor/flowInterfaces) without actually having to copy and paste them together when jQuery plugins must be defined? I cannot seem to find a problem solution in flowjs.

**Comment by doberkofler** [comment]
@marudor Any news on when this will be available?

**Comment by marudor** [comment]
Once someone writes Tests for it.
I'm busy and haven't been able to yet.
Feel free to copy paste it and get it in here. (With tests)

**Comment by doberkofler** [comment]
@marudor I started working on this and am currently adding tests. Unfortunately there are quite a few issues with the existing definition and would need some help to better understand the library definitions.

I'm for example unable to create tests for the with functions:

The tests look like this:
```
//width(): number;
testNumber = $('div').width();

//width(value: number | string): JQuery;
testSelector = $('div').width(50);

//width(func: (index: number, width: number) => number | string): JQuery;
testSelector = $('div').width(function (index) {
	return index * 50;
});
```

and I get the following error message:
```
0-test_jquery.js:471
471: testSelector = $('div').width(50);
                    ^^^^^^^^^^^^^^^^^^ number. This type is incompatible with
 22: let testSelector: JQuery = $('div');
                       ^^^^^^ JQuery

0-test_jquery.js:474
474: testSelector = $('div').width(function (index) {
                    ^ number. This type is incompatible with
 22: let testSelector: JQuery = $('div');
                       ^^^^^^ JQuery
```

Could you help me to understand what's wrong here?
Is it generally allowed to "overload" function definitions?
Whom else might I contact to get some help on this?

Thank you!

**Comment by GAntoine** [comment]
Closing as the PR above added a jquery definition.
