### ISSUE TITLE
Stubbed definitions trigger ESLint error: "Only declares are allowed inside declare module"

### ISSUE THREAD

**Issue by admmasters** [flowtype/flow-typed#389]
Great work on generating stubs for missing definitions - this feels like the right approach. There is an issue though: a stub might generate the following:

``` js
declare module 'autoprefixer' {
  declare module.exports: any;
}
```

This triggers the parsing error:  "Unexpected token. Only declares are allowed inside declare module". Using the parser: 'babel-eslint'.
This (closed) issue against babylon has the same error message: https://github.com/babel/babylon/pull/73

**Comment by jeffmo** [comment]
Indeed, this is syntax that we need to add support for over in babylon.

In the meantime, as a workaround, maybe you can ignore the `flow-typed/` directory in your eslint config?

**Comment by admmasters** [comment]
No problem, that's what I'm currently doing :)

**Comment by GAntoine** [comment]
@admmasters Is this still the case, or was this fixed by babylon at one point?
