### ISSUE TITLE
[CLI] `flow-typed install` ignore some package which could be `create-stub`

### ISSUE THREAD

**Issue by morlay** [flowtype/flow-typed#393]
https://github.com/morlay/flow-typed-issue-demo

``` json
{
  "private": true,
  "dependencies": {
    "flow-bin": "0.33.0",
    "flow-typed": "2.0.0",
    "json-schema-to-flow-type": "0.1.2"
  }
}
```

The `json-schema-to-flow-type` will not be created stub when run `flow-typed install`;
`flow-typed create-stub json-schema-to-flow-type@0.1.2` works well.

**Comment by morlay** [comment]
After debug for `install` command，
it seems because this
https://github.com/flowtype/flow-typed/blob/master/cli/src/lib/stubUtils.js#L169
```js
glob("**/*.flow")
```
Should we need check flow files so deeply?
Somebody may publish package with source files which are include flow files.

**Comment by luislhl** [comment]
I also had a problem with this recently with graphql.  
The problem with creating a stub in these cases is that you don't benefit from the types defined by the project.

Instead, I changed the [ignore] in my .flowconfig to not ignore .flow files, just .js and .json:
```
.*/node_modules/.*\.js$
.*/node_modules/.*\.json$
```

**Comment by GAntoine** [comment]
Closing as the current behaviour is the intended one.
