### ISSUE TITLE
UNCAUGHT ERROR: TypeError: Invalid comparator: latest

### ISSUE THREAD

**Issue by superherointj** [flowtype/flow-typed#399]
When trying to do "flow-typed install", it fails, error follows:

> c:\dev\project1>flow-typed install
> UNCAUGHT ERROR: TypeError: Invalid comparator: latest
>     at Comparator.parse (C:\Program Files (x86)\Nodist\bin\node_modules\flow-typed\node_modules\semver\semver.js:678:11)
>     at new Comparator (C:\Program Files (x86)\Nodist\bin\node_modules\flow-typed\node_modules\semver\semver.js:662:8)
>     at C:\Program Files (x86)\Nodist\bin\node_modules\flow-typed\node_modules\semver\semver.js:780:12
>     at Array.map (native)
>     at Range.parseRange (C:\Program Files (x86)\Nodist\bin\node_modules\flow-typed\node_modules\semver\semver.js:779:13)
>     at Range.<anonymous> (C:\Program Files (x86)\Nodist\bin\node_modules\flow-typed\node_modules\semver\semver.js:721:17)
>     at Array.map (native)
>     at new Range (C:\Program Files (x86)\Nodist\bin\node_modules\flow-typed\node_modules\semver\semver.js:720:40)
>     at determineFlowVersion$ (C:\Program Files (x86)\Nodist\bin\node_modules\flow-typed\dist\lib\npmProjectUtils.js:195:26)
>     at tryCatch (C:\Program Files (x86)\Nodist\bin\node_modules\flow-typed\node_modules\regenerator-runtime\runtime.js:62:40)

What causes this error?

**Comment by relekang** [comment]
Based on the stacktrace it looks like one or more of dependencies has version set to latest. Example:
```
"dependencies": {
  "react": "latest"
}
```
flow-typed does not support that in its current implementation.

**Comment by superherointj** [comment]
@relekang Thanks for answering. Setting specific module versions for dependencies & devDependencies in package.json worked. 

I find value in using 'latest' for modules during development time. And blocking it is an unfortunate feature. Also the hint provided by Flow-Typed isn't enough for the average user to grasp what is going on.

So, I'd suggest to consider feature request:
1) Better hint for it not accepting 'latest' for modules in package.json
2) Allowing 'Latest' version for module dependencies in package.json.

Again, thank you very much for your input.

**Comment by jeffmo** [comment]
We probably shouldn't fatal the CLI (hence the "bug" tag for this issue), but there's no way for `flow-typed install` to know which version of a libdef to install -- so using `latest` is going to limit the utility of the CLI here.

**Comment by rricard** [comment]
@jeffmo having a similar issue with tarball/git provided modules. Same thing, I get an invalid comparator. The concerned package would only need to get stubbed. But this make fail all other packages retrieval. Would it be possible to make this error as a warning and stub the module if this fails? (context: I'm working on integrating flow into create-react-app and for local end-to-end testing, we rely on a .tgz version of react-scripts, this make the build fail, so I had to silence the error...)

**Comment by IanVS** [comment]
FWIW, it also fails with that error on a repo#sha combo, like `nutshellcrm/react-joyride#bd5fb0a27d44dec5893bf425b88971222b317275`.

**Comment by bradennapier** [comment]
Yeah this should definitely just ignore and/or install the latest libdef ... really annoying since tons of package authors sayt to use @next and that guarantees your shit is broken unless you know this.

**Comment by GAntoine** [comment]
Closing in favour of feature issue #1127.
