### ISSUE TITLE
Running def tests is unnecessarily slow

### ISSUE THREAD

**Issue by nmote** [flowtype/flow-typed#414]
`./run_def_tests.sh rxjs` (or any library, this is just what I've been working on) does all of the following:
- `npm install` in `./definitions`
- Runs ESLint on _all_ the typedefs
- `npm install` in `./cli`
- Transpiles all CLI code
- Runs the tests for the CLI code
- Runs ESLint for all the CLI code
- Runs `validate-defs` for all the libdefs (not just the ones under test)
- Finally runs the actual def tests that I wanted to run.

All told, this takes 20-25 seconds on my laptop. That's not very good for making quick iterations on libdefs and testing them.

**Comment by jeffmo** [comment]
Good feedback, speed of the test-runner could definitely use some love.
Care to dig in and send some PRs to help make it faster? :)

**Comment by nmote** [comment]
I hope so. I'll try to find some time.
