### ISSUE TITLE
Switch to yarn

### ISSUE THREAD

**Issue by nmote** [flowtype/flow-typed#415]
Among other things, it may alleviate some of the issues in #414.

**Comment by jeffmo** [comment]
By switch to yarn, do you just mean use it instead of `npm` in the travis build steps?

**Comment by nmote** [comment]
Yeah, and in any other scripts where it appears (such as `./run_def_tests.sh` -- I don't know if that's used in Travis)

**Comment by GAntoine** [comment]
Done at #1417
