### ISSUE TITLE
Definitions for react-native

### ISSUE THREAD

**Issue by dralletje** [flowtype/flow-typed#418]
Although react-native is written with a lot of flow, they don't seem to be checked a lot, or they are incomplete in a lot of places. Either way I can not use them with `react-native-web` without installing `react-native` itself.

Is there a reason why there isn't a react-native one yet, or just no one has tried?
For the latter, I would love to make a definition!

**Comment by nmote** [comment]
I suspect that it's just that nobody's done it yet

**Comment by jeffmo** [comment]
This may be an issue better opened on the react-native repo, but I don't know of any reasons why -- on the flow-typed side of things -- there aren't libdefs here. If I were to guess I'd speculate the same as @nmote

**Comment by sibelius** [comment]
flowtype will be added to react native repo as described in the roadmap: https://github.com/facebook/react-native/wiki/Roadmap#developer-experience
