### ISSUE TITLE
Example usage of importing libdef type

### ISSUE THREAD

**Issue by adriancooney** [flowtype/flow-typed#438]
It's pretty obvious once you figure it out but it took me a quite a while via some pretty obscure Google searches to find out *how to actually use a libdef* and by "use", I mean import a type (e.g. `moment`). A little example in the README would be nice like:

> And you can use your new libdefs like:
```js
import type moment from "moment";

type Apple = {
    sellByDate: moment
    weight: number
}
```

**Comment by jeffmo** [comment]
Thanks for the feedback! You can find docs like this over on flowtype.org:

https://flowtype.org/docs/modules.html#import-type

**Comment by fastfrwrd** [comment]
I know this is closed, but I just spent quite a bit of time with the same problem. Still not sure how to import the `Middleware` type from the redux libdef, frankly. Do I directly import from the file in the `flow-typed` directory? I know that's not right, just pointing out a question I had and could not find an answer to.

**Comment by pschlette** [comment]
This wasn't obvious to me either. I wanted to import a type from the library `axios`. I know that axios itself doesn't contain the type information, the flow-typed file does (in `flow-typed/npm/axios_whatever.js`), so I tried to import the type from there - which doesn't work. The linked documentation page makes sense to me when I have types in my own code because I'm including the file that the types are declared in. In this case though, what I needed to do was include the file that the types are declared _for_: `import { AxiosPromise } from 'axios'`. I figured it out by searching for and reading this (closed) issue.

**Comment by gleb-lobastov** [comment]
> I figured it out by searching for and reading this (closed) issue.

Me also. Finally I come to such solution:
1. Add folder with libdefs to libs section in your .flowconfig:
```
[libs]
./flow-typed
```
2. Import types with separate statement as shown:
```
import { reduxForm, Form, FormSection} from 'redux-form';
import type { FormComponentProps } from 'redux-form';  
```

**Comment by OzairP** [comment]
Yea this is super confusing, the README.md should provide more information on how to get started with this.

**Comment by dvakatsiienko** [comment]
+1, it took me a while to crack down mechanism of writing a custom libdef, whould be cool to see a clear step-by step live example for dummies

**Comment by GAntoine** [comment]
I've created a short wiki page: https://github.com/flowtype/flow-typed/wiki/Importing-And-Using-Type-Definitions

Comments and criticisms are welcome!

**Comment by OzairP** [comment]
@GAntoine could you add a link to this on the README as well? Increases visibility == less issues about this stuff :)

**Comment by GAntoine** [comment]
I'm tempted to write a few more entries to the wiki, then I'll open a PR with a link to the relevant wikis.

**Comment by budleigh** [comment]
I still needed to google this after reading the libdef documentation. Why are there 0 usage examples [here](https://flow.org/en/docs/libdefs/)? @GAntoine's wiki content seems like a drop-in.

**Comment by GAntoine** [comment]
Thanks @budleigh, I'll have a talk to the flow team about enhancing that page, or at least linking directly to some examples. You're welcome to [reach out](https://twitter.com/flowtype) as well if you have any feedback about the docs.

**Comment by SilencerWeb** [comment]
I still can't get how to use flow-typed and docs don't help at all. Could you help me?

**Comment by GAntoine** [comment]
Hey @SilencerWeb, where are you stuck?

**Comment by n1ru4l** [comment]
@GAntoine Hey there, I am also having issues finding a guide on how I import the library definitions that come with flow (e.g. BOM or DOM).

**Comment by SilencerWeb** [comment]
@GAntoine, hey, sorry for delay, here is my issue https://github.com/flowtype/flow-typed/issues/1743

**Comment by GAntoine** [comment]
@n1ru4l You might want to take a look at the flow docs on `flow.org`, I don't have a wiki for using built-in definitions. The flow repo itself might have some information as well. The best we've got is https://github.com/flowtype/flow-typed/wiki/Importing-And-Using-Type-Definitions

**Comment by n1ru4l** [comment]
@GAntoine There is a list of built in types. However I still have not figured out how I could use them

**Comment by GAntoine** [comment]
There's a cheat-sheet [here](https://www.saltycrane.com/flow-type-cheat-sheet/latest/), which list the most useful React and DOM types.

**Comment by n1ru4l** [comment]
@GAntoine So they should be globals?

**Comment by GAntoine** [comment]
Yes, they should be available globally.

**Comment by zeekrey** [comment]
I still don't get it. :( 

I installed everything as described in the readme. I use _react-native-firebase_ but the types should be the same as the normal firebase. That's why I installed _flow-typed install firebase@5.4.2_ and added the dependency: _import type { FirebaseUser } from 'firebase/auth'_
But my IDE says 'Cannot import "FirebaseUser"  because there is no "FirebaseUser" export in "firebase/auth"'.

Any ideas?

**Comment by oTree-org** [comment]
I have a similar question as @n1ru4l. I am looking at the [Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAhjApgJwC4AUA5ABZYzxgJw4wAmRAlANxA) tool, and when I write:

```
/* @flow */
alert('hello world');
```

I get ```Cannot resolve name 'alert'```.

How can I write code that references `document`, `window`, `alert`, and other variables that are ordinarily defined in the browser?

**Comment by pascalduez** [comment]
@oTree-org 

First this is not related to `flow-typed` but Flow core.  
Second, I don't have the references at hand, but I remember that the online "try flow" interface can't load all of the core "lib" definitions for performance reasons. This includes all DOM definitions.

**Comment by oTree-org** [comment]
@pascalduez OK thank you! (And sorry I was in the wrong repo)
