### ISSUE TITLE
Ability to exclude devDependencies from generating definitions

### ISSUE THREAD

**Issue by stowball** [flowtype/flow-typed#453]
I can't think of a good reason why devDependencies should be included in the type definitions, so either they should be excluded by default, or an option should allow them to be excluded

**Comment by jeffmo** [comment]
We include libdefs for `devDependencies` because the only time it makes sense for Flow to run on a project is during development -- which is when you might be depending on devDependencies.

Can you expand a bit on why you'd want to exclude them?

**Comment by TLadd** [comment]
A lot of the devDependencies in my projects are things like babel plugins and webpack loaders, where there's really not an opportunity for type checking to come into play. As a result, I end up with a bunch of generated flow-typed files that I generally just view as clutter. 

I agree that it would be handy to be able to specify that you don't want to search for/generate a libdef for certain dependencies; I don't think a flag to turn all of devDependencies on/off would work in general, since you certainly could want libDefs for some devDependencies.

**Comment by stowball** [comment]
Here are my current project's `devDependencies`:

```json
"devDependencies": {
    "babel-eslint": "^6.1.2",
    "babel-jest": "17.0.0",
    "babel-preset-react-native": "1.9.0",
    "eslint": "^3.9.1",
    "eslint-plugin-flowtype": "^2.25.0",
    "eslint-plugin-react": "^6.6.0",
    "eslint-watch": "^2.1.14",
    "flow-bin": "^0.34.0",
    "flow-typed": "^2.0.0",
    "jest": "17.0.0",
    "jest-react-native": "17.0.0",
    "npm-run-all": "^3.1.1",
    "react-test-renderer": "15.3.2"
}
```

I don't need to use annotations for any of these things, and I can't see that I'd ever need to depend on them in my project code, because they're not available in production.

**Comment by ryyppy** [comment]
Do you really see this as a huge problem? You will barely interact with `flow-typed` files anyways... and they will not bloat your repository whatsoever, since they are mostly stubs?

**Comment by alxlu** [comment]
Dunno if this is a good solution or not, but to clean up the clutter, I ended up placing a `.gitignore` in the `flow-typed` directory with:
```
eslint*
babel*
...etc
```

**Comment by ryyppy** [comment]
@alxlu yeah, that's a really nice solution

**Comment by stowball** [comment]
That's not a nice solution for me. It's still manual work to ignore it every time you add a new `devDependency`

**Comment by jcperez-ch** [comment]
@ryyppy that a nice hack, but not a solution.  I agree that most of the times you don't want to skip even devDependencies, but I agree also, that it is annoying to add hacks to the `.gitignore` file because a simple configuration command is not available.

**Comment by paska27** [comment]
Bash command to install only from `dependencies`:
```bash
for dep in $(npm ls --prod --depth=0 --parseable --long | grep node_modules); do p=$(basename $dep); pp=${p#*:} && ppp=${pp%:*} && flow-typed install $ppp; done
```
