### ISSUE TITLE
Failed to find a flow-bin dependency in package.json for nested package.json files

### ISSUE THREAD

**Issue by matthewoates** [flowtype/flow-typed#455]
Love the CLI tool. It doesn't work out of the box with my project though.

My file structure looks something like this:
```
package.json // modules for the build system, tests, etc
client/
    package.json // client modules
    src/
        ...
shared/
    package.json // modules for the client and server
    src/
        ...
server/
    package.json // server modules
    src/
        ...
```

I get the following error:
```
~/workspace/boardom/client
 ➤ flow-typed install
Failed to find a flow-bin dependency in package.json.
Please install flow bin: `npm install --save-dev flow-bin` or provide a version on the command line: `flow-typed install --flowVersion=0.24.0
```

`Flow-bin` is only added to the topmost package.json. Flow has no issues with nested package.jsons, and it makes a lot of sense for my project. Would be great if flow-type supported this out of the box.

**Comment by jeffmo** [comment]
In this case you'll just need to specify the version of Flow being used manually with the `--flowVersion` flag. The reason `flow-typed` needs to find `flow-bin` is only to use it to auto-detect the Flow version.

However, it's not a very safe general assumption to make that a package.json that sits outside of a project's  directory indicates anything about the project itself.

For example: Consider the scenario where people might have a `package.json` file in their homedir (often without realizing it) and a project in a subdir of their homedir. We wouldn't want to accidentally install libdefs for the wrong version of Flow for the project based on the completely unrelated package.json up one level.

**Comment by mediaslav** [comment]
I think lot more sense is to:
1) check .flowconfig [version] first, 
2) flow-bin in package.json, 
3) flow in path
