### ISSUE TITLE
`table` version.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [flowtype/flow-typed#456]
Apologizes for the question, but why is `table` [locked to a specific version](https://github.com/flowtype/flow-typed/blob/master/cli/package.json#L61) while most of the other dependencies are not?  It is not a big deal, but it is preventing a clean dedupe with `eslint`.

**Comment by jeffmo** [comment]
Based on blame, this dependency seems to be super super old.
I don't think there's a good reason for this -- want to send a PR to update it?

**Comment by wtgtybhertgeghgtwtg** [comment]
I'd be honored.  Is #462 okay?
