### ISSUE TITLE
Replacing a libdef with a custom one, robustly

### ISSUE THREAD

**Issue by jtlapp** [flowtype/flow-typed#465]
How do I replace a libdef with a custom one of my own creation? I still want the full benefit of all the other libdefs.

Equivalently, I'd like to remove one libdef, but I don't want subsequent updates of my libdefs to undo the replacement. It seems to me that simply deleting the libdef from the `flow-typed` directory would suffer this problem.

The number of challenges I'm having with the Express libdef has grown to the point where I just don't see how I'm going to be able to use it. All I want are limited views of the request and response objects, extended with my session information and utility methods.

**Comment by ryyppy** [comment]
I recommend moving the `flow-typed/npm/express` directly to `flow-typed/` (move out of `/npm`) and add your customizations to the original libdef file... you have to check in `flow-typed` dependencies in your source-control anyways.... by separating `npm` with non-npm, you always know which are the official libdefs from `flow-typed`.

**Comment by jtlapp** [comment]
Okay thanks. But wouldn't a `flow-typed update` overwrite my mods, forcing me to recover them via git each time?

**Comment by jtlapp** [comment]
Another option is to create a wrapper class and use that everywhere, but that would be letting the particulars of `flow-typed` dictate software design. Not ideal.

**Comment by ryyppy** [comment]
@jtlapp 
> Okay thanks. But wouldn't a flow-typed update overwrite my mods, forcing me to recover them via git each time?

No, it will only overwrite the file located in `flow-typed/npm` ... this is `flow-typed`'s way of expressing a namespace for libdefs

> 
Another option is to create a wrapper class and use that everywhere, but that would be letting the particulars of flow-typed dictate software design. Not ideal.

Yep, you are right... I would really recommend modify the flow-typed definition locally outside of the `flow-typed/npm` directory

**Comment by jtlapp** [comment]
It sounds like you're saying that a file present at `flow-typed/` will override one of the same name at `flow-typed/npm/`. Attempting this with original libdef, I get an error that baffles me. The libdef works in `flow-typed/npm/` but not in `flow-typed/`:

````js
flow-typed/express_v4.x.x.js:2
  2: import type { Server } from 'http';
                   ^^^^^^ Named import from module `http`. This module has no named export called `Server`.
````

**Comment by jtlapp** [comment]
And when I declare my own version of the module in `flow-typed/express_v4.x.x.js`, it ignores it completely and enforces the types of `flow-typed/npm/express_v4.x.x.js`.

So I appear to be misunderstanding your suggestion.

**Comment by ryyppy** [comment]
@jtlapp Did you actually remove the `flow-typed/npm/express_v4.x.x.js`? If you have to files doing a `declare module 'express'` it may take one of them... but not both.

Also, what is your `[libs]` configuration?

**Comment by jtlapp** [comment]
Yeah, playing around now I see that if I delete the one from `flow-typed/npm/` it will heed the one in `flow-typed/`. Interestingly, the import error also goes away.

Aha! If I specify the new libdef in `[libs]`, it ignores the one in `flow-typed/npm/`. Perfect!

I did read through the configuration file docs several times in search of something that would help. Maybe a blurb under `[libs]` saying that these libdef files override those of `flow-typed/npm/` would have wizened me sooner.

Thank you so much for your help!

**Comment by ryyppy** [comment]
@jtlapp By default, if there are no `[lib]` entries, `flow` will assume `flow-typed/` to be the libdef directory.... as soon as you define an entry, `flow-typed`, you also need to explicitly define `flow-typed` again.

Example: 

```
[lib]
# Without this, flow will not assume flow-typed anymore..
flow-typed
node_modules/react-native/lib/flow/react-native.js
```

**Comment by jtlapp** [comment]
Okay, thanks for that clarification. I vaguely recall having read that somewhere, but I don't see it in the docs for `[libs]`.

Also, it appears to me that the import error is always happening but is getting quietly swallowed when it occurs within a module declaration that `flow-typed` actually uses.

**Comment by Awpteamoose** [comment]
This broke in flow 0.53 for me.
