### ISSUE TITLE
Use ESDoc for inline comments in Definitions

### ISSUE THREAD

**Issue by orta** [flowtype/flow-typed#474]
Hey there flow-typed people - I wanted to add some ESDoc definitions to libraries I use, but I couldn't find any existing definition files that include this data already

Mainly wanted to know if PRs adding ESDoc documentation to the source inline ( like below ) would be 👌 ? (as it's quite a bit of effort, and don't want to not have them merged for reasons I don't know yet )

![2016-11-22 10_59_16](https://cloud.githubusercontent.com/assets/49038/20521343/b9643cec-b0a2-11e6-9520-a8b93aecccbd.gif)

**Comment by jeffmo** [comment]
Sure, I think useful comments are always a great improvement for libdefs!

**Comment by orta** [comment]
Thanks, shipped https://github.com/flowtype/flow-typed/pull/480
