### ISSUE TITLE
defaults property missing from Axios

### ISSUE THREAD

**Issue by corydeppen** [flowtype/flow-typed#476]
I just added Flow to a module that uses transformResponse in the config and noticed I get the error ```property `defaults`. Property not found in Axios```. Being new to Flow, I modified the definition to include `defaults: Object;` and was able to continue with no errors, but I'm concerned this may not be preferred. Since `AxiosXHRConfig` is a generic interface, I wasn't sure if it was possible to get the type inside the non-generic Axios class.

**Comment by ryyppy** [comment]
How does your module interact with the `axios` node_module? How do you import it?

**Comment by corydeppen** [comment]
`import axios from 'axios';`

**Comment by ryyppy** [comment]
I just installed the `v0.15.x` libdef and wrote following program:

```
import axios from 'axios';

const a = axios({
  url: 'foo',
  transformResponse: [function (data) {
    // Do whatever you want to transform the data

    return data;
  }]
});
```

It does typecheck for me... which `flow` version & `axios` libdef version did you use?

**Comment by corydeppen** [comment]
Sorry, I should have included more about the usage in my last reply. The error I see appears when using axios like the following:

```js
constructor() {
  this.api = axios.create({
    baseURL: '/api/v1/applications',
  });
}

getKeys(id: string) {
  const config = {
    transformResponse: this.api.defaults.transformResponse.concat(getEnhancedKeys),
  };
  // ...
}
```

**Comment by ryyppy** [comment]
Oh yeah, that makes sense... so you would probably need to add a defaults property to the Axis class definition as well... since AxisConfig has `transformResponse` as optional, you will probably also need to null check first in this case (which makes sense)...

**Comment by GAntoine** [comment]
Closing as the latest def has `defaults` on the constructor.
