### ISSUE TITLE
Consider replacing `request`.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [flowtype/flow-typed#490]
The use for `request` is [pretty simple](https://github.com/flowtype/flow-typed/blob/d0f06ec5404560855065857e78e25f201dfe80d2/cli/src/commands/runTests.js#L135).  Could it be replaced with something lighter, like `got` or `fetch`?

**Comment by ryyppy** [comment]
Hey!
What is the benefit of doing so?

**Comment by wtgtybhertgeghgtwtg** [comment]
Less overall dependencies.  About half of the overall dependencies for `flow-typed` are currently from `request`.  Additionally, there may be some [security concerns](https://github.com/request/request/issues/2230), but I am not too sure if that would actually be a problem for this use case.
The argument has been made, much more articulately, for some other packages, such as [`yarn`](https://github.com/yarnpkg/yarn/issues/1461), [`node-pre-gyp`](https://github.com/mapbox/node-pre-gyp/issues/198), and [`jsdom`](https://github.com/tmpvar/jsdom/pull/1630).

**Comment by ryyppy** [comment]
Makes sense... it seems you have followed the `yarn` discussion... if you have a good replacement and create a PR, I would consider reviewing & merging it!

**Comment by wtgtybhertgeghgtwtg** [comment]
I'll see what I can do, but since the `scripts` aren't Windows friendly, that might not be much.

**Comment by ryyppy** [comment]
True dat, so we also need to make the build steps work for windows as well.. not sure how to proceed for now... if you are motivated to make this happen, I am happy to try it on my machine as well!

**Comment by wtgtybhertgeghgtwtg** [comment]
PR to make scripts work on Windows: #522.

**Comment by wtgtybhertgeghgtwtg** [comment]
I have this complete, but there were never any tests for it.  #526 would help.
