### ISSUE TITLE
express res.cookie takes a maxAge param that should be a number, not a string

### ISSUE THREAD

**Issue by demands** [flowtype/flow-typed#497]
I'm sorry that this is just a regular issue instead of a pull request, but I wanted to make sure that I recorded it somewhere before I forgot:

[According to the express documentation](http://expressjs.com/en/api.html#res.cookie), `res.cookie` takes a `maxAge` param, which should be a `number` (in milliseconds). The flow annotations for express complain when you pass a `number`; [flow thinks the argument should be a `string`](https://github.com/flowtype/flow-typed/blob/master/definitions/npm/express_v4.x.x/flow_v0.25.x-/express_v4.x.x.js#L49).

**Comment by ryyppy** [comment]
Fixed in #492
