### ISSUE TITLE
No flow@v0.36.0-compatible libdefs found in flow-typed

### ISSUE THREAD

**Issue by msudgh** [flowtype/flow-typed#527]
Hello Everybody,
when i run **`flow-typed install`** command i got **`No flow@v0.36.0-compatible libdefs found`** message, what's wrong?

```bash
$ flow-typed install
• Found flow-bin@v0.36.0 installed. Installing libdefs compatible with this version of Flow...
• Found 3 dependencies in package.json. Searching for libdefs...
• rebasing flow-typed cache...done.
• Installing 2 libdefs...
  • flow-typed/npm/express_v4.x.x.js already exists!
    └> Use --overwrite to overwrite the existing libdef.
  • flow-typed/npm/flow-bin_v0.x.x.js already exists!
    └> Use --overwrite to overwrite the existing libdef.
• Generating stubs for untyped dependencies...
  • global@^4.3.1
    └> flow-typed/npm/global_vx.x.x.js

!! No flow@v0.36.0-compatible libdefs found in flow-typed for the above untyped dependencies !!

   I've generated `any`-typed stubs for this package, but consider submitting
   a libdef for it to https://github.com/flowtype/flow-typed/
```

**Comment by ryyppy** [comment]
There is nothing wrong... you are using packages which are not covered as libdef files in `flow-typed` yet...

It's actually saying that in the last message:

```
   I've generated `any`-typed stubs for this package, but consider submitting
   a libdef for it to https://github.com/flowtype/flow-typed/
```

The idea is to create a basic scaffold a file for you, which (after you added your declarations), can be submitted to `flow-typed`.

If you look in your generated stub files, you will find something like this:

```
// flow-typed/npm/global_vx.x.x.js
declare module 'global' {
   declare module.exports: any;
}
```

So if you are using `global` in your code, it will be typed as `any`... which is not good by no means... we are happy for libdef contributions :-)

**Comment by msudgh** [comment]
Oh, You're right.
I didn't attention to messages.

Thanks

**Comment by nvmt2** [comment]
npx flow-typed create-stub name-package
