### ISSUE TITLE
Can't have dependency in peerDeps and devDeps (Error: Found react listed twice in package.json!)

### ISSUE THREAD

**Issue by AgentME** [flowtype/flow-typed#528]
If you clone https://github.com/StreakYC/react-menu-list and then run `flow-typed install` inside of it, then you get this error:

```
• Found flow-bin@v0.36.0 installed. Installing libdefs compatible with this version of Flow...
UNCAUGHT ERROR: Error: Found react listed twice in package.json!
    at /usr/local/lib/node_modules/flow-typed/dist/lib/npmProjectUtils.js:123:17
    at Array.forEach (native)
    at /usr/local/lib/node_modules/flow-typed/dist/lib/npmProjectUtils.js:121:35
    at Array.reduce (native)
    at getPackageJsonDependencies (/usr/local/lib/node_modules/flow-typed/dist/lib/npmProjectUtils.js:118:30)
    at Object.run$ (/usr/local/lib/node_modules/flow-typed/dist/commands/install.js:177:91)
    at tryCatch (/usr/local/lib/node_modules/flow-typed/node_modules/regenerator-runtime/runtime.js:64:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/flow-typed/node_modules/regenerator-runtime/runtime.js:355:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/flow-typed/node_modules/regenerator-runtime/runtime.js:116:21)
    at tryCatch (/usr/local/lib/node_modules/flow-typed/node_modules/regenerator-runtime/runtime.js:64:40)
```

Its [package.json](https://github.com/StreakYC/react-menu-list/blob/master/package.json) has react listed under both devDependencies and peerDependencies which is legal and sensible as far as I know. (If it's pulled as a dependency of an application, then that application needs to have its own copy of React already; it will never pull in its own copy of React because that would cause conflicts. If react-menu-list is developed on directly, its devDependencies are installed including its own copy of React.)

**Comment by ahutchings** [comment]
This was also reported in #379.

**Comment by dschinkel** [comment]
Has this been resolved yet?  I get this error also when trying to install it:

I run npm install, all fine
I run flow-typed install and get this:

```

**Comment by ahutchings** [comment]
I submitted #587 to fix this. You can temporarily work around the issue by removing the duplicate dependencies in package.json, running flow-typed install/update, then restoring the dependencies in package.json.

**Comment by ctrlplusb** [comment]
Blocking me from doing flow defs installs on travis. :(

**Comment by nodkz** [comment]
Flow@0.41 the same error
```
• Found flow-bin@v0.41.0 installed. Installing libdefs compatible with this version of Flow...
UNCAUGHT ERROR: Error: Found graphql listed twice in package.json!
    at /usr/local/lib/node_modules/flow-typed/dist/lib/npmProjectUtils.js:123:17
    at Array.forEach (native)
    at /usr/local/lib/node_modules/flow-typed/dist/lib/npmProjectUtils.js:121:35
    at Array.reduce (native)
```
with following `package.json`:
```
{
  ...
  "peerDependencies": {
    "graphql": "^0.9.1",
  },
  "devDependencies": {
    ...
    "flow-bin": "^0.41.0",
    "graphql": "^0.9.1",
    ...
  }
}
```

**Comment by dschinkel** [comment]
add this to your .flowconfig

```
[ignore]
.*/node_modules/fbjs/.*
```

**Comment by nikordaris** [comment]
Any work arounds for this other than avoiding peer dependencies?

**Comment by cef62** [comment]
@nikordaris currently we've made a script that temporarily clone the `package.json`, removes the peer dependencies node, executes `flow-typed` and then restore the original file. It's not ideal but is simple and it works.

**Comment by nikordaris** [comment]
@cef62 definitely not ideal but seems like a reasonable work around. Can you share your script?

**Comment by cef62** [comment]
I made a [gist](https://gist.github.com/cef62/abf525ab703d4f18b413b1fce2b85403) from our script. You can create a single file if you want, I've just copied the code from our automation module.

**Comment by SimenB** [comment]
This one-liner works as well, only dependency is `jq`: `mv package.json package.json.bak && jq 'del(.peerDependencies)' package.json.bak > package.json && flow-typed install && mv package.json.bak package.json`.

More workarounds discussed here: #379

**Comment by TrySound** [comment]
Guys. This sucks. Peer doesn't make sense for project, only for dependants.

**Comment by zachwolf** [comment]
Hello!

I'm still getting this issue. Is it expected to be fixed? If not, I'd be happy to submit a PR.

**Comment by dschinkel** [comment]
this worked for me, try this in your .flowconfig

```
[ignore]
.*/node_modules/fbjs/.*

flowEntities/
```
