### ISSUE TITLE
This command only works in a clone of flowtype/flow-typed. It is a tool used to validate the library definitions flow-typed project.

### ISSUE THREAD

**Issue by doberkofler** [flowtype/flow-typed#567]
I have been trying to enhance some of the type definitions but running on windows does not seem to be fully supported and I was not able to run the required unit tests.

I started by creating a `run_def_tests.cmd` version of `run_def_tests.sh` that looks like this:
```
cd definitions
call npm install
call npm test
cd ..\cli
call npm install 
node dist\cli.js validate-defs 
node dist\cli.js run-tests %*
```

and it seems to work but:

1) when running `eslint npm/**/test*` I get a large number of warning and an error:
```
D:\MyDev\doberkofler\flow-typed\definitions\npm\react-redux_v4.x.x\flow_v0.30.x-\test_Provider.js
  6:11  error  Parsing error: Unexpected token, expected ,
```
Is this expected?

2) Later when processing the script, I get the following error message:
```
D:\MyDev\doberkofler\flow-typed\cli>node dist\cli.js validate-defs
This command only works in a clone of flowtype/flow-typed. It is a tool used to validate the library definitions flow-typed project.
```
clearly I am working in a cloned repository and I have no idea what this is about?

3) More generally speaking, I'm surprised why there are so many open pull requests and was wondering, if this is just a backlog or something else?

**Comment by relekang** [comment]
2. This is probably because [this detection method is a bit to naive](https://github.com/flowtype/flow-typed/blob/master/cli/src/lib/isInFlowTypedRepo.js).
