### ISSUE TITLE
[express] express$Application type should be a function

### ISSUE THREAD

**Issue by thibaultdelor** [flowtype/flow-typed#575]
To illustrate my problem, here is the bit of code which is not working:
```javascript
const express = require('express');
var app = express();
var server = require('http').createServer(app);
```

Flow fails saying that `app` doesn't have the signature `(request: IncomingMessage, response: ServerResponse) => void`

Looking at [the express code](https://github.com/expressjs/express/blob/e71014f522fb8db9ba1ef634f2e9f2c8069e4b6c/lib/express.js#L36) the `express()` function actually returns a function with this signature and add some properties to the function. Not sure how, in flow, you declare a function which has also properties but at the moment the type `express$Application` is not correct.

**Comment by shuhei** [comment]
It seems like it's working now. https://github.com/philikon/flow-typed/blob/2e7ee1938215b65b677e93eb6f757d209064b061/definitions/npm/express_v4.x.x/flow_v0.32.x-/express_v4.x.x.js#L144
