### ISSUE TITLE
Type inference works differently with classes

### ISSUE THREAD

**Issue by lalnuo** [flowtype/flow-typed#576]
Is this intended behaviour?

With class:
https://flowtype.org/try/#0C4TwDgpgBAYg9nKBeKBvKA7ArgWwFxQD82OARhAE5QC+A3AFD0DGANgIYDOHUAKhB8DT0AkADMEBeHAZiEyIVEVKSBbCxb0lNBiNJsKACgCUCpcOAALAJYcAdOLi2S8gIwAmBlur1qQA

Without class:
https://flowtype.org/try/#0C4TwDgpgBAYg9nKBeKBvKA7ArgWwFxQD82OARhAE5QC+A3AFAA2EwUAZggfIvR4iqnpRMuAtkaN6dIXwB0JZFACMAJgZA

**Comment by ryyppy** [comment]
For the class version, you probably want it to do it like this:
https://flowtype.org/try/#0C4TwDgpgBAYg9nKBeKBvKA7ArgWwFxQD82OARhAE5QC+A3AFD0DGANgIYDOHUAKhB8DT0AkADMEBeIhSp6UeQpIFsLFnIV1Gw0mwoAKAJRCFC4evnDgACwCWHAHTi49ksigBGAEwMT1etSA
