### ISSUE TITLE
Create libdefs for lodash/fp

### ISSUE THREAD

**Issue by rgbkrk** [flowtype/flow-typed#577]
The signatures are _roughly_ the same as good ol' classic lodash, the [order is flipped a bit to have iteratee first, data last signatures while also auto-currying](https://github.com/lodash/lodash/wiki/FP-Guide). I have a feeling there is a decent way to generate these based on other efforts in lodash.

/cc @jdalton

**Comment by rgbkrk** [comment]
I've written out a few that were easy to work with based on my codebase. For others, especially `set` it's difficult because of the auto-currying.

A plain version of lodash/fp's `set` with all arguments placed is:

```
set<T>(path?: ?Array<string>|string, value: any, object?: ?T): T;
```

Whereas if I want to write out the curried versions, I start out with 

```
set<T: Object>(path: Array<string>|string): (value: any, object: T) => T;
```

Then I realize that I need to return the curried versions:

```
set<T: Object>(path: Array<string>|string): ( (value: any, object: T) => T ) | (value: any) => (object: T) => T;
```

I'm a bit lost on how to write these libdefs so I'll have to go without the beautiful `flow` (and turning off nuclide so I don't see my lack of coverage :wink:).

**Comment by yenbekbay** [comment]
I took some time to type the methods we use in our codebases. Here's what it looks like: https://github.com/anvilabs/flow-libdefs/blob/master/definitions/lodash.js. There are also some extensive tests: https://github.com/anvilabs/flow-libdefs/blob/master/test/lodash-test.js.

**Comment by rgbkrk** [comment]
Thanks @yenbekbay! Want to make a PR here or would you be ok with me trying to incorporate it?

**Comment by yenbekbay** [comment]
@rgbkrk There are still quite a few methods remaining that are untyped, and I'm not sure if I'll be able to finish them up in the nearest future. If you'd like to work on this and make a PR, I'm totally ok with that!

**Comment by robwise** [comment]
@rgbkrk Are you actively working on this? I can try to offer some help if you're busy. lodash/fp typedefs would change my life!!!

**Comment by rgbkrk** [comment]
Haven't touched it, went a different direction with our code base.

**Comment by robwise** [comment]
Okay maybe I will take a crack at it then

**Comment by jrnail23** [comment]
it _seems_ like types for lodash/fp might be able to borrow a bit from `ramda`, BTW.  Those two have a lot in common.

**Comment by robwise** [comment]
@jrnail23 Yeah for sure, I'm trying to basically steal from the non-fp lodash and from ramda typedefs

**Comment by GAntoine** [comment]
Closing as `lodash` has a module for `lodash/fp`.

**Comment by robwise** [comment]
PR is here: https://github.com/flowtype/flow-typed/pull/1262
