### ISSUE TITLE
Cannot Resolve Modules

### ISSUE THREAD

**Issue by dschinkel** [flowtype/flow-typed#586]
So I've been trying to resolve module references.  (screen cast of it here: https://youtu.be/CZHYD2-jb7I)

For instance take this one:

<img width="517" alt="screen shot 2017-01-01 at 8 27 17 pm" src="https://cloud.githubusercontent.com/assets/338798/21584104/bc526612-d060-11e6-981f-9c23317db10a.png">

When I look at PromiseMap.js for example, it can't resolve the Deferred module:

<img width="592" alt="screen shot 2017-01-01 at 8 28 17 pm" src="https://cloud.githubusercontent.com/assets/338798/21584108/e38648ca-d060-11e6-9c36-603675ac9200.png">

The Deferred module is in ./Deferred.js, but I notice in PromiseMap.js, it's trying to require it as require('Deferred');

<img width="297" alt="screen shot 2017-01-01 at 8 29 15 pm" src="https://cloud.githubusercontent.com/assets/338798/21584111/fb4c22ea-d060-11e6-8ab2-e4cd42b1f2ff.png">

Well, yea, if you add ./ to it, it resolves!

<img width="276" alt="screen shot 2017-01-01 at 8 29 46 pm" src="https://cloud.githubusercontent.com/assets/338798/21584112/0e895f58-d061-11e6-9763-83d2bdca2f8c.png">

Why isn't flow doing this?

I can't resolve it in .flowconfig.js so far trying various things:

<img width="697" alt="screen shot 2017-01-01 at 8 40 14 pm" src="https://cloud.githubusercontent.com/assets/338798/21584165/aafc80a8-d062-11e6-8efa-0c7bd2df493f.png">

**Comment by ryyppy** [comment]
You are using `haste-modules` (since there are this `@providesModule` tags in your jsdoc)...
So you need to teach `flow` to do haste-module resolving like this...

In your `.flowconfig >> [options]` section:
```
[options]
module.system=haste
```

Now `flow` should be able to find dependency defined as haste-modules.
Does this work?

**Comment by dschinkel** [comment]
thanks that resolved it.   Now when I run flow I get a ton of Duplicate module provider errors.  Ugh.  Ok, working on that now.

**Comment by dschinkel** [comment]
In case anyone reads this issue, here's more info on Flow setup https://github.com/samwgoldman/issue-react-flow-setup

**Comment by dschinkel** [comment]
For now I just nuked react-side-effect folder or any other folders giving me a Duplicate Module Provider.  I don't know if that has any implications by doing so but at least when I run Flow now, I get a clean result:

```
> flow; test $? -eq 0 -o $? -eq 2

Launching Flow server for /Users/dave/code/projects/we-do-tdd
Spawned flow server (pid=10700)
Logs will go
```
