### ISSUE TITLE
Option to not install libdefs for devDependencies?

### ISSUE THREAD

**Issue by tlrobinson** [flowtype/flow-typed#599]
Most of the time I don't need libdefs for devDepdendencies. It would be nice if `flow-typed install` had an option to not install those.

**Comment by web2style** [comment]
Also, maybe you can consider adding a CLI command to add libdef only for one or multiple specified dependency/ies. For example: `flow-type install redux-saga [...]`. I want to introduce types gradually and adding 100+ libdefs at once most of which are stubs is something weird to me.

If the specified libdef is missing in `flow-typed` repo it could ask if the user wants to add stubs file.

What do you think?

**Comment by apaatsio** [comment]
What would be the preferred command? 

I suppose the most common use case is that you want to install type defs for all `dependencies` and ignore all `devDependencies`. How about `peerDependencies` and `bundledDependencies`?

Maybe the command could be:
```sh
flow-type install --ignore-dev-dependencies
```
