### ISSUE TITLE
Export types/interfaces from libdef

### ISSUE THREAD

**Issue by mudetroit** [flowtype/flow-typed#622]
I was starting to work on creating my first libdef for a project that we happen to use, but I have run into na issue that I am simply not clear on. Is it possible to export types from your libdef? 

Specific example, I am working on creating a definition for [redux-act](https://github.com/pauldijou/redux-act), and I feel like it would be helpful for the definition for [createAction](https://github.com/pauldijou/redux-act#createactiondescription-payloadreducer-metareducer) to emit an `ActionCreator` type. However whenever I try to export a type/function/interface for this I get
```
 * redux-act_v1.x.x/flow_>=v0.38.x (flow-v0.38.0): Unexpected Flow errors(2):
   0-test_redux-act.js:2
     2: import { ActionCreator } from './redux-actions_v0.9.x';
                                      ^^^^^^^^^^^^^^^^^^^^^^^^ ./redux-actions_v0.9.x. Required module not found
```

Is this even possible? If not what would be the best way to handle something like this?

**Comment by alex-deas** [comment]
Are you sure the path is correct? Remember that JS imports are relative. So from what I can infer from the error message it looks you'd need `import { ActionCreator } from '../../redux-actions_v0.9.x/flow_v0.23.x/redux-actions_v0.9.x`

**Comment by mudetroit** [comment]
I think what I learned is that I should really be doing a declare here and not a exporting a type. Going to go ahead and close for now, and if I get stuck will reopen with much better details.
