### ISSUE TITLE
Bluebird library missing function return

### ISSUE THREAD

**Issue by moberemk** [flowtype/flow-typed#644]
I noticed earlier while working with Bluebird that Flow doesn't understand the following syntax:

```javascript
const Promise = require('bluebird');
const using = Promise.using;
```

It seems like the current definition only exports the Promise object, but not the `using` method. This makes sense given how the API is written currently, only exporting the `Bluebird$Promise` type which doesn't include that method, but it means that there's no documentation around that method.

**Comment by GAntoine** [comment]
Addressed at #901
