### ISSUE TITLE
Add Ability to Change libdef Directory

### ISSUE THREAD

**Issue by keplersj** [flowtype/flow-typed#646]
I've had to prefix the libdef directory with a period in order to hide it from Meteor at build time. It would be great to tell the flow-typed CLI the correct libdef directory when it install and updates libdefs.

**Comment by anton-kabysh** [comment]
+1. I want to specify output directory where to put type definitions.

**Comment by schovi** [comment]
+1

**Comment by GAntoine** [comment]
@keplersj `--libdefDir` was added with #1021.

@anton-kabysh @schovi

**Comment by keplersj** [comment]
Awesome to hear! We haven't used Meteor for the project I needed this on for a little while now so I won't be able to test to confirm. However the CLI option is exactly what I would've needed so I'm going to close this issue.
