### ISSUE TITLE
ESLint support?

### ISSUE THREAD

**Issue by ryyppy** [flowtype/flow-typed#65]
Since I am currently trying to take a stab for the `install` command, I got annoyed really fast by the missing `eslint` support... is this something you left out intentionally, or should I create a PR for adding it?

**Comment by jeffmo** [comment]
Fine by me if you add it. I'm generally not a big fan of lots of nuanced style rules, but the bug-finding lints are def good (and I'm sure some will appreciate things like tab-space enforcement, etc).


Also you might want to coordinate with @splodingsocks on the `install` command stuff -- I think he's been working in that space lately?

**Comment by ryyppy** [comment]
Yeah, style is very subjective... right now I just defined the `eslint` scaffold, which only checks `eqeqeq` for now... at least it stops my vim to complain about `import` statements to be an unknown keyword.

Thanks for the tip, I thought @splodingsocks was exclusively working on the OCAML part.

**Comment by splodingsocks** [comment]
@ryyppy I've finished the search command, and the install command is almost done, but if you have time, I wouldn't mind at all if you wanted to take over. I've been getting pretty busy lately, and my work os slow. I'll push up my almost-finished install command, and you can tell me what you think.

**Comment by splodingsocks** [comment]
Also, I'm cool with ESLint, too.

**Comment by ryyppy** [comment]
@splodingsocks Would be happy to take over :-)

**Comment by ryyppy** [comment]
Since the `install` command branch was merged, this issue is resolved
