### ISSUE TITLE
Lerna and flow-typed

### ISSUE THREAD

**Issue by gmaggess** [flowtype/flow-typed#650]
All,

I'm currently using [lerna](https://github.com/lerna/lerna) in my project and it doesn't seem possible to instruct flow-typed to crawl for all package.json files and drop the type definition files under a root level _flow-typed_ folder. 
Since lerna is becoming more and more popular these days I think flow-typed could benefit from it.

Cheer,

**Comment by 0xR** [comment]
I am running into the same issue. Has this been fixed?

**Comment by sibelius** [comment]
@gmaggess how did you fixed this issue?

**Comment by 0xR** [comment]
This reminds me of :joy:: https://xkcd.com/979/

Also, I may have found a solution:

1. go to `packages/mypackage`
2. run: `../../node_modules/.bin/flow-typed install --flowVersion=0.44.1`

This actually installs in `../../flow-typed`.

**Comment by ravicious** [comment]
This workaround seems to no longer work as of flow-typed 2.1.2.

**Comment by gmaggess** [comment]
I have a a _decls_ directory in the root level - same level as _packages_ folder - with all common types cross monorepo and one _decls_ folder under each package where I keep the type declarations specific for each package.  In the **.flowconfig** file I have:
```
...
[libs]
decls
packages/mypackage1/decls
packages/mypackage2/decls
...
packages/mypackagen/decls
...
```

On the root package.json I have the script ```"lint:flow": "flow check"```

Hope this helps.

**Comment by ravicious** [comment]
@gmaggess: Thanks! This is what I managed to set up as well. I have a single `flow-typed` directory with all the necessary type definitions. The main downside of this approach is that I have to manage the type defs manually, since I no longer can just run `yarn run flow-typed install`.

**Comment by jacobwgillespie** [comment]
To solve this issue, I just wrote a script that is run at the root of the lerna project.  It finds all `package.json` files and runs flow-typed there:

**scripts/update-flow-libdefs.sh**

```bash
#!/bin/bash

base_dir="$(pwd)"
flow_typed="$base_dir/node_modules/.bin/flow-typed"

find . -name package.json -not -path '*node_modules*' -print0 | while read -d '' -r package_json; do
  package_dir="$(dirname "$package_json")"

  echo "Updating flow libdefs for $package_dir:"
  echo

  cd "$base_dir" || exit 1
  cd "$package_dir" || exit 1
  "$flow_typed" install -p "$base_dir/package.json"
done

echo "Done"
```

**Comment by Inkdpixels** [comment]
I Forgot to mention it in this issue, but my current client sponsored a CLI to solve a few issues, this included, for mono-repo flow applications.

Regarding this specific issue take a look at [`flow-mono install-types`](https://immoweltgroup.gitbooks.io/flow-mono-cli/docs/cli/install-types.html) which does the job a bit more safer IMO since it also checks if the package.json includes a dependency to `flow-bin` and `flow-typed`.

**Comment by vjpr** [comment]
@jacobwgillespie You can use `lerna exec` too.

```
lerna exec --scope=@foo/bar -- \$LERNA_ROOT_PATH/scripts/flow-typed-recursive.sh
```

```sh
#!/usr/bin/env bash

echo $LERNA_ROOT_PATH
RELPATH=$(realpath --relative-to=$LERNA_ROOT_PATH $PWD/flow-typed)
echo $RELPATH
flow-typed install --libdefDir=$RELPATH
```

---

@Inkdpixels I couldn't get `flow-mono install-types` to work. I have `flow-bin` and `flow-typed` as dev dependencies in a package and it doesn't work.

Workspaces set to:

```
 "workspaces": [
    "packages/*"
  ]
```

**Comment by Inkdpixels** [comment]
@vjpr could you reproduce / setup a test-repo where this issue occurs so I can help you out? :)

**Comment by vjpr** [comment]
@Inkdpixels I found the issue. If there is no `.flowconfig` file in the sub-repo it doesn't create the `flow-typed` folder. But it still says "installing defs in 1 package".

I think there should be `--verbose` option. And is `.flowconfig` file really required?

**Comment by vjpr** [comment]
@Inkdpixels 

> Maintains a single or fallback .flowconfig across all packages.

Don't understand this.

---

Also, could we have something to run *one* instance of flow? Like automatically adding sub-repo [libs] like suggested in https://github.com/flowtype/flow-typed/issues/650#issuecomment-303784665

**Comment by Inkdpixels** [comment]
@vjpr I think flow and maybe even flow-typed(?) require a flowconfig in the working directory if I am not mistaken (which is the packages of the mono-repo). 

The quote from the Readme is true btw, as it relates to the `flow-mono create-links` command. :smile: 

The verbose Idea is great! Could you create an issue? (I'm currently on the Road)

**Comment by nnennajohn** [comment]
@Inkdpixels , I've seen your comment on many threads where I was trying to get flow working in the manner described here. 

It took me several several tries, and I thought I'd leave a comment here for the next person. A lot of your comment kept directing people to the package, but failing to specify in your documentation and in the comments the two things below, let me down a near futile circle. You know those ones were you keep "googling" different phrases in hope for a different response, but it was kept coming back to some comment you wrote saying to check the package you wrote. 

All this to say, it works. But proper documentation could have save quite a few hours/days. As vjpr mentioned above, he tried this, but likely also missed the below.

1: All docs on the site are correct. Just incomplete.
2: You need a .flowconfig file in every package folder you want flow-typed.
3: You need flow-bin and flow-typed set up as devDependencies in any of the packages you want flow typed. If you want it in all packages, you can probably use lerna's --hoist feature.

2 and 3 seem very straight forward, but somehow, I think most people might just like me, assume having flow installed in just the root-workspace and have a .flowconfig in the root would suffice.

I was really close to giving up. But with just those two changes, finally got it working for all packages  happily with lerna, yarn workspaces, storybook, etc.

Ok. That is all. 

Thanks again for the package. Just thought I'd save someone else the circular "googling" I've done over the past several hours, with quite a few breaks in between. :) :)

**Comment by AndrewSouthpaw** [comment]
@nnennajohn If you want to be extra wonderful and open a PR documenting the steps, you'd be a 🌟.

**Comment by nnennajohn** [comment]
@AndrewSouthpaw, you are right. Will put a PR for it. 

Thank you.
