### ISSUE TITLE
`orderBy` should accept also a function

### ISSUE THREAD

**Issue by masylum** [flowtype/flow-typed#655]
https://github.com/flowtype/flow-typed/blob/master/definitions/npm/lodash_v4.x.x/flow_v0.38.x-/lodash_v4.x.x.js#L204-L205

```js
_.orderBy([a, b, c], Boolean, ['asc'])
```

should be valid

**Comment by GAntoine** [comment]
Closing as this is currently the case in the latest version of the `lodash` def.
