### ISSUE TITLE
Travis-CI test fails when running from cloned repo

### ISSUE THREAD

**Issue by mathiasrw** [flowtype/flow-typed#667]
I cloned this repo, and asked travis to test (no change)

"./travis.sh" exited with 1 (error) informing me that

    This command only works in a clone of flowtype/flow-typed. It is a tool used to run tests of the library definitions in the flow-typed project.

https://travis-ci.org/AlaSQL/alasql-flow-typed/jobs/203756425#L877

It would be awesome if I could run the travis test when editing on my own repo so I can be sure my future PR is smooth and perfect.

Running ` ./run_def_tests.sh` gives me the same message

![skaermbillede 2017-02-21 21 57 09](https://cloud.githubusercontent.com/assets/1063454/23162329/ab11c8cc-f881-11e6-8d25-60dfb5676905.png)

**Comment by marudor** [comment]
As a workaround you can use flow-typed as folder (and repo) name.
If the folder is named flow-typed it should work.
