### ISSUE TITLE
flow-typed install generates libdefs without escaped quotes

### ISSUE THREAD

**Issue by nicotroia** [flowtype/flow-typed#673]
I ran `flow-typed install`

It generated certain files, specifically `browser-env_vx.x.x.js` with declarations such as:

    declare module 'browser-env/test/Existing falsey node globals don't get overwritten' {
      declare module.exports: any;
    }

    declare module 'browser-env/test/Function shouldn't return the same instance' {
      declare module.exports: any;
    }

And running `flow` calls them out:
    
    Library parse error:
    flow-typed/npm/browser-env_vx.x.x.js:33
     33: declare module 'browser-env/test/Existing falsey node globals don't get overwritten' {
                                                                           ^ Unexpected identifier

**Comment by trevorwhitney** [comment]
I'm seeing the same problem, with the same library

**Comment by mimshwright** [comment]
I think this may be fixed in v2.0.31 of browser-env https://github.com/lukechilds/browser-env/issues/42#event-1066822516
