### ISSUE TITLE
Partial definitions

### ISSUE THREAD

**Issue by magicmark** [flowtype/flow-typed#675]
Hey!

What are your thoughts on accepting a PR for "partial" definitions for libraries? We have some half-complete flow def files for the methods we use for [flot](https://github.com/flot/flot). Would it be helpful?

**Comment by GAntoine** [comment]
#178

**Comment by GAntoine** [comment]
@magicmark If you've still got those definitions lying around, I'd love to see them. There have been talks about how to integrate WIP definitions. At the very least, you could throw everything in a PR and leave it open, for someone else to pickup.
