### ISSUE TITLE
Typedefs for lib are ignored when placeholder file exists

### ISSUE THREAD

**Issue by alexfedoseev** [flowtype/flow-typed#676]
When placeholder file and file w/ typedefs are side by side, typedefs are ignored by flow, e.g.:

```
|- flow-typed/
   |- npm/
      |- reselect_v2.x.x.js // <= doesn't work
      |- reselect_vx.x.x.js
```

As a workaround for updates:

```shell
rm -rf flow-typed && flow-typed install
```

**Comment by Rauttis** [comment]
Ran into the same thing. Maybe flow-typed update should delete libdef stubs when proper definitions are available?

**Comment by GAntoine** [comment]
@Rauttis You can pass the `-o` or `--overwrite` flag to the `flow-typed install` or `flow-typed update` commands, which will overwrite existing stubs.

**Comment by Rauttis** [comment]
Well that's the thing, it's not overwriting generated stubs at all. If there's a stub called bluebird_vx.x.x.js and then later bluebird_v3.x.x.js becomes available, flow-typed doesn't touch bluebird_vx.x.x.js at all.

Also according to the help printed by flow-typed `flow-typed update` is just an alias for `flow-typed install --overwrite`.

**Comment by GAntoine** [comment]
Yeah my bad, I was wrong about what `--overwrite` did with `install`. So after taking a peek at the code, it seems overwrite will only overwrite a manually edited version of a libdef, not the stub, just like you're experiencing. I've updated the docs to match that behaviour.

As for the actual issue, I agree it should be fixed to remove/replace the stub.

**Comment by GAntoine** [comment]
@Rauttis Wrote a quick PR to address this. 

@alexfedoseev
