### ISSUE TITLE
Question: Should we define aliases as well?

### ISSUE THREAD

**Issue by joeycozza** [flowtype/flow-typed#684]
I am using Bluebird's .thenReturn() which is an alias of .return(), but thenReturn() is not defined in bluebird's definition file, and I was wondering if aliases were explicitly not defined, or if I should create a PR with that addition?

Thanks so much.

**Comment by marudor** [comment]
Feel free to create a PR.

**Comment by joeycozza** [comment]
PR submitted https://github.com/flowtype/flow-typed/pull/708
