### ISSUE TITLE
Okay to commit type definitions that overwrite existing ones (underscorejs)?

### ISSUE THREAD

**Issue by lewisf** [flowtype/flow-typed#692]
At Coursera, we use a more complete version of the UnderscoreJS types that includes support for all both types of invocations of underscore as well as chaining. I see that there are already UnderscoreJS type implementations but they're fairly incomplete -- would it be okay to open a pull-request to overwrite the existing ones since what we have is pretty different?

If so, how does this play with flow-typed cli?

**Comment by GAntoine** [comment]
Hey @lewisf, would you still have those typedefs lying around? If they are better then the current ones, I don't see why we wouldn't replace them.
