### ISSUE TITLE
When should tests be required?

### ISSUE THREAD

**Issue by jeffmo** [flowtype/flow-typed#70]
We have the ability to write tests that exercise libdefs, but sometimes when there is only one definition file it can feel a bit redundant to have to specify a test for the libdef you just wrote.

Would it be a good idea to require at least one test file for each libdef (just to ensure the libdef typechecks with itself)? 

cc @marudor @splodingsocks @ryyppy

**Comment by ryyppy** [comment]
I don't really understand... do you mean we should be able to skip e.g. `test_underscore-v1.js` entirely?
How would a single-libdef-test file look like?

**Comment by jeffmo** [comment]
Ok thinking more about this, I think it's best if we always require at least one test (like underscore had). At minimum it makes it easier for future contributors to quickly add new test cases.
