### ISSUE TITLE
GitHub auth documentation

### ISSUE THREAD

**Issue by mvolkmann** [flowtype/flow-typed#721]
When I run `flow-typed install`, it prompts for my GitHub username and password.
I haven't found any documentation on why it does that.
Why is that needed?
If I just press enter for both, it still runs.
What do I give up by doing that?

**Comment by GAntoine** [comment]
Interesting, I've never heard of that happening. It may be do to your setup, as you don't need Github auth information to fetch and cache the repo.

**Comment by FDiskas** [comment]
Usually it's happening on CI. Then requests to github are reaching his limits. :pizza:
