### ISSUE TITLE
Jest module 'jest'.

### ISSUE THREAD

**Issue by anton-kabysh** [flowtype/flow-typed#724]
Running flow i got error in my `npm test` script where I use Jest:
```
const jest = require('jest');
                  ^^^^^^^^^^^^^^^ jest. Required module not found
```
Flow-typed are properly installed and configured, cause all other modules are properly resolved by flow. After some investigation I had found, that `flow-typed/npm/jest_v19.x.x.js` does not contain jest module declaration. I added `jest.js` to `flow-typed/npm` with content:
```
declare module 'jest' {
    declare module.exports: any; 
}
```
And it fix problem.

**Comment by mmazzarolo** [comment]
Same issue here.

**Comment by marudor** [comment]
Currently the jest typings have no typings for cli usage. Only the globals to use it as testrunner.
(require('jest') is never needed to actually use jest. Just for cli usage I guess? - No one typed it yet.)
Feel free to send a PR.
Happy to merge it. (Although I would prefer typings instead of any)

**Comment by GAntoine** [comment]
Closed as we now have jest typings.
