### ISSUE TITLE
doesn't support requires with slashes

### ISSUE THREAD

**Issue by mvolkmann** [flowtype/flow-typed#737]
I used flow-typed to install type definitions for lodash.
If I required lodash like the following, I get the type checking I expect:
```js
const _ = require('lodash');
```
However, if I do it like this because I'm only using the string functions in lodash, type checking no longer works:
```js
const _ = require('lodash/string');
```
I suppose this is because 'lodash/string' doesn't match any file under `flow-typed/npm`.
Should this kind of require be supported?

**Comment by hackhat** [comment]
Any solution for this? Is very annoying... maybe we need to update the flow type def for lodash to support this?

**Comment by GAntoine** [comment]
Fixed, as lodash no exports individual functions.
