### ISSUE TITLE
React-Router v4: missing history in ContextRouter

### ISSUE THREAD

**Issue by michalkvasnicak** [flowtype/flow-typed#769]
According to documentation, the shape of [ContextRouter](https://github.com/flowtype/flow-typed/blob/master/definitions/npm/react-router-dom_v4.x.x/flow_v0.38.x-/react-router-dom_v4.x.x.js#L62) is not valid because methods like `push(), replace(), ...` are passed as [`history` object](https://reacttraining.com/react-router/web/api/Route/Route-props).

**Comment by kouak** [comment]
See #714 which corrects this exact issue.

**Comment by kouak** [comment]
#714 has been merged, I suppose this one could be closed !
