### ISSUE TITLE
Error about `connect(mapStateToProps, mapDispatchToProps)` in flow-typed/npm/react-redux_v5.x.x.js

### ISSUE THREAD

**Issue by alwaysonlinetxm** [flowtype/flow-typed#778]
I got en error with `connect(mapStateToProps, mapDispatchToProps)` when use flow-typed.

here is the error:

    85: export default connect(mapStateToProps, mapDispatchToProps)(Root);
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function call. Function cannot be called on 
    any member of intersection type
     85: export default connect(mapStateToProps, mapDispatchToProps)(Root);
                        ^^^^^^^ intersection
      Member 1:
       50:   declare function connect<A, OP>(
                                     ^ polymorphic type: function type. See lib: flow-typed/npm/react-
    redux_v5.x.x.js:50
      Error:
       85: export default connect(mapStateToProps, mapDispatchToProps)(Root);
                                  ^^^^^^^^^^^^^^^ function. This type is incompatible with
       51:     ...rest: Array<void> // <= workaround for https://github.com/facebook/flow/issues/2360
                              ^^^^ undefined. See lib: flow-typed/npm/react-redux_v5.x.x.js:51
      Member 2:
       54:   declare function connect<A, OP>(
                                     ^ polymorphic type: function type. See lib: flow-typed/npm/react-
    redux_v5.x.x.js:54
      Error:
       85: export default connect(mapStateToProps, mapDispatchToProps)(Root);
                                  ^^^^^^^^^^^^^^^ function. This type is incompatible with
       55:     mapStateToProps: Null,
                                ^^^^ union: null | undefined. See lib: flow-typed/npm/react-redux_v5.x.x.js:55
        Member 1:
         48:   declare type Null = null | void;
                                   ^^^^ null. See lib: flow-typed/npm/react-redux_v5.x.x.js:48
        Error:
         85: export default connect(mapStateToProps, mapDispatchToProps)(Root);
                                    ^^^^^^^^^^^^^^^ function. This type is incompatible with
         48:   declare type Null = null | void;
                                   ^^^^ null. See lib: flow-typed/npm/react-redux_v5.x.x.js:48
        Member 2:
         48:   declare type Null = null | void;
                                          ^^^^ undefined. See lib: flow-typed/npm/react-redux_v5.x.x.js:48
        Error:
         85: export default connect(mapStateToProps, mapDispatchToProps)(Root);
                                    ^^^^^^^^^^^^^^^ function. This type is incompatible with
         48:   declare type Null = null | void;
                                          ^^^^ undefined. See lib: flow-typed/npm/react-redux_v5.x.x.js:48
      Member 3:
       61:   declare function connect<S, A, OP, SP>(
                                     ^ polymorphic type: function type. See lib: flow-typed/npm/react-
    redux_v5.x.x.js:61
      Error:
       85: export default connect(mapStateToProps, mapDispatchToProps)(Root);
                                                   ^^^^^^^^^^^^^^^^^^ function. This type is incompatible with
       63:     mapDispatchToProps: Null,
                                   ^^^^ union: null | undefined. See lib: flow-typed/npm/react-redux_v5.x.x.js:63
        Member 1:
         48:   declare type Null = null | void;
                                   ^^^^ null. See lib: flow-typed/npm/react-redux_v5.x.x.js:48
        Error:
         85: export default connect(mapStateToProps, mapDispatchToProps)(Root);
                                                     ^^^^^^^^^^^^^^^^^^ function. This type is incompatible with
         48:   declare type Null = null | void;
                                   ^^^^ null. See lib: flow-typed/npm/react-redux_v5.x.x.js:48
        Member 2:
         48:   declare type Null = null | void;
                                          ^^^^ undefined. See lib: flow-typed/npm/react-redux_v5.x.x.js:48
        Error:
         85: export default connect(mapStateToProps, mapDispatchToProps)(Root);
                                                     ^^^^^^^^^^^^^^^^^^ function. This type is incompatible with
         48:   declare type Null = null | void;
                                          ^^^^ undefined. See lib: flow-typed/npm/react-redux_v5.x.x.js:48
      Member 4:
       68:   declare function connect<A, OP, DP>(
                                     ^ polymorphic type: function type. See lib: flow-typed/npm/react-
    redux_v5.x.x.js:68
      Error:
       85: export default connect(mapStateToProps, mapDispatchToProps)(Root);
                                  ^^^^^^^^^^^^^^^ function. This type is incompatible with
       69:     mapStateToProps: Null,
                                ^^^^ union: null | undefined. See lib: flow-typed/npm/react-redux_v5.x.x.js:69
        Member 1:
         48:   declare type Null = null | void;
                                   ^^^^ null. See lib: flow-typed/npm/react-redux_v5.x.x.js:48
        Error:
         85: export default connect(mapStateToProps, mapDispatchToProps)(Root);
                                    ^^^^^^^^^^^^^^^ function. This type is incompatible with
         48:   declare type Null = null | void;
                                   ^^^^ null. See lib: flow-typed/npm/react-redux_v5.x.x.js:48
        Member 2:
         48:   declare type Null = null | void;
                                          ^^^^ undefined. See lib: flow-typed/npm/react-redux_v5.x.x.js:48
        Error:
         85: export default connect(mapStateToProps, mapDispatchToProps)(Root);
                                    ^^^^^^^^^^^^^^^ function. This type is incompatible with
         48:   declare type Null = null | void;
                                          ^^^^ undefined. See lib: flow-typed/npm/react-redux_v5.x.x.js:48
      Member 5:
       75:   declare function connect<S, A, OP, SP, DP>(
                                     ^ polymorphic type: function type. See lib: flow-typed/npm/react-
    redux_v5.x.x.js:75
      Error:
       85: export default connect(mapStateToProps, mapDispatchToProps)(Root);
                                                   ^^^^^^^^^^^^^^^^^^ function. Could not decide which case to select
       77:     mapDispatchToProps: MapDispatchToProps<A, OP, DP>,
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ union type. See lib: flow-typed/npm/react-
    redux_v5.x.x.js:77
        Case 1 may work:
         20:   declare type MapDispatchToProps<A, OP: Object, DP: Object> = ((dispatch: Dispatch<A>, ownProps: OP) => DP) | DP;
                                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^function 
        type. See lib: flow-typed/npm/react-redux_v5.x.x.js:20
            But if it doesn't, case 2 looks promising too:
             85: export default connect(mapStateToProps, mapDispatchToProps)(Root);
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ type parameter `DP` of function call
            Please provide additional annotation(s) to determine whether case 1 works (or consider merging it with case 2):
             81: function mapDispatchToProps(dispatch) {
                                             ^^^^^^^^ parameter `dispatch`
      Member 6:
       82:   declare function connect<S, A, OP, SP, DP, P>(
                                     ^ polymorphic type: function type. See lib: flow-typed/npm/react-
    redux_v5.x.x.js:82
      Error:
       85: export default connect(mapStateToProps, mapDispatchToProps)(Root);
                                               ^^^^^^^^^^^^^^^^^^ function. Could not decide which case to select
       84: mapDispatchToProps: MapDispatchToProps<A, OP, DP>,
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ union type. See lib: flow-typed/npm/react-redux_v5.x.x.js:84
    Case 1 may work:
     20:   declare type MapDispatchToProps<A, OP: Object, DP: Object> = ((dispatch: Dispatch<A>, ownProps: OP) => DP) | DP;
                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: flow-typed/npm/react-redux_v5.x.x.js:20
    But if it doesn't, case 2 looks promising too:
     85: export default connect(mapStateToProps, mapDispatchToProps)(Root);
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ type parameter `DP` of function call
    Please provide additional annotation(s) to determine whether case 1 works (or consider merging it with case 2):
     81: function mapDispatchToProps(dispatch) {
                                     ^^^^^^^^ parameter `dispatch`

Does any one know what's wrong here ?

**Comment by sporto** [comment]
Annotating the function `mapDispatchToProps` worked for me

```

import type { Dispatch } from "redux"

...

const mapDispatchToProps = (dispatch: Dispatch<*>) => {
  return {
    ...
  }
}
```

**Comment by gustavjf** [comment]
Thanks @sporto, that fixed the issue for me.

Just out of curiosity, do you know why the existential type in angled brackets is necessary for getting rid of the errors? I understand it tells Flow to infer the type according to context, but I'm not exactly sure how that solves the problem in this particular case.

**Comment by sporto** [comment]
As connect can take many different function permutations it seems that Flow cannot figure out which one of the polymorphic set are you passing. By adding the type annotation `(dispatch: Dispatch<*>)` Flow can tell which one it is.

**Comment by dvakatsiienko** [comment]
Met exact the same issue. Thnx, @sporto, this solutions works.

**Comment by tomaskazatel** [comment]
Thank you @sporto this has been hurting me for a whole week and thanks to you I have solved it today.

**Comment by eMarek** [comment]
I had quite similar issue. This is the error which I was getting:
`
  70:16  error  Case 3 may work: 'polymorphic type: function type'. See https://github.com/facebook/flow/blob/v0.57.3/lib/react-redux_v5.x.x.js#L98  flowtype-errors/show-errors
`

In my case problem was that I forgot to apply type on function return value.
From this:
```
function mapStateToProps(state: any, ownProps: any) {
  return {
    something: "something"
  }
}
```
To this:
```
function mapStateToProps(state: any, ownProps: any): Object {
  return {
    something: "something"
  }
}
```

I hope it will help someone.
