### ISSUE TITLE
Test only against newer versions of flow

### ISSUE THREAD

**Issue by sibelius** [flowtype/flow-typed#788]
Right now it tests against `flow` from v.0.44.1 until v0.15.0.

I think it would be easier to test only against the last 5 or 10 flow versions

**Comment by jeffmo** [comment]
Do you mean in terms of libdef directory syntax? You can do this with an uncapped range:

`mylibdef-v1.2.3/flow_v0.44-`

The trailing `-` means: "Flow v0.44.1 and after". If it stops working at some future version, can just cap it off at the last working version, copy the directory, fix things to work in the new version, and then you'll have two libdefs -- one for each compatible Flow version range:

`mylibdef-v1.2.3/flow_v0.44-v0.51/`
`mylibdef-v1.2.3/flow_v0.52-/`
