### ISSUE TITLE
After upgrading to 2.1.0 no type definitions are found anymore

### ISSUE THREAD

**Issue by doberkofler** [flowtype/flow-typed#792]
I just upgraded to version 2.1.0 and after removing all type definitions and running flow-typed again no library definitions are found anymore and flow-typed simply generates stubs for all dependencies.

**Comment by jeffmo** [comment]
Thanks for the report, I'll take a look at this later today.

In the meantime I'm curious if the new install command works for you (`flow-typed new-install `)? It's a rewrite of a lot of stuff with lots more tests

**Comment by mpajunen** [comment]
We had the same problem after upgrading to 2.1.0: 

`flow-typed install` found no definitions.

`flow-typed new-install` works correctly and found the correct updated definitions.

**Comment by jeffmo** [comment]
Good to know. Ill just replaced `install ` with `new-install ` in a patch release here in a few mins

**Comment by jeffmo** [comment]
Ok, 2.1.1 is out with `install` replaced by `new-install`.
Please let me know if you have any more installation issues

**Comment by doberkofler** [comment]
@jeffmo Working now. Thank you. What about update?
