### ISSUE TITLE
flow-typed@2.1.1 install exits with non-zero status, which is too different from 2.1.0

### ISSUE THREAD

**Issue by xaka** [flowtype/flow-typed#795]
Hi there,

Doing `flow-typed install` gives us `!! No flow@v0.38.0-compatible libdefs found in flow-typed for the above untyped dependencies !!` as before, but in 2.1.0 the exit code was 0 and in 2.1.1 it changed to 1, and scripts start failing. I don't believe it's something that should have ended up in patch version release. Way too backward incompatible :)

Thanks!

**Comment by doberkofler** [comment]
Same problem here and actually also `flow-typed update` does no longer return 0.
Generally not a big deal but now when invoking flow-typed using `npm run` also fails and all CI scripts as well.

**Comment by jeffmo** [comment]
Apologies: I moved the `new-install` command over to replace the `install` command and must've missed this inconsistency between the two.

I have a patch release coming up to fix some other issues, so I'll make sure this is fixed in that as well.

**Comment by doberkofler** [comment]
@jeffmo seems to be solved in 2.1.1
