### ISSUE TITLE
Cache a local git checkout rather than scanning libdefs through the GitHub API

### ISSUE THREAD

**Issue by jeffmo** [flowtype/flow-typed#80]
Currently `flow-typed install` will hit the GitHub API multiple times for each call. Unfortunately, because the GitHub API is aggressively rate-limited, this means CLI users will run into issues with this approach fairly quickly.

Instead, we should probably just take inspiration from tools like Homebrew and manage a locally-cached checkout of the repo (say, in somewhere like `~/.flow-typed/repo-cache` -- and I suppose `% USERPROFILE%` on windows).

**Comment by jeffmo** [comment]
I'm going to start working on this today

**Comment by marudor** [comment]
Is there a way to not use the rate limited API at all?
I'm using internet that is shared with lots of others quite often. (Conferences, Hackerspaces, Train for instance)
If we need to create a mirror for now I would be fine hosting on that updates whenever commits change.

**Comment by jeffmo** [comment]
@marudor: Yes, that's the idea -- Instead of using the API, we'll effectively clone a copy of the repo into a cache directory, and use that cached copy to scan for libdefs locally. AFAIK there's no rate-limiting on git operations like `clone`/`rebase`/etc

**Comment by jeffmo** [comment]
(Note that the locally-cached checkout is also how Homebrew works, and that seems to work fairly well)

**Comment by marudor** [comment]
Ah okay - Yea, everything fine in that case. Carry on.
