### ISSUE TITLE
More helpful message when flow-version mismatch

### ISSUE THREAD

**Issue by edorivai** [flowtype/flow-typed#801]
Not sure if this should be implemented, but just leaving my experience with the CLI here as a datapoint :)

I tried installing type declarations for koa (v2), and received the following feedback:

```
$ flow-typed install koa@2.x.x
• Searching for 1 libdefs...
!! No libdefs found in flow-typed for the explicitly requested libdefs. !!

Consider using `flow-typed create-stub koa@2.x.x` to generate an empty libdef that you can fill in.
```

Turns out there are type declarations available, just for a different version of Flow. This is perhaps easily understood or figured out if you're experienced with the Flow ecosystem, but it's not so straightforward if you're just getting started.

It might be worth considering to print all of the supported flow versions for a library.

Printing the output of `flow-typed search koa` would already be helpful:

```
$ flow-typed search koa
• rebasing flow-typed cache...done.

Found definitions:
╔══════╤═════════════════╤═════════════════════╗
║ Name │ Package Version │ Flow Version        ║
╟──────┼─────────────────┼─────────────────────╢
║ koa  │ v2.x.x          │ >=v0.38.x <=v0.38.x ║
╟──────┼─────────────────┼─────────────────────╢
║ koa  │ v2.x.x          │ >=v0.37.x <=v0.37.x ║
╚══════╧═════════════════╧═════════════════════╝
```

**Comment by techieshark** [comment]
The above PR is the simplest possible improvement for now - it just includes the flow version in the output, which I hope might be enough to explain what's going on.
