### ISSUE TITLE
Redux: Using compose for higher order components causes error

### ISSUE THREAD

**Issue by natenorberg** [flowtype/flow-typed#816]
The type definition for `compose` in redux seems to expect that that function is only used with store enhancers, but it can be used more generically. We tend to use it for creating higher order components:

```javascript
const wrapComponent = compose(
  connect(mapStateToProps, mapDispatchToProps),
  injectIntl,
);

export default wrapComponent(MyComponent);
```

Would there be any downside to changing the type definition to something more generic, like:
```javascript
declare function compose(...funcs?: Array<Function>): Function;
```
(copied from `flowRight` in lodash)

**Comment by keithkml** [comment]
Another option is the way it's done for [`recompose`](https://github.com/flowtype/flow-typed/blob/master/definitions/npm/recompose_v0.24.x/flow_v0.47.x-/recompose_v0.24.x.js):

```js
declare type Compose = (<A, B, C, D, E, F, G, H, I>(
    hi: UnaryFn<H, I>,
    gh: UnaryFn<G, H>,
    fg: UnaryFn<F, G>,
    ef: UnaryFn<E, F>,
    de: UnaryFn<D, E>,
    cd: UnaryFn<C, D>,
    bc: UnaryFn<B, C>,
    ab: UnaryFn<A, B>,
    ...rest: Array<void>
  ) => UnaryFn<A, I>) &
  (<A, B, C, D, E, F, G, H>(
    gh: UnaryFn<G, H>,
    fg: UnaryFn<F, G>,
    ef: UnaryFn<E, F>,
    de: UnaryFn<D, E>,
    cd: UnaryFn<C, D>,
    bc: UnaryFn<B, C>,
    ab: UnaryFn<A, B>,
    ...rest: Array<void>
```
(etc)

**Comment by GAntoine** [comment]
Closing since the latest defs seems to have changed to what you're looking for.
