### ISSUE TITLE
Provide a web ui to search for lib defs

### ISSUE THREAD

**Issue by StokeMasterJack** [flowtype/flow-typed#848]

**Comment by GAntoine** [comment]
@StokeMasterJack Ask, and ye shall receive: http://flowtyped.gantoine.com

I had a blast writing this thing. Let me know if there's anything you'd like to see on there. Note that I'm not affiliated with the flow-typed project in any way, but I couldn't resist throwing something together.

**Comment by marudor** [comment]
@jeffmo Could probably got an Idea what to do with this.
