### ISSUE TITLE
Allow specification of custom directory

### ISSUE THREAD

**Issue by joncursi** [flowtype/flow-typed#870]
I'd like to resurrect the idea proposed in https://github.com/flowtype/flow-typed/issues/194

My reasons aren't style-based, it's functional. I am using Flow in my [Meteor app](https://www.meteor.com/) and I'd obviously like to use flow-typed. But there's a problem.

The meteor build system eagerly loads all files in your project root that are not

A) dot files or dot folders
B) not called `imports`

Therefore, Meteor tries to eagerly load the `flow-typed` directory into the application bundle and, well, there's no way to stop it. It crashes the server.

![screen shot 2017-05-25 at 9 51 03 pm](https://cloud.githubusercontent.com/assets/4974609/26477540/4cdb071c-4194-11e7-817e-5ed658962684.png)

I vote for an option in `.flowconfig` to point to a custom `flow-typed` directory. In my case, I want to name it `.flow-typed`.

**Comment by joncursi** [comment]
cc @benjamn

**Comment by johhansantana** [comment]
no news on this?

**Comment by peterobrien** [comment]
Being able to specify a custom location would be helpful to share an in-the-works flow-typed folder across multiple local projects. Symlinks for `flow-typed/` don't work do they? Another other suggestions?

**Comment by GAntoine** [comment]
@johhansantana @peterobrien Although I kinda still agree with jeff, I'll take a crack at this over the weekend. I make no promises.

**Comment by peterobrien** [comment]
Thanks @GAntoine - apologies from me, I should have said I'm a noob with flow and I might be overlooking something (not sure why I waited so long to try it, it's really cool!). For my current tinkering, I just want to share one frequently changing module declaration across multiple projects. Another way to solve my requirement it seems is to simply put a reference in `libs` in the `.flowconfig`. The only problem with this though it also seem the `libs` are cached(?), and therefore when the module declaration changes flow doesn't notice until I explicitly restart the server.

So maybe I don’t really want this for myself right now. It might be useful still to me though if I could add an additional `flow-typed` folder location

**Comment by GAntoine** [comment]
Across multiple project, yeah you'd want to use references in `[libs]`. I'm not sure about the libs being cached, but since you're experiencing it I'll trust is happening.

It's the third time this feature has been proposed, and although I don't fully agree with @joncursi use case (I feel meteor should have a `.meteorconfig` to ignore certain folders), there are more valid use cases, especially for developers who like full control over their project's folder structure.
