### ISSUE TITLE
[CLI] CLI should look at cwd and use locally-installed binary (if present)

### ISSUE THREAD

**Issue by jeffmo** [flowtype/flow-typed#88]
One problem with `npm install -g` is that it installs an executable at a certain version -- whereas various projects could be built using/expecting a different version.

One way I dealt with this for the Jest CLI was to look at `CWD` and try to determine if we're currently inside a project that depends on the CLI (and, if so, delegate execution to the *local* version instead of the globally-installed version).

This should also help reduce the frequency with which people need to update their global CLI version.

**Comment by bassettsj** [comment]
Agreed. This is why `grunt-cli` exists.

**Comment by ryyppy** [comment]
Are you talking about the `flow-typed` cli binary?

**Comment by jeffmo** [comment]
@ryyppy: right

**Comment by jeffmo** [comment]
(PS: I have this PR mostly ready, just need to test a bit more before I send it out for review)
