### ISSUE TITLE
underscore pick method failing after upgrade to flow 0.47.0

### ISSUE THREAD

**Issue by doberkofler** [flowtype/flow-typed#887]
After upgrading to flow 0.47.0 using the underscore pick method in the following way fails with an error `call of method `pick`. Method cannot be called on any member of intersection type`:
```
const config = _.pick({a: 1, b: 2, d:4}, ['a', 'b', 'c']);
```

**Comment by GAntoine** [comment]
Seems this was fixed with at deeae5cc98077dccc3101011de2964c638f174f4
