### ISSUE TITLE
flow-typed/moment bad signature for isBetween function

### ISSUE THREAD

**Issue by remetalosse** [flowtype/flow-typed#891]
Hello people, just a little typo I found today that provokes unwanted flow errors.

1. Go to flow-typed/definitions/npm/moment_v2.x.x/flow_v0.34.x-/moment_v2.x.x.js
2. Go to line 203. There is: `
 isBetween(date: moment$Moment|string|number|Date|Array<number>): boolean`

3. It should be`
 isBetween(date: moment$Moment|string|number|Date|Array<number>, date: moment$Moment|string|number|Date|Array<number>): boolean;`

**Comment by jeroenbourgois** [comment]
@remetalosse I already put out a PR for this :)
