### ISSUE TITLE
[CLI] Libdef install fail with `invalid comparator error` when package version set to 'github' instead of semver (e.g. `"flow-bin": "github:flowtype/flow-bin"`)

### ISSUE THREAD

**Issue by AlexxNica** [flowtype/flow-typed#895]
## <div align="center">👎 Before</div>
<div align="center">
<code>package.json</code>
<br>
<img src="https://cloud.githubusercontent.com/assets/14338588/26555422/5b4c3f62-446b-11e7-92df-3f6387dbe52f.png" alt="package.json snippet containing flow-bin: github:flowtype/flow-bin" title="package.json snippet containing flow-bin: github:flowtype/flow-bin">
 <br><br>
<code>Terminal</code>
<img src="https://cloud.githubusercontent.com/assets/14338588/26555547/e2a028c0-446b-11e7-849e-cc63501556ff.png" alt="screenshot from terminal after unsuccessful installation of flow-bin libdef because of invalid comparator error" title="screenshot from terminal after unsuccessful installation of flow-bin libdef because of invalid comparator error">
<br><br><br></div>
</div>

## <div align="center">👍 After</div>
<div align="center">
<code>package.json</code>
<br>
<img src="https://cloud.githubusercontent.com/assets/14338588/26555425/5dacd69a-446b-11e7-9a9a-5ca9ef56a134.png" alt="package.json snippet containing flow-bin: ^0.47.0" title="package.json snippet containing flow-bin: ^0.47.0">
<br><br>
<code>Terminal</code>
<img src="https://cloud.githubusercontent.com/assets/14338588/26555548/e3411a5a-446b-11e7-8bbb-6ec0e249ee79.png" alt="screenshot from terminal after successful intallation of flow-bin libdef" title="screenshot from terminal after successful intallation of flow-bin libdef">
</div>

-----

## Expected Result
The installation should not fail when I use 'github:' or any other form of Git URL to set a version in package.json, since it's permitted to do so.

This probably ain't semver's fault, since it's being used mainly to compare versions coming from package.json and the 'github:' or Git URLs are not backed by semver specification.

## Extra Info
``` haskell
❯ flow-typed version
flow-typed@2.1.2
```
``` haskell
❯ npm version
{ statistics: '1.0.0',
  npm: '4.6.1',
  ares: '1.10.1-DEV',
  cldr: '30.0.3',
  http_parser: '2.7.0',
  icu: '58.2',
  modules: '51',
  node: '7.10.0',
  openssl: '1.0.2k',
  tz: '2016j',
  unicode: '9.0',
  uv: '1.11.0',
  v8: '5.5.372.43',
  zlib: '1.2.11' }
```
``` haskell
❯ flow version
Flow, a static type checker for JavaScript, version 0.47.0
```
``` haskell
❯ uname -a
Darwin *****.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
```

**Comment by marudor** [comment]
#1127 Feature Issue for this.
