### ISSUE TITLE
Should this belong to a community org?

### ISSUE THREAD

**Issue by splodingsocks** [flowtype/flow-typed#9]
I'm glad to have this repo under my name. But would it be more appropriate to create a 'FlowCommunity' GH org and move it there?

**Comment by jeffmo** [comment]
So we have a "FlowTyped" GH org already for Flow-oriented tooling. It's also pretty well set up to host community-driven projects like this one (meaning: non-FB employees can still manage repos, I *think* we'd bet the benefits of a paid Travis account (will have to check on that one), etc).

I'd be happy to follow up on our end if everyone is on board with moving this effort into that org?

**Comment by splodingsocks** [comment]
Sounds good to me :+1:

**Comment by jeffmo** [comment]
(Clarification: the org is called "FlowType" -- I've edited the typo in my prev comment)

**Comment by marudor** [comment]
Moving to the FlowType organisation would be awesome.
Once everything is set up I'm also more than happy to contribute and merge my collection of definitions (https://github.com/marudor/flowInterfaces/issues/6)

**Comment by splodingsocks** [comment]
@jeffmo I tried to transfer ownership to you tonight, but it looks like you've already got a fork, so it wouldn't transfer. Let me know when to try again!

**Comment by jeffmo** [comment]
Deleted my repo

**Comment by splodingsocks** [comment]
Nice!
