### ISSUE TITLE
Isn't possible to add test that cache is not broken please?

### ISSUE THREAD

**Issue by steida** [flowtype/flow-typed#905]
Every week...

```
 flow-typed cache...done.
UNCAUGHT ERROR: Error: swagger-schema-official_v2.x.x-: 'swagger-schema-official_v2.x.x-' is a malformed definitions/npm/ directory name! Expected the name to be formatted as <PKGNAME>_v<MAJOR>.<MINOR>.<PATCH>
    at validationError (/Users/steida/.nvm/versions/node/v7.8.0/lib/node_modules/flow-typed/dist/lib/libDefs.js:804:11)
    at parseRepoDirItem (/Users/steida/.nvm/versions/node/v7.8.0/lib/node_modules/flow-typed/dist/lib/libDefs.js:731:5)
    at addLibDefs$ (/Users/steida/.nvm/versions/node/v7.8.0/lib/node_modules/flow-typed/dist/lib/libDefs.js:304:27)
    at tryCatch (/Users/steida/.nvm/versions/node/v7.8.0/lib/node_modules/flow-typed/node_modules/regenerator-runtime/runtime.js:64:40)
```

**Comment by steida** [comment]
Please fix it asap. I will pay for it. That's terrible that defs are broken so often.

**Comment by steida** [comment]
I am such git lama. This saved me (github for mac)

![screen shot 2017-05-31 at 23 22 28](https://cloud.githubusercontent.com/assets/66249/26654698/156a551c-4658-11e7-8a42-c47a5ac4f7c0.png)

**Comment by dunnock** [comment]
That has nothing to do with cache, it is a bug in definition name!
`https://github.com/flowtype/flow-typed/tree/master/definitions/npm/swagger-schema-official_v2.x.x-` , should not be `-` at the end.  @marudor @StefanoMagrassi please fix asap, it breaks flow install process!

**Comment by StefanoMagrassi** [comment]
@dunnock @steida which is your flow-typed cli version? (current stable is 2.1.2)

**Comment by StefanoMagrassi** [comment]
@dunnock @steida take a look to [this line](https://github.com/flowtype/flow-typed/blob/master/cli/src/lib/libDefs.js#L329) in the source code: cli support for prerelease versions was added on december (commits [fb76126](https://github.com/flowtype/flow-typed/commit/fb7612683c8a2546d95bfe58f91f50c654ecd066#diff-25f5a9122677a86e95aa68bff622b32c) and [a4de23b](https://github.com/flowtype/flow-typed/commit/a4de23b1698f121dd57d449af114dcb196dde04b#diff-25f5a9122677a86e95aa68bff622b32c))

[Here](https://regex101.com/r/guPf2A/1) you can also test the regex against the directory name that throwns error on your local installation

**Comment by dunnock** [comment]
Sorry I missed this and thank you for pointing out, works after upgrading! So it appears it is breaking change in flow-typed.. should not new version be flow-typed 3.0.0 then? seems everyone must upgrade now.

**Comment by sboudrias-aa** [comment]
Still happens for me on 2.1.2

```
UNCAUGHT ERROR: Error: jasmine_v2.4.x/flow_vx.x.x: The major version of a Flow version string cannot be `x`, it must be a number!
```

**Comment by dunnock** [comment]
@sboudrias-aa there is no such dir flow_vx.x.x in git: https://github.com/flowtype/flow-typed/tree/master/definitions/npm/jasmine_v2.4.x , you sync to local flow-typed repo?

**Comment by augbog** [comment]
Also running into this issue

**Comment by AfflatusX** [comment]
this is still broken with latest flow-bin. can someone please fix it?

**Comment by natasha08n** [comment]
I still face such issue in dependencies which don't follow normal pattern major.minor.patch but in dependencies with links to other internal repos. Any luck on this issue? All answers are welcomed

**Comment by lukerayman** [comment]
I'm also facing this issue. The only workaround I found is to completely remove `flow-typed` folder and reinstall them again. No way to update without this error. 👎
