### ISSUE TITLE
Ramda: NestedObject is too restrictive

### ISSUE THREAD

**Issue by stevenyap** [flowtype/flow-typed#917]
`declare type NestedObject<T> = { [k: string]: T | NestedObject<T> }` insists that the object must contain the same type for all values in the object which is too restrictive because an object can contain different combination of value types such as string, number, boolean, etc.

I think we should type NestedObject as `type NestedObject = { [k: string]: string | number | boolean, | null | NestedObject }`

@ajhyndman @dchambers @mattgstevens @mwalkerwells Would love to know your thoughts on this

**Comment by mwalkerwells** [comment]
That's too restrictive as it doesn't allow polymorphic & non-primitive types.


> ...object can contain different combination of value types

Object literals / maps are strongly typed in Flow. Seems like you understand them to be arbitrary containers of key values. If that's your use case, you should use ```Object``` as a type, which removes type checking (same as ```any```, bound to ```Objects```).

I might be able to help if you have a specific example?

**Comment by stevenyap** [comment]
Thanks for the explanation. I will re-open this issue again when I faced a specific example. :)

**Comment by ajhyndman** [comment]
@stevenyap If you find this that flow is not accepting an object with multiple value types, you could try explicitly annotating it:

```
const myObj: NestedObject<number | string> = {
  a: 'string',
  b: 12,
};
```

**Comment by stevenyap** [comment]
A convoluted example off my head is when using redux, a state object may be typed as

```
type State = {
  products: { [id: string]: Product }
}
type Product = {
  title: string,
  owner: {
    name: string,
    id: string
  }
}
const state: State = {
  products: {
    one: {
      title: 'Title',
      owner: {
        name: 'Owner',
        id: '123'
      }
    }
  }
}

// When we try to access using path on state
R.path(['products', 'one', 'owner', 'id'], state)

App.js:58
 58: R.path(['products', 'one', 'owner', 'id'], state)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `path`. Function cannot be called on any member of intersection type
563:   declare function path<V,A:?NestedObject<V>>(p: Array<string>, ...rest: Array<void>): (o: A) => ?V;
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ intersection. See lib: flow-typed/npm/ramda_v0.x.x.js:563
  Member 1:
  563:   declare function path<V,A:?NestedObject<V>>(p: Array<string>, ...rest: Array<void>): (o: A) => ?V;
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ polymorphic type: function type. See lib: flow-typed/npm/ramda_v0.x.x.js:563
  Error:
   36:   | {
           ^ object type. This type is incompatible with
  563:   declare function path<V,A:?NestedObject<V>>(p: Array<string>, ...rest: Array<void>): (o: A) => ?V;
                                                                                      ^^^^ undefined. See lib: flow-typed/npm/ramda_v0.x.x.js:563
  Member 2:
  564:   declare function path<V,A:?NestedObject<V>>(p: Array<string>, o: A): ?V;
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ polymorphic type: function type. See lib: flow-typed/npm/ramda_v0.x.x.js:564
  Error:
   41:   owner: {
                ^ property `id`. Property not found in
   37:       products: { [id: string]: Product }
                                       ^^^^^^^ object type


```

I am not 100% sure why flow throws an error but I am guessing it is because of the typing of NestedObject.

**Comment by ajhyndman** [comment]
It does look like you're right.  Flow can't recognize that the definition of State matches the recursive type definition of NestedObject.

Interestingly, if you take the type annotation off of `const state: State = // ...`, then flow is perfectly happy with the invocation.  It seems that flow is picking a naive value for type parameter V, in the case that a part of the parameter's type has been aliased.

**Comment by stevenyap** [comment]
I think flow matches State to NestedObject correctly:
```
declare type NestedObject<T> = { [k: string]: T | NestedObject<T> }
type State = {
  products: { [id: string]: Product }
}
```
so T is Product

```
declare function path<V,A:?NestedObject<V>>(p: Array<string>, o: A): ?V;

R.path(['products', 'one', 'owner', 'id'], state)
```
so path must return a type of V which is T which is Product

and hence the error

```
 Error:
   41:   owner: {
                ^ property `id`. Property not found in
   37:       products: { [id: string]: Product }
                                       ^^^^^^^ object type
```

because flow is expecting a Product

Hence, NestedObject typing is too strict (at least in path case even though I have encountered it in other functions too)

I think perhaps NestedObject should be:
```
declare type NestedObject = { [k: string]: * | NestedObject }
// or maybe just Object???
```

**Comment by mwalkerwells** [comment]
Since you're declaring that ```state``` is of type ```State```, you cannot pass it into a function expecting a invariant recursive type (read/write privileges). 

You need to annotate ```NestedMap``` values as covariant, thus allowing subtypes.

[Try Flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AZRQIYo4C8oA3oqKBgE6wAmArgMYoDOAXBaANrspaASwB2AcwC63AAr1mbUAF9Ey1JhyzGrFKDKVqKISmhZuA4eIA0VUAhFZa3fdVAiCAW1OhzosdZegQgxmgr42yqossCIC3oTE3PhEpBQ2dFpsXKkB0V7OAYbGXgDkACpGJsX+Abbw9o7ZNdRuntzFAPJ1DlU2TUFtAIwATADMxb0uygFTSirIDFgs0AS0OOjYoAByWAJYDO0ARgBWiygAPADSlqAAagB8ujwA1LwXUregAD5bO8T7x6dLtd7rMmmDwRDqIgFksVjhIEwRGwhNEaEQABZA253AAUAEFaLQCGhLndrttdv8TmwsfcAJTcAD8N2QGAxON4xXS8g4VVAxVyfIFXVoQqCxQk1wEyTpQA)
```js
// @flow

type State = {
  products: { [string]: Product }
}

type Product = {
  title: string,
  owner: {
    name: string,
    id: string
  }
}

const state: State = {
  products: {
    one: {
      title: 'Title',
      owner: {
        name: 'Owner',
        id: '123'
      }
    }
  }
}

declare type NestedMap<K, V> = { +[K]: V | NestedMap<K, V> }
                                
declare function path<K, V>(Array<K>, NestedMap<K, V>): ?V

path(['products', 'one', 'owner', 'id'], state)
```

**Comment by mwalkerwells** [comment]
It's worth noting that a more specific union is a subtype of a less specific union.
```V``` is a subtype of ```V | NestedMap<*, *>```


https://medium.com/@mwalkerwells/disjoint-union-intersection-relationships-with-flow-600b0cde9b32

**Comment by stevenyap** [comment]
@mwalkerwells I have no idea what is covariant `{ +[K]: V | NestedMap<K, V> }` and I can't find any reference for object values in flow docs.


However using the `NestedMap`, there is an issue:

[Try Flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AZRQIYo4C8oA3oqKBgE6wAmArgMYoDOAXBaANrspaASwB2AcwC63AAr1mbUAF9Ey1JhyzGrFKDKVqKISmhZuA4eIA0VUAhFZa3fdVAiCAW1OhzosdZegQgxmgr42yqossCIC3oTE3PhEpBQ2dFpsXKkB0V7OAYbGXgDkACpGJsX+Abbw9o7ZNdRuntzFAPJ1DlU2TUFtAIwATADMxb0uygFTSirIDFgs0AS0OOjYoAByWAJYDO0ARgBWiygAPADSlqAAagB8ujwA1LwXUregAD5bO8T7x6dLtd7rMFksVjhIEwRGwhNEaEQABZA253AAUAEFaLQCGhLndrttdv8TmwUfcAJTcAD8N2QURiOgINJ84keGCRaN4xXS8g4VVAxVyAqFXVoIqCxQk1wEyQpyCAA)

```
// @flow

type State = {
  products: { [string]: Product }
}

type Product = {
  title: string,
  owner: {
    name: string,
    id: string
  }
}

const state: State = {
  products: {
    one: {
      title: 'Title',
      owner: {
        name: 'Owner',
        id: '123'
      }
    }
  }
}

declare type NestedObject<K, V> = { +[K]: V | NestedObject<K, V> }
declare function path<K, V>(Array<K>, NestedObject<K, V>): ?V

const a: ?string = path(['products', 'one', 'owner', 'id'], state)
```

will generate an error

```
30: const a: ?string = path(['products', 'one', 'owner', 'id'], state)
                       ^ object type. This type is incompatible with
30: const a: ?string = path(['products', 'one', 'owner', 'id'], state)
              ^ string
```

where Flow is expecting `path` to return an object instead of a string.

**Comment by mwalkerwells** [comment]
This type returns an optional polymorphic type ```V```, which is a Sum type (union) of the value types of the recursive object.

In your example, you want ```string``` to be a subtype of this type.

This should work...
```js
declare function path<K, V, R: V>(Array<K>, NestedObject<K, V>): ?R
```

**Comment by mwalkerwells** [comment]
That's why this works...
```js
type Return = 'products' | NestedObject<*, *>

const a: ?Return = path(['products', 'one', 'owner', 'id'], state)
```

**Comment by mwalkerwells** [comment]
```?string``` is not the correct type, as there are no guarantees that key path is valid & will return that type. Indicating it as an optional is not sufficient.

This code cannot be statically typed the way you propose.

**Comment by mwalkerwells** [comment]
```js
declare function path<K, V, R: V>(Array<K>, NestedObject<K, V>): ?R

const a: ?string = path(['products', 'one', 'owner', 'id'], state)
```

**Comment by stevenyap** [comment]
@mwalkerwells NestedObject or NestedMap?

> declare function path<K, V, R: V>(Array<K>, NestedObject<K, V>): ?R
> const a: ?string = path(['products', 'one', 'owner', 'id'], state)

**Comment by mwalkerwells** [comment]
Sorry, was using those interchangeably. I renamed ```NestedObject``` to ```NestedMap``` as a more accurate name.

**Comment by mwalkerwells** [comment]
```R``` here is bounded by the type ```V```, thus it's subtype. I believe all ```?``` types are subtypes of all non-```?``` types.

**Comment by mwalkerwells** [comment]
That also means this works to be clear...

```js
const a: ?boolean = path(['products', 'one', 'owner', 'id'], state)
```

**Comment by mwalkerwells** [comment]
Which makes sense... Given this random ```Array``` of keys, the result _may_ be this type.

**Comment by stevenyap** [comment]
I don't understand why...
If this works... `declare function path<K, V, R: V>(Array<K>, NestedMap<K, V>): ?R`,
then why doesn't this works `declare function path<K, V>(Array<K>, NestedMap<K, V>): ?V`?

Since R is bounded to V, we can replace R with V... can't we?

**Comment by mwalkerwells** [comment]
> Since R is bounded to V, we can replace R with V... can't we?
No. Bounded just means the ```V``` type acts as the "upper limit" of the type, thus the subtype relationship.

**Comment by stevenyap** [comment]
I am quite thoroughly confused at this point
but if this works `const a: ?boolean = path(['products', 'one', 'owner', 'id'], state)`, it also means that we have lost all type information when we use `path`, isn't it?

The type State/Product does not even have boolean types in it.

**Comment by mwalkerwells** [comment]
Right, you'll need to refactor to avoid dynamically accessing properties. If you want a more specific type.

You're not saying a boolean is a value in this object. You're saying there might be one.

**Comment by mwalkerwells** [comment]
You haven't lost all type information.

This does not work...
```js
const a: boolean = path(['products', 'one', 'owner', 'id'], state)
```

**Comment by stevenyap** [comment]
> const a: boolean = path(['products', 'one', 'owner', 'id'], state)
This doesn't work because flow is complaining a could be null or undefined... not that a is boolean.

If we don't type a `const a = path(['products', 'one', 'owner', 'id'], state)`, is flow able to infer that a is actually a ?string which is as per our State/Product definition

**Comment by mwalkerwells** [comment]
Flow cannot infer this since you're dynamically accessing the value, not statically.

**Comment by stevenyap** [comment]
thank you for you time to help me to understand flow better
but this really feels like a lost battle since flow cannot infer after we dynamically access the value through `path`

so at least we should declare path as
`declare function path<K, V, R: V>(Array<K>, NestedMap<K, V>): ?R` ?

**Comment by mwalkerwells** [comment]
You post on stackoverflow if you want to explore other approaches & copy the link here. You should close "Ramda: NestedObject is too restrictive".

**Comment by mwalkerwells** [comment]
Happy to help!

**Comment by mwalkerwells** [comment]
The declarative way to implement this is with lenses. They actually need to be added to the library definition if you want to contribute something. :)

Took a quick look at it (with hacky ```unwrap``` type)...
```js
// @flow

declare type UnaryFn<A,R> = (a: A) => R

declare type Compose = & (<A,B,C,D,E,F,G>(fg: UnaryFn<F,G>, ef: UnaryFn<E,F>, de: UnaryFn<D,E>, cd: UnaryFn<C,D>, bc: UnaryFn<B,C>, ab: UnaryFn<A,B>, ...rest: Array<void>) => UnaryFn<A,G>)
  & (<A,B,C,D,E,F>(ef: UnaryFn<E,F>, de: UnaryFn<D,E>, cd: UnaryFn<C,D>, bc: UnaryFn<B,C>, ab: UnaryFn<A,B>, ...rest: Array<void>) => UnaryFn<A,F>)
  & (<A,B,C,D,E>(de: UnaryFn<D,E>, cd: UnaryFn<C,D>, bc: UnaryFn<B,C>, ab: UnaryFn<A,B>, ...rest: Array<void>) => UnaryFn<A,E>)
  & (<A,B,C,D>(cd: UnaryFn<C,D>, bc: UnaryFn<B,C>, ab: UnaryFn<A,B>, ...rest: Array<void>) => UnaryFn<A,D>)
  & (<A,B,C>(bc: UnaryFn<B,C>, ab: UnaryFn<A,B>, ...rest: Array<void>) => UnaryFn<A,C>)
  & (<A,B>(ab: UnaryFn<A,B>, ...rest: Array<void>) => UnaryFn<A,B>)

declare var compose: Compose

type __Unwrap<V, K, O: { [K]: V }> = V
type Unwrap<K, O> = __Unwrap<*, K, O>

type NestedObject = {
  a: {
    b: 'foo'
  }
}

type Lens<K> = <O: {}>(O) => Unwrap<K, O>

declare var lensA: Lens<'a'>
declare var lensB: Lens<'b'>
    
declare var testObject: NestedObject
    
const composedLenses = compose(lensB, lensA)
const value: 'foo' = test(testObject)
```
[Try Flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAmBTAxtAhgJzaAC4CeADgQKoB2exAYlQDwCCANAEoB8oAvKABTYAXKGYBKXt3bJ0WPARLlQAYVgBbUrADOBPgDIBLVgCFWy1gBFWAUVZ1WAcU79IAcxHVaDRvaetQaJAeNLj0TLZ0nP7owV5MVtZRoBgosaHe5hZJAEYYaWGMpspJ2Nn53mzGSQB0tfhahCLMuLjYxIwAbrAAliicEjzcnulMbE5iiKCgBvxGRZY2ds6B5eFL0WirjAlJKVuZOXmgwwVFJWXHIQWVNXVoDU0tbZ09fQNDVxVLE1Mzc2YLRL8GKXOLbGy7VKgkaMA7+XJbM7+UpbG7+WrVeqNURPdpdXr9STQ64Qn7TQyVAFZfh7YkZSyHRFmc6oky3TH3bHNVp416EwZ00YMsl-SnFfgIwWFZnIi4nL5VdF3B44nkvAnvKVsYoiilswRyz5CxWgDFYx5q-FvIny439GSYHD4UAdPDJdSaHQiVQabRoZCKAgAfSD1HgrVIjAAav4ANL+ADyIgA3qAANqxgC6IijoAAvtw+FHEIHLuHsJH46AE4XQCGwxHGAAqOOJzgBsgEABynLQKAT2QAVphCLxQMnJqBhOPJ1MLgBySCwWDzyd5xDrkud0AAGTQVC0jFjtcYSfHBf4Cc1DYrR7bDrkztduFA0H3WmYIj3B8Y8+w8-bWQnQIZ9X3fYwv3fX9sgA2dQFQR15BdN1CE5AdhwwbEewaPt0JHODEAwWAD1HIjfR0FBvx0LQxzIz00H4N8D1MMCD3EQjiIaZDoAAV02UBF2Xecx1Qhp+FEwg8MwsQgA)

**Comment by mwalkerwells** [comment]
https://vimeo.com/104807358
https://medium.com/@drboolean/lenses-with-immutable-js-9bda85674780

**Comment by stevenyap** [comment]
@mwalkerwells thanks for pointing this out! I have not used lens before but I am curious to try and learn. Will contribute after I understand them.

However, I don't understand your advice... do you mean that we should use lens over path in the use case of `const a = path(['products', 'one', 'owner', 'id'], state)`?

**Comment by mwalkerwells** [comment]
Yes, if you want a more specific static type for your example function.

**Comment by wi-ski** [comment]
This issue is infuriating \o.o/ - the answer is to use lenses?

**Comment by AndrewSouthpaw** [comment]
Related: #3372. I'd say track the conversation there.
