### ISSUE TITLE
Exported literal types do not work in other file.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [flowtype/flow-typed#934]
I'm maintaining a file of names for Redux action types, to ensure there are no naming collisions. I would expect this to complain, but it doesn't:

```js
// file1.js
export const foo: 'foo' = 'foo'

// file2.js
import { foo } from './file1'
export type FooAction = { type: typeof foo }
const FooActionCreator = (): FooAction => ({ type: 'notfoo' })
```

But this does, when it's all in the same file:

```js
const foo: 'foo' = 'foo'
export type FooAction = { type: typeof foo }
const FooActionCreator = (): FooAction => ({ type: 'bar' })
```

Am I doing something wrong here, or is this a bug?

**Comment by lukebelliveau** [comment]
I'm having a similar issue. I'm trying to hold my type aliases in one file and export them, but they seem to only work when the type alias is defined in the same file it is used. This complains, like I'd expect:
```es6
//reducer.js
type State = {
 aNumber: number,
};

const initialState = {
 aNumber: 'this is not a number'
}

reducer(state: State = initialState, action){...}
```

However, this does not:
```es6
//Types.js
export type State = {
 aNumber: number,
};

//reducer.js
import type { State } from  './Types.js'

const initialState = {
 aNumber: 'this is not a number'
}

reducer(state: State = initialState, action){...}
```

I figure it's a bug, my syntax is identical to what's shown in the [docs](https://flow.org/en/docs/types/modules/) as far as I can tell.

**Comment by GAntoine** [comment]
Hey @AndrewSouthpaw, is this still an issue?

**Comment by AndrewSouthpaw** [comment]
Hmm, looks like this is no longer an issues. Yay for bugs resolving themselves on their own. 🙌

**Comment by GAntoine** [comment]
![Magic.](http://s2.quickmeme.com/img/df/df2071e1084c273fe910863f1b2cfde86f938c161259d95e8fd0ee5d893b0c6f.jpg)
