### ISSUE TITLE
[redux-actions v2.x.x] Multiple typed arguments for payload creator not supported

### ISSUE THREAD

**Issue by floriangosse** [flowtype/flow-typed#936]
I seems that the libdef for redux-actions v2.x.x don't support multiple typed arguments for payload creators. Here is an example [flow.org/try/#...](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVATApgYxgQwCcswoBXAOxwBcBLOCsHY-arAQRvooB4AVADRgACkOEAmAHwAKVGDDUAngAcsALjCC5YZfkXx8GAMItqcQhukB9DcICUYALySR4gdoAkAfg1YAtspKqHaWuvpwhrZCAHSxxADO1Br4FIoA2gC6Ds5gAN4KKuqaQmEGGLZuYFiEhOY+YABGcHAwWClgAL4A3OjMbWycdAzSAOQAFlgw8CNC0lDNGomEtBQA5kINRBoA8g0AVrjU2S7SudrzcELam4SoHXZ2XUA) which shows the error.

The current tests are not failing because they don't have type definitions for the arguments: [definitions/npm/redux-actions_v2.x.x/flow_v0.34.x-/test_createAction.js#L62](https://github.com/flowtype/flow-typed/blob/e8ca1e6a1a51c0934c8dd12b372a96bf808817aa/definitions/npm/redux-actions_v2.x.x/flow_v0.34.x-/test_createAction.js#L62).

I tried to fix it by myself (#935) but I don't have enough experience in libdefs - especially generics for rest parameters.

**Comment by floriangosse** [comment]
I fixed it now. Would be nice if someone could review it: https://github.com/flowtype/flow-typed/pull/935.

**Comment by GAntoine** [comment]
Closing since fixed.
