### ISSUE TITLE
[koa_v2.x.x] Import error

### ISSUE THREAD

**Issue by selkinvitaly** [flowtype/flow-typed#961]
Hi,

I'm trying to use types for koa 2.2. When I use `import type { Server } from 'koa' ` then I get error:
`Named import from module koa. This module has no named export called Server.`
Screen: https://prnt.sc/fl6rf5

Can anyone tell me, how can I fix it?

> node - 8.1.1
> flow-bin - 0.47.0
> koa - 2.2.0
> flow-typed 2.1.2

**Comment by GAntoine** [comment]
Taking at look at the koa definition, looks like you'll need `ServerType `.

```
import type { ServerType } from 'koa'
```

Have a look: https://github.com/flowtype/flow-typed/blob/master/definitions/npm/koa_v2.0.x/flow_v0.47.x-/koa_v2.0.x.js#L17

**Comment by selkinvitaly** [comment]
@GAntoine thanks, It fine works for me
