### ISSUE TITLE
What is the best way to express inner class?

### ISSUE THREAD

**Issue by Ailrun** [flowtype/flow-typed#962]
I'm working with [openlayers](http://openlayers.org/) typing.
There is following inner class in code of _openlayers_.

``` javascript
// ol.Collection class
ol.Collection = function (/* ... parameters ... */) {
  // ... class construction codes ...
}
// ... some methods

// ol.Collection.Error class
ol.Collection.Error = function (/* ... parameters ... */) {
  // ... class construction codes ...
}
```

I try some typescript-like, C++-like, ... methods, (inner module, static inner class, ....) but no one works.
For example,

``` javascript
declare module 'ol' {
  declare module 'Collection' {
    declare class Error {
      // ....
    }
  }
}
```

is rejected by flow.

Is there any clean choice for this case? If it is, could you give me some direction for typing this one?

**Comment by Ailrun** [comment]
Solved.
https://github.com/facebook/flow/issues/4204#issuecomment-309608435

**Comment by Ailrun** [comment]
@tonio
Actually, I gave up because I postponed to use flow in my company until https://github.com/flowtype/flow-typed/issues/16 solved.

**Comment by tonio** [comment]
@Ailrun OK, thanks for the answer.
