### ISSUE TITLE
react-redux does not support memoized versions of mapDispatchToProps and mapStateToProps

### ISSUE THREAD

**Issue by cjhoward92** [flowtype/flow-typed#979]
In the react-redux api documentation there is an edge case for `mapDispatchToProps` and `mapStateToProps` where the consumer can pass in a function that returns another function as opposed to the `StateProps` or `DispatchProps`. Currently, it appears that flow-typed does not support this.

[See the 'Notes' here](https://github.com/reactjs/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options)

I tried adding a recursive type definition to `MapDispatchToProps` but I couldn't get it to work unless I returned `mixed` from the `MapDispatchToProps` union, like so:

```javascript
declare type MapDispatchToProps<A, OP: Object, DP: Object> = ((dispatch: Dispatch<A>, ownProps: OP) => mixed) | DP;
```

A recursive type like:

```javascript
declare type MapDispatchToProps<A, OP: Object, DP: Object> = ((dispatch: Dispatch<A>, ownProps: OP) => MapDispatchToProps<A, OP, DP>) | DP;
```

cannot work with the current tests. I also tried adding a new type called `MamoizedMapDispatchToProps` that I may be able to get to work, but I didn't know what the best solution to this problem would be, so I am reaching out to the community.

Either I am missing something completely or the memoize-able version of both functions do not exist.

**Comment by ericm546** [comment]
This is something that is impacting me as well. In the meantime I put a return type any, if I don't want flow to throw an error:
```javascript
const mapStateToPropsFactory = (): any => {
  const somethingSelector = selectors.somethingSelectorFactory();
  return (state: MyState, props: OwnProps) => ({
    something: somethingSelector(state, props.valueThatChangeBetweenComponents)
})}

const connector: Connector<OwnProps, Props> = connect(mapStateToPropsFactory);
export default connector(MyComponent);
```
