### ISSUE TITLE
Shall we publish `-beta.0` of the CLI?

### ISSUE THREAD

**Issue by jeffmo** [flowtype/flow-typed#98]
After a quick IRC conversation with @ryyppy and @marudor, it seems like we're ready to publish a beta version of the CLI at this point.

I've pushed the version in the package.json to [2.0.0-beta.0](https://github.com/flowtype/flow-typed/blob/master/cli/package.json#L3) so people can `npm install -g` it and start playing around.

cc @splodingsocks -- what do you think?

**Comment by alexbooker** [comment]
Yes please :smile:

**Comment by marudor** [comment]
Definitively in favor of publishing.

**Comment by splodingsocks** [comment]
@jeffmo so sorry I didn't read this message two days ago. Yes!

**Comment by ryyppy** [comment]
I was in an IRC conversation? Can't remember :joy: ... anyways I would be totally ready for this!

**Comment by jeffmo** [comment]
@ryyppy: Heh, I thought you were? Maybe I made that up in my head... Who knows
Anyway, `v2.0.0-beta.3` is published! Grab it with `npm install -g flow-typed` and lets see how things go

**Comment by alexbooker** [comment]
I'm looking forward to try it out :+1:
