### ISSUE TITLE
Yet another version validation error

### ISSUE THREAD

**Issue by bsonntag** [flowtype/flow-typed#983]
I don't know where this is coming from, but I'm getting this error when running `flow-typed install`:

`UNCAUGHT ERROR: Error: flow_v0.28.x <=v0.37.x: Unexpected trailing characters:  <=v0.37.x`

I'm using `flow-typed@2.1.2`.

**Comment by gb714us** [comment]
I encountered the same issue. This has to do with the fact that flow-typed doesn't understand the flow ranges. I believed i had to remove the trailing characters to get it to work. 

Sure, it might cause some issue in the future, but that's the issue that occurs. I'm unsure if that's valid.

**Comment by augbog** [comment]
I see this issue in `2.1.5` :/

**Comment by bsonntag** [comment]
> I believed i had to remove the trailing characters to get it to work.

@gb714us what do you mean with this? Where did you remove the trailing characters?

**Comment by adamawang** [comment]
@bsonntag assuming you fixed this already, but if anyone else is still getting this error, go to 
`flow-typed/npm/lodash_v4.x.x.js.` 
Remove the space in the flow-typed version header for a temporary fix. Will break again when downloading most recent libdef for lodash.

**Comment by dreid** [comment]
This should be fixed in v2.2 by #1311

**Comment by GAntoine** [comment]
Fixed and closing.
