### ISSUE TITLE
"No dependencies were found in this project's package.json!" shouldn't be a fatal error

### ISSUE THREAD

**Issue by omerzach** [flowtype/flow-typed#995]
We manage multiple packages in a single repo using [Lerna](https://github.com/lerna/lerna) but configure and run Flow globally at the top-level of the repo.

To run flow-typed for each package we give each package a script called `flow-typed` that runs `flow-typed install` and then call `lerna run flow-typed` from the top-level. It correctly adds flow-typed files to our top-level flow-typed folder.

However if one of our packages has no dependencies `flow-typed install` fails with `No dependencies were found in this project's package.json!`. As long as the `package.json` is valid and has no dependencies I don't see why this should be an error rather than just a warning. It's perfectly valid to have an NPM package with no dependencies.

**Comment by GAntoine** [comment]
Could you give an example of what an empty (with no dependencies) `package.json` looks like in your project?

**Comment by omerzach** [comment]
Sure. One example is a `colors` package with a bunch of constants (and some functions for manipulating colors) exported in an object. Our React web app and React Native apps, which are separate packages, both have it as a dependency. You can imagine all sorts of similar packages for constants or utilities.

```
{
  "name": "colors",
  "version": "1.0.0",
  "description": "Colors for Sigma's client apps",
  "main": "lib/index.js",
  "scripts": {
    …,
    "flow-typed": "flow-typed install  --flowVersion=0.49.1"
  },
  "author": "Sigma Accolade, Inc.",
  "dependencies": {},
  "devDependencies": {}
}
```

**Comment by GAntoine** [comment]
Yeah that makes sense, although I wonder why it's made to error out, @jeffmo can probably answer this.
