### ISSUE TITLE
Why does it add stub modules?

### ISSUE THREAD

**Issue by mikelambert** [flowtype/flow-typed#998]
When I run this on a react-native project, it generates stub types that basically export "any" for all of my react-native-* dependencies.

These dependencies may or may not have full flow typing, but they do have classes, methods, properties, and more, that should be type-checkable by flow.

I'm worried that the flow-typed auto-generated stubs that export `any` at a global export level, will override and destroy whatever type information was available/usable. How do you avoid conflicts and wiping out potentially-useful info?

**Comment by Anahkiasen** [comment]
I'm having the same issue, currently I delete manually the stub definitions as they confuse IntellijIDEA IDEs. The information they're able to gather from the actual sources provide better completion than the stubs. I wish there was a flag like `--no-stubs`

**Comment by GAntoine** [comment]
@mikelambert @Anahkiasen You can pass `--skip` to `flow-typed install`, which will skip installing stubs.

**Comment by Anahkiasen** [comment]
Didn't know that, nice! Thanks

**Comment by mikelambert** [comment]
Two thoughts:
- When running with the latest version 2.1.2, the `--skip` flag does not yet exist. Any interest in publishing another version to npm?
- Why does `install` produce stubs by default? Stubs seem to be better suited for users developing stubs, as opposed to users just using flow-typed in their project to get stubs. And there's always `create-stub` if a developer wishes to create and flesh out a particular stub module. So maybe it's seems worth reconsidering the default here?

**Comment by GAntoine** [comment]
@mikelambert You can use the bleeding edge of flow-typed globally by running `npm install -g flowtype/flow-typed`. This will give you access to the `--skip` flag, and, eventually, the `--packageDir` flag from #1002, that you reported at #999

**Comment by marudor** [comment]
I've just released 2.1.3. --skip does exist now.
