### ISSUE TITLE
Flow-bin checking fails to search parent package.json

### ISSUE THREAD

**Issue by mikelambert** [flowtype/flow-typed#999]
I have `flow-bin` installed in a parent package (since I want to keep my versioning in one place).

I have sub-packages, each with their own `package.json`. Unfortunately, trying to run `flow-typed` on these packages fails, because it can't find `flow-bin`:
```
cd UNCAUGHT ERROR: Error: Failed to find a flow-bin dependency in package.json.
Please install flow-bin: `npm install --save-dev flow-bin`
```

flow-typed should be smart enough to walk up the directory tree of `package.json` files looking for `flow-bin`, instead of checking only the current `package.json`.

**Comment by GAntoine** [comment]
If you could specify the directory of the `package.json` where `flow-bin` in installed, would that be good enough? Kinda like how they did it here: https://github.com/benmosher/eslint-plugin-import/pull/685

**Comment by mikelambert** [comment]
To be clear, you're proposing asking the user to pass commandline args for data the code could figure out itself, right?

But yes, it would work for my purposes. I'm hiding this call behind gulp tasks, so I can just pass extra args, and won't have to remember the syntax to use it.

**Comment by GAntoine** [comment]
Yes, exactly. It's not ideal, but its *good enough*.
